FROM ubuntu:18.04
MAINTAINER Oleg Morozenkov <m@oleg.rocks>

RUN apt-get -qq update && \
    apt-get -qq install -y \
        autotools-dev \
        binutils \
        build-essential \
        cmake \
        g++ \
        libboost-all-dev \
        libbz2-dev \
        libcurl4-openssl-dev \
        libicu-dev \
        libssl-dev \
        make \
        python-dev \
        wget \
        zlib1g-dev


WORKDIR /usr/src/tgbot-cpp
COPY include include
COPY src src
COPY test test
COPY CMakeLists.txt ./

RUN cmake -DENABLE_TESTS=ON . && \
    make -j$(nproc) && \
    make install


COPY samples samples

WORKDIR /usr/src/tgbot-cpp/samples/echobot
RUN rm -rf CMakeCache.txt CMakeFiles/ && \
    cmake . && make -j$(nproc)

WORKDIR /usr/src/tgbot-cpp/samples/echobot-curl-client
RUN rm -rf CMakeCache.txt CMakeFiles/ && \
    cmake . && make -j$(nproc)

WORKDIR /usr/src/tgbot-cpp/samples/echobot-webhook-server
RUN rm -rf CMakeCache.txt CMakeFiles/ && \
    cmake . && make -j$(nproc)

WORKDIR /usr/src/tgbot-cpp/samples/inline-keyboard
RUN rm -rf CMakeCache.txt CMakeFiles/ && \
    cmake . && make -j$(nproc)

WORKDIR /usr/src/tgbot-cpp/samples/photo
RUN rm -rf CMakeCache.txt CMakeFiles/ && \
    cmake . && make -j$(nproc)

WORKDIR /usr/src/tgbot-cpp/samples/received-text-processing
RUN rm -rf CMakeCache.txt CMakeFiles/ && \
    cmake . && make -j$(nproc)

WORKDIR /usr/src/tgbot-cpp
ENV CTEST_OUTPUT_ON_FAILURE=1
CMD make test

