var searchData=
[
  ['passportdata_0',['PassportData',['../class_tg_bot_1_1_passport_data.html',1,'TgBot']]],
  ['passportelementerror_1',['PassportElementError',['../class_tg_bot_1_1_passport_element_error.html',1,'TgBot']]],
  ['passportelementerrordatafield_2',['PassportElementErrorDataField',['../class_tg_bot_1_1_passport_element_error_data_field.html',1,'TgBot']]],
  ['passportelementerrorfile_3',['PassportElementErrorFile',['../class_tg_bot_1_1_passport_element_error_file.html',1,'TgBot']]],
  ['passportelementerrorfiles_4',['PassportElementErrorFiles',['../class_tg_bot_1_1_passport_element_error_files.html',1,'TgBot']]],
  ['passportelementerrorfrontside_5',['PassportElementErrorFrontSide',['../class_tg_bot_1_1_passport_element_error_front_side.html',1,'TgBot']]],
  ['passportelementerrorreverseside_6',['PassportElementErrorReverseSide',['../class_tg_bot_1_1_passport_element_error_reverse_side.html',1,'TgBot']]],
  ['passportelementerrorselfie_7',['PassportElementErrorSelfie',['../class_tg_bot_1_1_passport_element_error_selfie.html',1,'TgBot']]],
  ['passportelementerrortranslationfile_8',['PassportElementErrorTranslationFile',['../class_tg_bot_1_1_passport_element_error_translation_file.html',1,'TgBot']]],
  ['passportelementerrortranslationfiles_9',['PassportElementErrorTranslationFiles',['../class_tg_bot_1_1_passport_element_error_translation_files.html',1,'TgBot']]],
  ['passportelementerrorunspecified_10',['PassportElementErrorUnspecified',['../class_tg_bot_1_1_passport_element_error_unspecified.html',1,'TgBot']]],
  ['passportfile_11',['PassportFile',['../class_tg_bot_1_1_passport_file.html',1,'TgBot']]],
  ['photosize_12',['PhotoSize',['../class_tg_bot_1_1_photo_size.html',1,'TgBot']]],
  ['poll_13',['Poll',['../class_tg_bot_1_1_poll.html',1,'TgBot']]],
  ['pollanswer_14',['PollAnswer',['../class_tg_bot_1_1_poll_answer.html',1,'TgBot']]],
  ['polloption_15',['PollOption',['../class_tg_bot_1_1_poll_option.html',1,'TgBot']]],
  ['precheckoutquery_16',['PreCheckoutQuery',['../class_tg_bot_1_1_pre_checkout_query.html',1,'TgBot']]],
  ['proximityalerttriggered_17',['ProximityAlertTriggered',['../class_tg_bot_1_1_proximity_alert_triggered.html',1,'TgBot']]]
];
