var searchData=
[
  ['passportdata_944',['PassportData',['../class_tg_bot_1_1_passport_data.html',1,'TgBot']]],
  ['passportelementerror_945',['PassportElementError',['../class_tg_bot_1_1_passport_element_error.html',1,'TgBot']]],
  ['passportelementerrordatafield_946',['PassportElementErrorDataField',['../class_tg_bot_1_1_passport_element_error_data_field.html',1,'TgBot']]],
  ['passportelementerrorfile_947',['PassportElementErrorFile',['../class_tg_bot_1_1_passport_element_error_file.html',1,'TgBot']]],
  ['passportelementerrorfiles_948',['PassportElementErrorFiles',['../class_tg_bot_1_1_passport_element_error_files.html',1,'TgBot']]],
  ['passportelementerrorfrontside_949',['PassportElementErrorFrontSide',['../class_tg_bot_1_1_passport_element_error_front_side.html',1,'TgBot']]],
  ['passportelementerrorreverseside_950',['PassportElementErrorReverseSide',['../class_tg_bot_1_1_passport_element_error_reverse_side.html',1,'TgBot']]],
  ['passportelementerrorselfie_951',['PassportElementErrorSelfie',['../class_tg_bot_1_1_passport_element_error_selfie.html',1,'TgBot']]],
  ['passportelementerrortranslationfile_952',['PassportElementErrorTranslationFile',['../class_tg_bot_1_1_passport_element_error_translation_file.html',1,'TgBot']]],
  ['passportelementerrortranslationfiles_953',['PassportElementErrorTranslationFiles',['../class_tg_bot_1_1_passport_element_error_translation_files.html',1,'TgBot']]],
  ['passportelementerrorunspecified_954',['PassportElementErrorUnspecified',['../class_tg_bot_1_1_passport_element_error_unspecified.html',1,'TgBot']]],
  ['passportfile_955',['PassportFile',['../class_tg_bot_1_1_passport_file.html',1,'TgBot']]],
  ['photosize_956',['PhotoSize',['../class_tg_bot_1_1_photo_size.html',1,'TgBot']]],
  ['poll_957',['Poll',['../class_tg_bot_1_1_poll.html',1,'TgBot']]],
  ['pollanswer_958',['PollAnswer',['../class_tg_bot_1_1_poll_answer.html',1,'TgBot']]],
  ['polloption_959',['PollOption',['../class_tg_bot_1_1_poll_option.html',1,'TgBot']]],
  ['precheckoutquery_960',['PreCheckoutQuery',['../class_tg_bot_1_1_pre_checkout_query.html',1,'TgBot']]],
  ['proximityalerttriggered_961',['ProximityAlertTriggered',['../class_tg_bot_1_1_proximity_alert_triggered.html',1,'TgBot']]]
];
