// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BackgroundTypeChatTheme.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string BackgroundTypeChatTheme::TYPE = "chat_theme";

void from_json(const nlohmann::json& json, BackgroundTypeChatTheme& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "theme_name", value.themeName);
}

void to_json(nlohmann::json& json, const BackgroundTypeChatTheme& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "theme_name", value.themeName);
}

} // namespace TgBot
