// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BackgroundTypeFill.h"
#include "tgbot/Json.h"
#include "tgbot/types/BackgroundFill.h"

namespace TgBot {

const std::string BackgroundTypeFill::TYPE = "fill";

void from_json(const nlohmann::json& json, BackgroundTypeFill& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "fill", value.fill);
    Json::readRequiredField(json, "dark_theme_dimming", value.darkThemeDimming);
}

void to_json(nlohmann::json& json, const BackgroundTypeFill& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "fill", value.fill);
    Json::writeRequiredField(json, "dark_theme_dimming", value.darkThemeDimming);
}

} // namespace TgBot
