// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BackgroundFillFreeformGradient.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string BackgroundFillFreeformGradient::TYPE = "freeform_gradient";

void from_json(const nlohmann::json& json, BackgroundFillFreeformGradient& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "colors", value.colors);
}

void to_json(nlohmann::json& json, const BackgroundFillFreeformGradient& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "colors", value.colors);
}

} // namespace TgBot
