// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BackgroundTypeWallpaper.h"
#include "tgbot/Json.h"
#include "tgbot/types/Document.h"

namespace TgBot {

const std::string BackgroundTypeWallpaper::TYPE = "wallpaper";

void from_json(const nlohmann::json& json, BackgroundTypeWallpaper& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "document", value.document);
    Json::readRequiredField(json, "dark_theme_dimming", value.darkThemeDimming);
    Json::readOptionalField(json, "is_blurred", value.isBlurred);
    Json::readOptionalField(json, "is_moving", value.isMoving);
}

void to_json(nlohmann::json& json, const BackgroundTypeWallpaper& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "document", value.document);
    Json::writeRequiredField(json, "dark_theme_dimming", value.darkThemeDimming);
    Json::writeOptionalField(json, "is_blurred", value.isBlurred);
    Json::writeOptionalField(json, "is_moving", value.isMoving);
}

} // namespace TgBot
