// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BackgroundTypePattern.h"
#include "tgbot/Json.h"
#include "tgbot/types/BackgroundFill.h"
#include "tgbot/types/Document.h"

namespace TgBot {

const std::string BackgroundTypePattern::TYPE = "pattern";

void from_json(const nlohmann::json& json, BackgroundTypePattern& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "document", value.document);
    Json::readRequiredField(json, "fill", value.fill);
    Json::readRequiredField(json, "intensity", value.intensity);
    Json::readOptionalField(json, "is_inverted", value.isInverted);
    Json::readOptionalField(json, "is_moving", value.isMoving);
}

void to_json(nlohmann::json& json, const BackgroundTypePattern& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "document", value.document);
    Json::writeRequiredField(json, "fill", value.fill);
    Json::writeRequiredField(json, "intensity", value.intensity);
    Json::writeOptionalField(json, "is_inverted", value.isInverted);
    Json::writeOptionalField(json, "is_moving", value.isMoving);
}

} // namespace TgBot
