// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BackgroundType.h"
#include "tgbot/Json.h"
#include "tgbot/types/BackgroundTypeChatTheme.h"
#include "tgbot/types/BackgroundTypeFill.h"
#include "tgbot/types/BackgroundTypePattern.h"
#include "tgbot/types/BackgroundTypeWallpaper.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BackgroundType& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const BackgroundType& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
