// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotAccessSettings.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BotAccessSettings& value) {
    Json::readRequiredField(json, "is_access_restricted", value.isAccessRestricted);
    Json::readOptionalField(json, "added_users", value.addedUsers);
}

void to_json(nlohmann::json& json, const BotAccessSettings& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "is_access_restricted", value.isAccessRestricted);
    Json::writeOptionalField(json, "added_users", value.addedUsers);
}

} // namespace TgBot
