// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotCommandScopeChat.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string BotCommandScopeChat::TYPE = "chat";

void from_json(const nlohmann::json& json, BotCommandScopeChat& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "chat_id", value.chatId);
}

void to_json(nlohmann::json& json, const BotCommandScopeChat& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "chat_id", value.chatId);
}

} // namespace TgBot
