// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotCommandScopeAllPrivateChats.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string BotCommandScopeAllPrivateChats::TYPE = "all_private_chats";

void from_json(const nlohmann::json& json, BotCommandScopeAllPrivateChats& value) {
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const BotCommandScopeAllPrivateChats& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
