// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotCommandScopeChatAdministrators.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string BotCommandScopeChatAdministrators::TYPE = "chat_administrators";

void from_json(const nlohmann::json& json, BotCommandScopeChatAdministrators& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "chat_id", value.chatId);
}

void to_json(nlohmann::json& json, const BotCommandScopeChatAdministrators& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "chat_id", value.chatId);
}

} // namespace TgBot
