// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotCommand.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BotCommand& value) {
    Json::readRequiredField(json, "command", value.command);
    Json::readRequiredField(json, "description", value.description);
    Json::readOptionalField(json, "is_ephemeral", value.isEphemeral);
}

void to_json(nlohmann::json& json, const BotCommand& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "command", value.command);
    Json::writeRequiredField(json, "description", value.description);
    Json::writeOptionalField(json, "is_ephemeral", value.isEphemeral);
}

} // namespace TgBot
