// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotCommandScopeAllChatAdministrators.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string BotCommandScopeAllChatAdministrators::TYPE = "all_chat_administrators";

void from_json(const nlohmann::json& json, BotCommandScopeAllChatAdministrators& value) {
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const BotCommandScopeAllChatAdministrators& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
