// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotDescription.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BotDescription& value) {
    Json::readRequiredField(json, "description", value.description);
}

void to_json(nlohmann::json& json, const BotDescription& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "description", value.description);
}

} // namespace TgBot
