// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotName.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BotName& value) {
    Json::readRequiredField(json, "name", value.name);
}

void to_json(nlohmann::json& json, const BotName& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "name", value.name);
}

} // namespace TgBot
