// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BotSubscriptionUpdated.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BotSubscriptionUpdated& value) {
    Json::readRequiredField(json, "user", value.user);
    Json::readRequiredField(json, "invoice_payload", value.invoicePayload);
    Json::readRequiredField(json, "state", value.state);
}

void to_json(nlohmann::json& json, const BotSubscriptionUpdated& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "user", value.user);
    Json::writeRequiredField(json, "invoice_payload", value.invoicePayload);
    Json::writeRequiredField(json, "state", value.state);
}

} // namespace TgBot
