// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BusinessConnection.h"
#include "tgbot/Json.h"
#include "tgbot/types/BusinessBotRights.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BusinessConnection& value) {
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "user", value.user);
    Json::readRequiredField(json, "user_chat_id", value.userChatId);
    Json::readRequiredField(json, "date", value.date);
    Json::readOptionalField(json, "rights", value.rights);
    Json::readRequiredField(json, "is_enabled", value.isEnabled);
}

void to_json(nlohmann::json& json, const BusinessConnection& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "user", value.user);
    Json::writeRequiredField(json, "user_chat_id", value.userChatId);
    Json::writeRequiredField(json, "date", value.date);
    Json::writeOptionalField(json, "rights", value.rights);
    Json::writeRequiredField(json, "is_enabled", value.isEnabled);
}

} // namespace TgBot
