// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BusinessOpeningHours.h"
#include "tgbot/Json.h"
#include "tgbot/types/BusinessOpeningHoursInterval.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BusinessOpeningHours& value) {
    Json::readRequiredField(json, "time_zone_name", value.timeZoneName);
    Json::readRequiredField(json, "opening_hours", value.openingHours);
}

void to_json(nlohmann::json& json, const BusinessOpeningHours& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "time_zone_name", value.timeZoneName);
    Json::writeRequiredField(json, "opening_hours", value.openingHours);
}

} // namespace TgBot
