// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/BusinessIntro.h"
#include "tgbot/Json.h"
#include "tgbot/types/Sticker.h"

namespace TgBot {

void from_json(const nlohmann::json& json, BusinessIntro& value) {
    Json::readOptionalField(json, "title", value.title);
    Json::readOptionalField(json, "message", value.message);
    Json::readOptionalField(json, "sticker", value.sticker);
}

void to_json(nlohmann::json& json, const BusinessIntro& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "title", value.title);
    Json::writeOptionalField(json, "message", value.message);
    Json::writeOptionalField(json, "sticker", value.sticker);
}

} // namespace TgBot
