// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatBoostSourceGiftCode.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

const std::string ChatBoostSourceGiftCode::SOURCE = "gift_code";

void from_json(const nlohmann::json& json, ChatBoostSourceGiftCode& value) {
    Json::readRequiredField(json, "source", value.source);
    Json::readRequiredField(json, "user", value.user);
}

void to_json(nlohmann::json& json, const ChatBoostSourceGiftCode& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "source", value.source);
    Json::writeRequiredField(json, "user", value.user);
}

} // namespace TgBot
