// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatBoostAdded.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatBoostAdded& value) {
    Json::readRequiredField(json, "boost_count", value.boostCount);
}

void to_json(nlohmann::json& json, const ChatBoostAdded& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "boost_count", value.boostCount);
}

} // namespace TgBot
