// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatOwnerChanged.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatOwnerChanged& value) {
    Json::readRequiredField(json, "new_owner", value.newOwner);
}

void to_json(nlohmann::json& json, const ChatOwnerChanged& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "new_owner", value.newOwner);
}

} // namespace TgBot
