// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatPhoto.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatPhoto& value) {
    Json::readRequiredField(json, "small_file_id", value.smallFileId);
    Json::readRequiredField(json, "small_file_unique_id", value.smallFileUniqueId);
    Json::readRequiredField(json, "big_file_id", value.bigFileId);
    Json::readRequiredField(json, "big_file_unique_id", value.bigFileUniqueId);
}

void to_json(nlohmann::json& json, const ChatPhoto& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "small_file_id", value.smallFileId);
    Json::writeRequiredField(json, "small_file_unique_id", value.smallFileUniqueId);
    Json::writeRequiredField(json, "big_file_id", value.bigFileId);
    Json::writeRequiredField(json, "big_file_unique_id", value.bigFileUniqueId);
}

} // namespace TgBot
