// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatMemberLeft.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

const std::string ChatMemberLeft::STATUS = "left";

void from_json(const nlohmann::json& json, ChatMemberLeft& value) {
    Json::readRequiredField(json, "status", value.status);
    Json::readRequiredField(json, "user", value.user);
}

void to_json(nlohmann::json& json, const ChatMemberLeft& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "status", value.status);
    Json::writeRequiredField(json, "user", value.user);
}

} // namespace TgBot
