// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Chat.h"
#include "tgbot/Json.h"

#include <stdexcept>

namespace TgBot {

void from_json(const nlohmann::json& json, Chat::Type& value) {
    const auto text = json.get<std::string>();
    if (text == "private") {
        value = Chat::Type::Private;
        return;
    }
    if (text == "group") {
        value = Chat::Type::Group;
        return;
    }
    if (text == "supergroup") {
        value = Chat::Type::Supergroup;
        return;
    }
    if (text == "channel") {
        value = Chat::Type::Channel;
        return;
    }
    throw std::invalid_argument("Unknown Chat.Type value: " + text);
}

void to_json(nlohmann::json& json, const Chat::Type& value) {
    switch (value) {
    case Chat::Type::Private:
        json = "private";
        return;
    case Chat::Type::Group:
        json = "group";
        return;
    case Chat::Type::Supergroup:
        json = "supergroup";
        return;
    case Chat::Type::Channel:
        json = "channel";
        return;
    }
    throw std::invalid_argument("Unknown Chat.Type value");
}

void from_json(const nlohmann::json& json, Chat& value) {
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "type", value.type);
    Json::readOptionalField(json, "title", value.title);
    Json::readOptionalField(json, "username", value.username);
    Json::readOptionalField(json, "first_name", value.firstName);
    Json::readOptionalField(json, "last_name", value.lastName);
    Json::readOptionalField(json, "is_forum", value.isForum);
    Json::readOptionalField(json, "is_direct_messages", value.isDirectMessages);
}

void to_json(nlohmann::json& json, const Chat& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "type", value.type);
    Json::writeOptionalField(json, "title", value.title);
    Json::writeOptionalField(json, "username", value.username);
    Json::writeOptionalField(json, "first_name", value.firstName);
    Json::writeOptionalField(json, "last_name", value.lastName);
    Json::writeOptionalField(json, "is_forum", value.isForum);
    Json::writeOptionalField(json, "is_direct_messages", value.isDirectMessages);
}

} // namespace TgBot
