// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatBoostUpdated.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/ChatBoost.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatBoostUpdated& value) {
    Json::readRequiredField(json, "chat", value.chat);
    Json::readRequiredField(json, "boost", value.boost);
}

void to_json(nlohmann::json& json, const ChatBoostUpdated& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "chat", value.chat);
    Json::writeRequiredField(json, "boost", value.boost);
}

} // namespace TgBot
