// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatMemberUpdated.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/ChatInviteLink.h"
#include "tgbot/types/ChatMember.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatMemberUpdated& value) {
    Json::readRequiredField(json, "chat", value.chat);
    Json::readRequiredField(json, "from", value.from);
    Json::readRequiredField(json, "date", value.date);
    Json::readRequiredField(json, "old_chat_member", value.oldChatMember);
    Json::readRequiredField(json, "new_chat_member", value.newChatMember);
    Json::readOptionalField(json, "invite_link", value.inviteLink);
    Json::readOptionalField(json, "via_join_request", value.viaJoinRequest);
    Json::readOptionalField(json, "via_chat_folder_invite_link", value.viaChatFolderInviteLink);
}

void to_json(nlohmann::json& json, const ChatMemberUpdated& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "chat", value.chat);
    Json::writeRequiredField(json, "from", value.from);
    Json::writeRequiredField(json, "date", value.date);
    Json::writeRequiredField(json, "old_chat_member", value.oldChatMember);
    Json::writeRequiredField(json, "new_chat_member", value.newChatMember);
    Json::writeOptionalField(json, "invite_link", value.inviteLink);
    Json::writeOptionalField(json, "via_join_request", value.viaJoinRequest);
    Json::writeOptionalField(json, "via_chat_folder_invite_link", value.viaChatFolderInviteLink);
}

} // namespace TgBot
