// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatOwnerLeft.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatOwnerLeft& value) {
    Json::readOptionalField(json, "new_owner", value.newOwner);
}

void to_json(nlohmann::json& json, const ChatOwnerLeft& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "new_owner", value.newOwner);
}

} // namespace TgBot
