// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChatAdministratorRights.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChatAdministratorRights& value) {
    Json::readRequiredField(json, "is_anonymous", value.isAnonymous);
    Json::readRequiredField(json, "can_manage_chat", value.canManageChat);
    Json::readRequiredField(json, "can_delete_messages", value.canDeleteMessages);
    Json::readRequiredField(json, "can_manage_video_chats", value.canManageVideoChats);
    Json::readRequiredField(json, "can_restrict_members", value.canRestrictMembers);
    Json::readRequiredField(json, "can_promote_members", value.canPromoteMembers);
    Json::readRequiredField(json, "can_change_info", value.canChangeInfo);
    Json::readRequiredField(json, "can_invite_users", value.canInviteUsers);
    Json::readRequiredField(json, "can_post_stories", value.canPostStories);
    Json::readRequiredField(json, "can_edit_stories", value.canEditStories);
    Json::readRequiredField(json, "can_delete_stories", value.canDeleteStories);
    Json::readOptionalField(json, "can_post_messages", value.canPostMessages);
    Json::readOptionalField(json, "can_edit_messages", value.canEditMessages);
    Json::readOptionalField(json, "can_pin_messages", value.canPinMessages);
    Json::readOptionalField(json, "can_manage_topics", value.canManageTopics);
    Json::readOptionalField(json, "can_manage_direct_messages", value.canManageDirectMessages);
    Json::readOptionalField(json, "can_manage_tags", value.canManageTags);
}

void to_json(nlohmann::json& json, const ChatAdministratorRights& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "is_anonymous", value.isAnonymous);
    Json::writeRequiredField(json, "can_manage_chat", value.canManageChat);
    Json::writeRequiredField(json, "can_delete_messages", value.canDeleteMessages);
    Json::writeRequiredField(json, "can_manage_video_chats", value.canManageVideoChats);
    Json::writeRequiredField(json, "can_restrict_members", value.canRestrictMembers);
    Json::writeRequiredField(json, "can_promote_members", value.canPromoteMembers);
    Json::writeRequiredField(json, "can_change_info", value.canChangeInfo);
    Json::writeRequiredField(json, "can_invite_users", value.canInviteUsers);
    Json::writeRequiredField(json, "can_post_stories", value.canPostStories);
    Json::writeRequiredField(json, "can_edit_stories", value.canEditStories);
    Json::writeRequiredField(json, "can_delete_stories", value.canDeleteStories);
    Json::writeOptionalField(json, "can_post_messages", value.canPostMessages);
    Json::writeOptionalField(json, "can_edit_messages", value.canEditMessages);
    Json::writeOptionalField(json, "can_pin_messages", value.canPinMessages);
    Json::writeOptionalField(json, "can_manage_topics", value.canManageTopics);
    Json::writeOptionalField(json, "can_manage_direct_messages", value.canManageDirectMessages);
    Json::writeOptionalField(json, "can_manage_tags", value.canManageTags);
}

} // namespace TgBot
