// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ChecklistTasksAdded.h"
#include "tgbot/Json.h"
#include "tgbot/types/ChecklistTask.h"
#include "tgbot/types/Message.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ChecklistTasksAdded& value) {
    Json::readOptionalField(json, "checklist_message", value.checklistMessage);
    Json::readRequiredField(json, "tasks", value.tasks);
}

void to_json(nlohmann::json& json, const ChecklistTasksAdded& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "checklist_message", value.checklistMessage);
    Json::writeRequiredField(json, "tasks", value.tasks);
}

} // namespace TgBot
