// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Community.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Community& value) {
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "name", value.name);
}

void to_json(nlohmann::json& json, const Community& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "name", value.name);
}

} // namespace TgBot
