// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/CopyTextButton.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, CopyTextButton& value) {
    Json::readRequiredField(json, "text", value.text);
}

void to_json(nlohmann::json& json, const CopyTextButton& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "text", value.text);
}

} // namespace TgBot
