// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Dice.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Dice& value) {
    Json::readRequiredField(json, "emoji", value.emoji);
    Json::readRequiredField(json, "value", value.value);
}

void to_json(nlohmann::json& json, const Dice& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "emoji", value.emoji);
    Json::writeRequiredField(json, "value", value.value);
}

} // namespace TgBot
