// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/DirectMessagesTopic.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, DirectMessagesTopic& value) {
    Json::readRequiredField(json, "topic_id", value.topicId);
    Json::readOptionalField(json, "user", value.user);
}

void to_json(nlohmann::json& json, const DirectMessagesTopic& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "topic_id", value.topicId);
    Json::writeOptionalField(json, "user", value.user);
}

} // namespace TgBot
