// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ExternalReplyInfo.h"
#include "tgbot/Json.h"
#include "tgbot/types/Animation.h"
#include "tgbot/types/Audio.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/Checklist.h"
#include "tgbot/types/Contact.h"
#include "tgbot/types/Dice.h"
#include "tgbot/types/Document.h"
#include "tgbot/types/Game.h"
#include "tgbot/types/Giveaway.h"
#include "tgbot/types/GiveawayWinners.h"
#include "tgbot/types/Invoice.h"
#include "tgbot/types/LinkPreviewOptions.h"
#include "tgbot/types/LivePhoto.h"
#include "tgbot/types/Location.h"
#include "tgbot/types/MessageOrigin.h"
#include "tgbot/types/PaidMediaInfo.h"
#include "tgbot/types/PhotoSize.h"
#include "tgbot/types/Poll.h"
#include "tgbot/types/Sticker.h"
#include "tgbot/types/Story.h"
#include "tgbot/types/Venue.h"
#include "tgbot/types/Video.h"
#include "tgbot/types/VideoNote.h"
#include "tgbot/types/Voice.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ExternalReplyInfo& value) {
    Json::readRequiredField(json, "origin", value.origin);
    Json::readOptionalField(json, "chat", value.chat);
    Json::readOptionalField(json, "message_id", value.messageId);
    Json::readOptionalField(json, "link_preview_options", value.linkPreviewOptions);
    Json::readOptionalField(json, "animation", value.animation);
    Json::readOptionalField(json, "audio", value.audio);
    Json::readOptionalField(json, "document", value.document);
    Json::readOptionalField(json, "live_photo", value.livePhoto);
    Json::readOptionalField(json, "paid_media", value.paidMedia);
    Json::readOptionalField(json, "photo", value.photo);
    Json::readOptionalField(json, "sticker", value.sticker);
    Json::readOptionalField(json, "story", value.story);
    Json::readOptionalField(json, "video", value.video);
    Json::readOptionalField(json, "video_note", value.videoNote);
    Json::readOptionalField(json, "voice", value.voice);
    Json::readOptionalField(json, "has_media_spoiler", value.hasMediaSpoiler);
    Json::readOptionalField(json, "checklist", value.checklist);
    Json::readOptionalField(json, "contact", value.contact);
    Json::readOptionalField(json, "dice", value.dice);
    Json::readOptionalField(json, "game", value.game);
    Json::readOptionalField(json, "giveaway", value.giveaway);
    Json::readOptionalField(json, "giveaway_winners", value.giveawayWinners);
    Json::readOptionalField(json, "invoice", value.invoice);
    Json::readOptionalField(json, "location", value.location);
    Json::readOptionalField(json, "poll", value.poll);
    Json::readOptionalField(json, "venue", value.venue);
}

void to_json(nlohmann::json& json, const ExternalReplyInfo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "origin", value.origin);
    Json::writeOptionalField(json, "chat", value.chat);
    Json::writeOptionalField(json, "message_id", value.messageId);
    Json::writeOptionalField(json, "link_preview_options", value.linkPreviewOptions);
    Json::writeOptionalField(json, "animation", value.animation);
    Json::writeOptionalField(json, "audio", value.audio);
    Json::writeOptionalField(json, "document", value.document);
    Json::writeOptionalField(json, "live_photo", value.livePhoto);
    Json::writeOptionalField(json, "paid_media", value.paidMedia);
    Json::writeOptionalField(json, "photo", value.photo);
    Json::writeOptionalField(json, "sticker", value.sticker);
    Json::writeOptionalField(json, "story", value.story);
    Json::writeOptionalField(json, "video", value.video);
    Json::writeOptionalField(json, "video_note", value.videoNote);
    Json::writeOptionalField(json, "voice", value.voice);
    Json::writeOptionalField(json, "has_media_spoiler", value.hasMediaSpoiler);
    Json::writeOptionalField(json, "checklist", value.checklist);
    Json::writeOptionalField(json, "contact", value.contact);
    Json::writeOptionalField(json, "dice", value.dice);
    Json::writeOptionalField(json, "game", value.game);
    Json::writeOptionalField(json, "giveaway", value.giveaway);
    Json::writeOptionalField(json, "giveaway_winners", value.giveawayWinners);
    Json::writeOptionalField(json, "invoice", value.invoice);
    Json::writeOptionalField(json, "location", value.location);
    Json::writeOptionalField(json, "poll", value.poll);
    Json::writeOptionalField(json, "venue", value.venue);
}

} // namespace TgBot
