// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/File.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, File& value) {
    Json::readRequiredField(json, "file_id", value.fileId);
    Json::readRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::readOptionalField(json, "file_size", value.fileSize);
    Json::readOptionalField(json, "file_path", value.filePath);
}

void to_json(nlohmann::json& json, const File& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "file_id", value.fileId);
    Json::writeRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::writeOptionalField(json, "file_size", value.fileSize);
    Json::writeOptionalField(json, "file_path", value.filePath);
}

} // namespace TgBot
