// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ForceReply.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ForceReply& value) {
    Json::readRequiredField(json, "force_reply", value.forceReply);
    Json::readOptionalField(json, "input_field_placeholder", value.inputFieldPlaceholder);
    Json::readOptionalField(json, "selective", value.selective);
}

void to_json(nlohmann::json& json, const ForceReply& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "force_reply", value.forceReply);
    Json::writeOptionalField(json, "input_field_placeholder", value.inputFieldPlaceholder);
    Json::writeOptionalField(json, "selective", value.selective);
}

} // namespace TgBot
