// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ForumTopicEdited.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ForumTopicEdited& value) {
    Json::readOptionalField(json, "name", value.name);
    Json::readOptionalField(json, "icon_custom_emoji_id", value.iconCustomEmojiId);
}

void to_json(nlohmann::json& json, const ForumTopicEdited& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "name", value.name);
    Json::writeOptionalField(json, "icon_custom_emoji_id", value.iconCustomEmojiId);
}

} // namespace TgBot
