// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ForumTopicClosed.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ForumTopicClosed& value) {
}

void to_json(nlohmann::json& json, const ForumTopicClosed& value) {
    json = nlohmann::json::object();
}

} // namespace TgBot
