// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ForumTopicCreated.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ForumTopicCreated& value) {
    Json::readRequiredField(json, "name", value.name);
    Json::readRequiredField(json, "icon_color", value.iconColor);
    Json::readOptionalField(json, "icon_custom_emoji_id", value.iconCustomEmojiId);
    Json::readOptionalField(json, "is_name_implicit", value.isNameImplicit);
}

void to_json(nlohmann::json& json, const ForumTopicCreated& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "name", value.name);
    Json::writeRequiredField(json, "icon_color", value.iconColor);
    Json::writeOptionalField(json, "icon_custom_emoji_id", value.iconCustomEmojiId);
    Json::writeOptionalField(json, "is_name_implicit", value.isNameImplicit);
}

} // namespace TgBot
