// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Game.h"
#include "tgbot/Json.h"
#include "tgbot/types/Animation.h"
#include "tgbot/types/MessageEntity.h"
#include "tgbot/types/PhotoSize.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Game& value) {
    Json::readRequiredField(json, "title", value.title);
    Json::readRequiredField(json, "description", value.description);
    Json::readRequiredField(json, "photo", value.photo);
    Json::readOptionalField(json, "text", value.text);
    Json::readOptionalField(json, "text_entities", value.textEntities);
    Json::readOptionalField(json, "animation", value.animation);
}

void to_json(nlohmann::json& json, const Game& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "title", value.title);
    Json::writeRequiredField(json, "description", value.description);
    Json::writeRequiredField(json, "photo", value.photo);
    Json::writeOptionalField(json, "text", value.text);
    Json::writeOptionalField(json, "text_entities", value.textEntities);
    Json::writeOptionalField(json, "animation", value.animation);
}

} // namespace TgBot
