// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/GiftInfo.h"
#include "tgbot/Json.h"
#include "tgbot/types/Gift.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

void from_json(const nlohmann::json& json, GiftInfo& value) {
    Json::readRequiredField(json, "gift", value.gift);
    Json::readOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::readOptionalField(json, "convert_star_count", value.convertStarCount);
    Json::readOptionalField(json, "prepaid_upgrade_star_count", value.prepaidUpgradeStarCount);
    Json::readOptionalField(json, "is_upgrade_separate", value.isUpgradeSeparate);
    Json::readOptionalField(json, "can_be_upgraded", value.canBeUpgraded);
    Json::readOptionalField(json, "text", value.text);
    Json::readOptionalField(json, "entities", value.entities);
    Json::readOptionalField(json, "is_private", value.isPrivate);
    Json::readOptionalField(json, "unique_gift_number", value.uniqueGiftNumber);
}

void to_json(nlohmann::json& json, const GiftInfo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "gift", value.gift);
    Json::writeOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::writeOptionalField(json, "convert_star_count", value.convertStarCount);
    Json::writeOptionalField(json, "prepaid_upgrade_star_count", value.prepaidUpgradeStarCount);
    Json::writeOptionalField(json, "is_upgrade_separate", value.isUpgradeSeparate);
    Json::writeOptionalField(json, "can_be_upgraded", value.canBeUpgraded);
    Json::writeOptionalField(json, "text", value.text);
    Json::writeOptionalField(json, "entities", value.entities);
    Json::writeOptionalField(json, "is_private", value.isPrivate);
    Json::writeOptionalField(json, "unique_gift_number", value.uniqueGiftNumber);
}

} // namespace TgBot
