// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Gifts.h"
#include "tgbot/Json.h"
#include "tgbot/types/Gift.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Gifts& value) {
    Json::readRequiredField(json, "gifts", value.gifts);
}

void to_json(nlohmann::json& json, const Gifts& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "gifts", value.gifts);
}

} // namespace TgBot
