// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/GiveawayCompleted.h"
#include "tgbot/Json.h"
#include "tgbot/types/Message.h"

namespace TgBot {

void from_json(const nlohmann::json& json, GiveawayCompleted& value) {
    Json::readRequiredField(json, "winner_count", value.winnerCount);
    Json::readOptionalField(json, "unclaimed_prize_count", value.unclaimedPrizeCount);
    Json::readOptionalField(json, "giveaway_message", value.giveawayMessage);
    Json::readOptionalField(json, "is_star_giveaway", value.isStarGiveaway);
}

void to_json(nlohmann::json& json, const GiveawayCompleted& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "winner_count", value.winnerCount);
    Json::writeOptionalField(json, "unclaimed_prize_count", value.unclaimedPrizeCount);
    Json::writeOptionalField(json, "giveaway_message", value.giveawayMessage);
    Json::writeOptionalField(json, "is_star_giveaway", value.isStarGiveaway);
}

} // namespace TgBot
