// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/GiveawayCreated.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, GiveawayCreated& value) {
    Json::readOptionalField(json, "prize_star_count", value.prizeStarCount);
}

void to_json(nlohmann::json& json, const GiveawayCreated& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "prize_star_count", value.prizeStarCount);
}

} // namespace TgBot
