// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InaccessibleMessage.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InaccessibleMessage& value) {
    Json::readRequiredField(json, "chat", value.chat);
    Json::readRequiredField(json, "message_id", value.messageId);
    Json::readRequiredField(json, "date", value.date);
}

void to_json(nlohmann::json& json, const InaccessibleMessage& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "chat", value.chat);
    Json::writeRequiredField(json, "message_id", value.messageId);
    Json::writeRequiredField(json, "date", value.date);
}

} // namespace TgBot
