// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InlineQueryResultArticle.h"
#include "tgbot/Json.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/InputMessageContent.h"

namespace TgBot {

const std::string InlineQueryResultArticle::TYPE = "article";

void from_json(const nlohmann::json& json, InlineQueryResultArticle& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "title", value.title);
    Json::readRequiredField(json, "input_message_content", value.inputMessageContent);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
    Json::readOptionalField(json, "url", value.url);
    Json::readOptionalField(json, "description", value.description);
    Json::readOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::readOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::readOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

void to_json(nlohmann::json& json, const InlineQueryResultArticle& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "title", value.title);
    Json::writeRequiredField(json, "input_message_content", value.inputMessageContent);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
    Json::writeOptionalField(json, "url", value.url);
    Json::writeOptionalField(json, "description", value.description);
    Json::writeOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::writeOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::writeOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

} // namespace TgBot
