// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InlineQueryResultGif.h"
#include "tgbot/Json.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/InputMessageContent.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

const std::string InlineQueryResultGif::TYPE = "gif";

void from_json(const nlohmann::json& json, InlineQueryResultGif& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "gif_url", value.gifUrl);
    Json::readOptionalField(json, "gif_width", value.gifWidth);
    Json::readOptionalField(json, "gif_height", value.gifHeight);
    Json::readOptionalField(json, "gif_duration", value.gifDuration);
    Json::readRequiredField(json, "thumbnail_url", value.thumbnailUrl);
    Json::readOptionalField(json, "thumbnail_mime_type", value.thumbnailMimeType);
    Json::readOptionalField(json, "title", value.title);
    Json::readOptionalField(json, "caption", value.caption);
    Json::readOptionalField(json, "parse_mode", value.parseMode);
    Json::readOptionalField(json, "caption_entities", value.captionEntities);
    Json::readOptionalField(json, "show_caption_above_media", value.showCaptionAboveMedia);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
    Json::readOptionalField(json, "input_message_content", value.inputMessageContent);
}

void to_json(nlohmann::json& json, const InlineQueryResultGif& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "gif_url", value.gifUrl);
    Json::writeOptionalField(json, "gif_width", value.gifWidth);
    Json::writeOptionalField(json, "gif_height", value.gifHeight);
    Json::writeOptionalField(json, "gif_duration", value.gifDuration);
    Json::writeRequiredField(json, "thumbnail_url", value.thumbnailUrl);
    Json::writeOptionalField(json, "thumbnail_mime_type", value.thumbnailMimeType);
    Json::writeOptionalField(json, "title", value.title);
    Json::writeOptionalField(json, "caption", value.caption);
    Json::writeOptionalField(json, "parse_mode", value.parseMode);
    Json::writeOptionalField(json, "caption_entities", value.captionEntities);
    Json::writeOptionalField(json, "show_caption_above_media", value.showCaptionAboveMedia);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
    Json::writeOptionalField(json, "input_message_content", value.inputMessageContent);
}

} // namespace TgBot
