// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InlineQueryResultLocation.h"
#include "tgbot/Json.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/InputMessageContent.h"

namespace TgBot {

const std::string InlineQueryResultLocation::TYPE = "location";

void from_json(const nlohmann::json& json, InlineQueryResultLocation& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "latitude", value.latitude);
    Json::readRequiredField(json, "longitude", value.longitude);
    Json::readRequiredField(json, "title", value.title);
    Json::readOptionalField(json, "horizontal_accuracy", value.horizontalAccuracy);
    Json::readOptionalField(json, "live_period", value.livePeriod);
    Json::readOptionalField(json, "heading", value.heading);
    Json::readOptionalField(json, "proximity_alert_radius", value.proximityAlertRadius);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
    Json::readOptionalField(json, "input_message_content", value.inputMessageContent);
    Json::readOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::readOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::readOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

void to_json(nlohmann::json& json, const InlineQueryResultLocation& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "latitude", value.latitude);
    Json::writeRequiredField(json, "longitude", value.longitude);
    Json::writeRequiredField(json, "title", value.title);
    Json::writeOptionalField(json, "horizontal_accuracy", value.horizontalAccuracy);
    Json::writeOptionalField(json, "live_period", value.livePeriod);
    Json::writeOptionalField(json, "heading", value.heading);
    Json::writeOptionalField(json, "proximity_alert_radius", value.proximityAlertRadius);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
    Json::writeOptionalField(json, "input_message_content", value.inputMessageContent);
    Json::writeOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::writeOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::writeOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

} // namespace TgBot
