// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InlineQueryResultCachedAudio.h"
#include "tgbot/Json.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/InputMessageContent.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

const std::string InlineQueryResultCachedAudio::TYPE = "audio";

void from_json(const nlohmann::json& json, InlineQueryResultCachedAudio& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "audio_file_id", value.audioFileId);
    Json::readOptionalField(json, "caption", value.caption);
    Json::readOptionalField(json, "parse_mode", value.parseMode);
    Json::readOptionalField(json, "caption_entities", value.captionEntities);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
    Json::readOptionalField(json, "input_message_content", value.inputMessageContent);
}

void to_json(nlohmann::json& json, const InlineQueryResultCachedAudio& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "audio_file_id", value.audioFileId);
    Json::writeOptionalField(json, "caption", value.caption);
    Json::writeOptionalField(json, "parse_mode", value.parseMode);
    Json::writeOptionalField(json, "caption_entities", value.captionEntities);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
    Json::writeOptionalField(json, "input_message_content", value.inputMessageContent);
}

} // namespace TgBot
