// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InlineQueryResultContact.h"
#include "tgbot/Json.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/InputMessageContent.h"

namespace TgBot {

const std::string InlineQueryResultContact::TYPE = "contact";

void from_json(const nlohmann::json& json, InlineQueryResultContact& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "phone_number", value.phoneNumber);
    Json::readRequiredField(json, "first_name", value.firstName);
    Json::readOptionalField(json, "last_name", value.lastName);
    Json::readOptionalField(json, "vcard", value.vcard);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
    Json::readOptionalField(json, "input_message_content", value.inputMessageContent);
    Json::readOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::readOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::readOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

void to_json(nlohmann::json& json, const InlineQueryResultContact& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "phone_number", value.phoneNumber);
    Json::writeRequiredField(json, "first_name", value.firstName);
    Json::writeOptionalField(json, "last_name", value.lastName);
    Json::writeOptionalField(json, "vcard", value.vcard);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
    Json::writeOptionalField(json, "input_message_content", value.inputMessageContent);
    Json::writeOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::writeOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::writeOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

} // namespace TgBot
