// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InlineQueryResultDocument.h"
#include "tgbot/Json.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/InputMessageContent.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

const std::string InlineQueryResultDocument::TYPE = "document";

void from_json(const nlohmann::json& json, InlineQueryResultDocument& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "title", value.title);
    Json::readOptionalField(json, "caption", value.caption);
    Json::readOptionalField(json, "parse_mode", value.parseMode);
    Json::readOptionalField(json, "caption_entities", value.captionEntities);
    Json::readRequiredField(json, "document_url", value.documentUrl);
    Json::readRequiredField(json, "mime_type", value.mimeType);
    Json::readOptionalField(json, "description", value.description);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
    Json::readOptionalField(json, "input_message_content", value.inputMessageContent);
    Json::readOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::readOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::readOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

void to_json(nlohmann::json& json, const InlineQueryResultDocument& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "title", value.title);
    Json::writeOptionalField(json, "caption", value.caption);
    Json::writeOptionalField(json, "parse_mode", value.parseMode);
    Json::writeOptionalField(json, "caption_entities", value.captionEntities);
    Json::writeRequiredField(json, "document_url", value.documentUrl);
    Json::writeRequiredField(json, "mime_type", value.mimeType);
    Json::writeOptionalField(json, "description", value.description);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
    Json::writeOptionalField(json, "input_message_content", value.inputMessageContent);
    Json::writeOptionalField(json, "thumbnail_url", value.thumbnailUrl);
    Json::writeOptionalField(json, "thumbnail_width", value.thumbnailWidth);
    Json::writeOptionalField(json, "thumbnail_height", value.thumbnailHeight);
}

} // namespace TgBot
