// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichMessageMedia.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputMediaAnimation.h"
#include "tgbot/types/InputMediaAudio.h"
#include "tgbot/types/InputMediaPhoto.h"
#include "tgbot/types/InputMediaVideo.h"
#include "tgbot/types/InputMediaVoiceNote.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputRichMessageMedia& value) {
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "media", value.media);
}

void to_json(nlohmann::json& json, const InputRichMessageMedia& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "media", value.media);
}

} // namespace TgBot
