// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputPaidMediaLivePhoto.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string InputPaidMediaLivePhoto::TYPE = "live_photo";

void from_json(const nlohmann::json& json, InputPaidMediaLivePhoto& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "media", value.media);
    Json::readRequiredField(json, "photo", value.photo);
}

void to_json(nlohmann::json& json, const InputPaidMediaLivePhoto& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "media", value.media);
    Json::writeRequiredField(json, "photo", value.photo);
}

} // namespace TgBot
