// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputStoryContentVideo.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string InputStoryContentVideo::TYPE = "video";

void from_json(const nlohmann::json& json, InputStoryContentVideo& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "video", value.video);
    Json::readOptionalField(json, "duration", value.duration);
    Json::readOptionalField(json, "cover_frame_timestamp", value.coverFrameTimestamp);
    Json::readOptionalField(json, "is_animation", value.isAnimation);
}

void to_json(nlohmann::json& json, const InputStoryContentVideo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "video", value.video);
    Json::writeOptionalField(json, "duration", value.duration);
    Json::writeOptionalField(json, "cover_frame_timestamp", value.coverFrameTimestamp);
    Json::writeOptionalField(json, "is_animation", value.isAnimation);
}

} // namespace TgBot
