// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichMessage.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputRichBlock.h"
#include "tgbot/types/InputRichMessageMedia.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputRichMessage& value) {
    Json::readOptionalField(json, "blocks", value.blocks);
    Json::readOptionalField(json, "html", value.html);
    Json::readOptionalField(json, "markdown", value.markdown);
    Json::readOptionalField(json, "media", value.media);
    Json::readOptionalField(json, "is_rtl", value.isRtl);
    Json::readOptionalField(json, "skip_entity_detection", value.skipEntityDetection);
}

void to_json(nlohmann::json& json, const InputRichMessage& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "blocks", value.blocks);
    Json::writeOptionalField(json, "html", value.html);
    Json::writeOptionalField(json, "markdown", value.markdown);
    Json::writeOptionalField(json, "media", value.media);
    Json::writeOptionalField(json, "is_rtl", value.isRtl);
    Json::writeOptionalField(json, "skip_entity_detection", value.skipEntityDetection);
}

} // namespace TgBot
