// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputMediaVoiceNote.h"
#include "tgbot/Json.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

const std::string InputMediaVoiceNote::TYPE = "voice_note";

void from_json(const nlohmann::json& json, InputMediaVoiceNote& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "media", value.media);
    Json::readOptionalField(json, "caption", value.caption);
    Json::readOptionalField(json, "parse_mode", value.parseMode);
    Json::readOptionalField(json, "caption_entities", value.captionEntities);
    Json::readOptionalField(json, "duration", value.duration);
}

void to_json(nlohmann::json& json, const InputMediaVoiceNote& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "media", value.media);
    Json::writeOptionalField(json, "caption", value.caption);
    Json::writeOptionalField(json, "parse_mode", value.parseMode);
    Json::writeOptionalField(json, "caption_entities", value.captionEntities);
    Json::writeOptionalField(json, "duration", value.duration);
}

} // namespace TgBot
