// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockSlideshow.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputRichBlock.h"
#include "tgbot/types/RichBlockCaption.h"

namespace TgBot {

const std::string InputRichBlockSlideshow::TYPE = "slideshow";

void from_json(const nlohmann::json& json, InputRichBlockSlideshow& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "blocks", value.blocks);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const InputRichBlockSlideshow& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "blocks", value.blocks);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
