// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputInvoiceMessageContent.h"
#include "tgbot/Json.h"
#include "tgbot/types/LabeledPrice.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputInvoiceMessageContent& value) {
    Json::readRequiredField(json, "title", value.title);
    Json::readRequiredField(json, "description", value.description);
    Json::readRequiredField(json, "payload", value.payload);
    Json::readOptionalField(json, "provider_token", value.providerToken);
    Json::readRequiredField(json, "currency", value.currency);
    Json::readRequiredField(json, "prices", value.prices);
    Json::readOptionalField(json, "max_tip_amount", value.maxTipAmount);
    Json::readOptionalField(json, "suggested_tip_amounts", value.suggestedTipAmounts);
    Json::readOptionalField(json, "provider_data", value.providerData);
    Json::readOptionalField(json, "photo_url", value.photoUrl);
    Json::readOptionalField(json, "photo_size", value.photoSize);
    Json::readOptionalField(json, "photo_width", value.photoWidth);
    Json::readOptionalField(json, "photo_height", value.photoHeight);
    Json::readOptionalField(json, "need_name", value.needName);
    Json::readOptionalField(json, "need_phone_number", value.needPhoneNumber);
    Json::readOptionalField(json, "need_email", value.needEmail);
    Json::readOptionalField(json, "need_shipping_address", value.needShippingAddress);
    Json::readOptionalField(json, "send_phone_number_to_provider", value.sendPhoneNumberToProvider);
    Json::readOptionalField(json, "send_email_to_provider", value.sendEmailToProvider);
    Json::readOptionalField(json, "is_flexible", value.isFlexible);
}

void to_json(nlohmann::json& json, const InputInvoiceMessageContent& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "title", value.title);
    Json::writeRequiredField(json, "description", value.description);
    Json::writeRequiredField(json, "payload", value.payload);
    Json::writeOptionalField(json, "provider_token", value.providerToken);
    Json::writeRequiredField(json, "currency", value.currency);
    Json::writeRequiredField(json, "prices", value.prices);
    Json::writeOptionalField(json, "max_tip_amount", value.maxTipAmount);
    Json::writeOptionalField(json, "suggested_tip_amounts", value.suggestedTipAmounts);
    Json::writeOptionalField(json, "provider_data", value.providerData);
    Json::writeOptionalField(json, "photo_url", value.photoUrl);
    Json::writeOptionalField(json, "photo_size", value.photoSize);
    Json::writeOptionalField(json, "photo_width", value.photoWidth);
    Json::writeOptionalField(json, "photo_height", value.photoHeight);
    Json::writeOptionalField(json, "need_name", value.needName);
    Json::writeOptionalField(json, "need_phone_number", value.needPhoneNumber);
    Json::writeOptionalField(json, "need_email", value.needEmail);
    Json::writeOptionalField(json, "need_shipping_address", value.needShippingAddress);
    Json::writeOptionalField(json, "send_phone_number_to_provider", value.sendPhoneNumberToProvider);
    Json::writeOptionalField(json, "send_email_to_provider", value.sendEmailToProvider);
    Json::writeOptionalField(json, "is_flexible", value.isFlexible);
}

} // namespace TgBot
