// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockVoiceNote.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputMediaVoiceNote.h"
#include "tgbot/types/RichBlockCaption.h"

namespace TgBot {

const std::string InputRichBlockVoiceNote::TYPE = "voice_note";

void from_json(const nlohmann::json& json, InputRichBlockVoiceNote& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "voice_note", value.voiceNote);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const InputRichBlockVoiceNote& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "voice_note", value.voiceNote);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
