// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockSectionHeading.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string InputRichBlockSectionHeading::TYPE = "heading";

void from_json(const nlohmann::json& json, InputRichBlockSectionHeading& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
    Json::readRequiredField(json, "size", value.size);
}

void to_json(nlohmann::json& json, const InputRichBlockSectionHeading& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeRequiredField(json, "size", value.size);
}

} // namespace TgBot
