// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputMediaSticker.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string InputMediaSticker::TYPE = "sticker";

void from_json(const nlohmann::json& json, InputMediaSticker& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "media", value.media);
    Json::readOptionalField(json, "emoji", value.emoji);
}

void to_json(nlohmann::json& json, const InputMediaSticker& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "media", value.media);
    Json::writeOptionalField(json, "emoji", value.emoji);
}

} // namespace TgBot
