// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputProfilePhotoStatic.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string InputProfilePhotoStatic::TYPE = "static";

void from_json(const nlohmann::json& json, InputProfilePhotoStatic& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "photo", value.photo);
}

void to_json(nlohmann::json& json, const InputProfilePhotoStatic& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "photo", value.photo);
}

} // namespace TgBot
