// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputPaidMediaVideo.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string InputPaidMediaVideo::TYPE = "video";

void from_json(const nlohmann::json& json, InputPaidMediaVideo& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "media", value.media);
    Json::readOptionalField(json, "thumbnail", value.thumbnail);
    Json::readOptionalField(json, "cover", value.cover);
    Json::readOptionalField(json, "start_timestamp", value.startTimestamp);
    Json::readOptionalField(json, "width", value.width);
    Json::readOptionalField(json, "height", value.height);
    Json::readOptionalField(json, "duration", value.duration);
    Json::readOptionalField(json, "supports_streaming", value.supportsStreaming);
}

void to_json(nlohmann::json& json, const InputPaidMediaVideo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "media", value.media);
    Json::writeOptionalField(json, "thumbnail", value.thumbnail);
    Json::writeOptionalField(json, "cover", value.cover);
    Json::writeOptionalField(json, "start_timestamp", value.startTimestamp);
    Json::writeOptionalField(json, "width", value.width);
    Json::writeOptionalField(json, "height", value.height);
    Json::writeOptionalField(json, "duration", value.duration);
    Json::writeOptionalField(json, "supports_streaming", value.supportsStreaming);
}

} // namespace TgBot
