// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputTextMessageContent.h"
#include "tgbot/Json.h"
#include "tgbot/types/LinkPreviewOptions.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputTextMessageContent& value) {
    Json::readRequiredField(json, "message_text", value.messageText);
    Json::readOptionalField(json, "parse_mode", value.parseMode);
    Json::readOptionalField(json, "entities", value.entities);
    Json::readOptionalField(json, "link_preview_options", value.linkPreviewOptions);
}

void to_json(nlohmann::json& json, const InputTextMessageContent& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "message_text", value.messageText);
    Json::writeOptionalField(json, "parse_mode", value.parseMode);
    Json::writeOptionalField(json, "entities", value.entities);
    Json::writeOptionalField(json, "link_preview_options", value.linkPreviewOptions);
}

} // namespace TgBot
