// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichMessageContent.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputRichMessage.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputRichMessageContent& value) {
    Json::readRequiredField(json, "rich_message", value.richMessage);
}

void to_json(nlohmann::json& json, const InputRichMessageContent& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "rich_message", value.richMessage);
}

} // namespace TgBot
