// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputPollOptionMedia.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputMediaAnimation.h"
#include "tgbot/types/InputMediaLink.h"
#include "tgbot/types/InputMediaLivePhoto.h"
#include "tgbot/types/InputMediaLocation.h"
#include "tgbot/types/InputMediaPhoto.h"
#include "tgbot/types/InputMediaSticker.h"
#include "tgbot/types/InputMediaVenue.h"
#include "tgbot/types/InputMediaVideo.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputPollOptionMedia& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const InputPollOptionMedia& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
