// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockThinking.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string InputRichBlockThinking::TYPE = "thinking";

void from_json(const nlohmann::json& json, InputRichBlockThinking& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
}

void to_json(nlohmann::json& json, const InputRichBlockThinking& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
}

} // namespace TgBot
