// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputMediaLocation.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string InputMediaLocation::TYPE = "location";

void from_json(const nlohmann::json& json, InputMediaLocation& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "latitude", value.latitude);
    Json::readRequiredField(json, "longitude", value.longitude);
    Json::readOptionalField(json, "horizontal_accuracy", value.horizontalAccuracy);
}

void to_json(nlohmann::json& json, const InputMediaLocation& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "latitude", value.latitude);
    Json::writeRequiredField(json, "longitude", value.longitude);
    Json::writeOptionalField(json, "horizontal_accuracy", value.horizontalAccuracy);
}

} // namespace TgBot
