// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockBlockQuotation.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputRichBlock.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string InputRichBlockBlockQuotation::TYPE = "blockquote";

void from_json(const nlohmann::json& json, InputRichBlockBlockQuotation& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "blocks", value.blocks);
    Json::readOptionalField(json, "credit", value.credit);
}

void to_json(nlohmann::json& json, const InputRichBlockBlockQuotation& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "blocks", value.blocks);
    Json::writeOptionalField(json, "credit", value.credit);
}

} // namespace TgBot
