// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputVenueMessageContent.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputVenueMessageContent& value) {
    Json::readRequiredField(json, "latitude", value.latitude);
    Json::readRequiredField(json, "longitude", value.longitude);
    Json::readRequiredField(json, "title", value.title);
    Json::readRequiredField(json, "address", value.address);
    Json::readOptionalField(json, "foursquare_id", value.foursquareId);
    Json::readOptionalField(json, "foursquare_type", value.foursquareType);
    Json::readOptionalField(json, "google_place_id", value.googlePlaceId);
    Json::readOptionalField(json, "google_place_type", value.googlePlaceType);
}

void to_json(nlohmann::json& json, const InputVenueMessageContent& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "latitude", value.latitude);
    Json::writeRequiredField(json, "longitude", value.longitude);
    Json::writeRequiredField(json, "title", value.title);
    Json::writeRequiredField(json, "address", value.address);
    Json::writeOptionalField(json, "foursquare_id", value.foursquareId);
    Json::writeOptionalField(json, "foursquare_type", value.foursquareType);
    Json::writeOptionalField(json, "google_place_id", value.googlePlaceId);
    Json::writeOptionalField(json, "google_place_type", value.googlePlaceType);
}

} // namespace TgBot
