// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockDetails.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputRichBlock.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string InputRichBlockDetails::TYPE = "details";

void from_json(const nlohmann::json& json, InputRichBlockDetails& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "summary", value.summary);
    Json::readRequiredField(json, "blocks", value.blocks);
    Json::readOptionalField(json, "is_open", value.isOpen);
}

void to_json(nlohmann::json& json, const InputRichBlockDetails& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "summary", value.summary);
    Json::writeRequiredField(json, "blocks", value.blocks);
    Json::writeOptionalField(json, "is_open", value.isOpen);
}

} // namespace TgBot
