// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlockVideo.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputMediaVideo.h"
#include "tgbot/types/RichBlockCaption.h"

namespace TgBot {

const std::string InputRichBlockVideo::TYPE = "video";

void from_json(const nlohmann::json& json, InputRichBlockVideo& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "video", value.video);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const InputRichBlockVideo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "video", value.video);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
