// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputMediaPhoto.h"
#include "tgbot/Json.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

const std::string InputMediaPhoto::TYPE = "photo";

void from_json(const nlohmann::json& json, InputMediaPhoto& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "media", value.media);
    Json::readOptionalField(json, "caption", value.caption);
    Json::readOptionalField(json, "parse_mode", value.parseMode);
    Json::readOptionalField(json, "caption_entities", value.captionEntities);
    Json::readOptionalField(json, "show_caption_above_media", value.showCaptionAboveMedia);
    Json::readOptionalField(json, "has_spoiler", value.hasSpoiler);
}

void to_json(nlohmann::json& json, const InputMediaPhoto& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "media", value.media);
    Json::writeOptionalField(json, "caption", value.caption);
    Json::writeOptionalField(json, "parse_mode", value.parseMode);
    Json::writeOptionalField(json, "caption_entities", value.captionEntities);
    Json::writeOptionalField(json, "show_caption_above_media", value.showCaptionAboveMedia);
    Json::writeOptionalField(json, "has_spoiler", value.hasSpoiler);
}

} // namespace TgBot
