// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputRichBlock.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputRichBlockAnchor.h"
#include "tgbot/types/InputRichBlockAnimation.h"
#include "tgbot/types/InputRichBlockAudio.h"
#include "tgbot/types/InputRichBlockBlockQuotation.h"
#include "tgbot/types/InputRichBlockCollage.h"
#include "tgbot/types/InputRichBlockDetails.h"
#include "tgbot/types/InputRichBlockDivider.h"
#include "tgbot/types/InputRichBlockFooter.h"
#include "tgbot/types/InputRichBlockList.h"
#include "tgbot/types/InputRichBlockMap.h"
#include "tgbot/types/InputRichBlockMathematicalExpression.h"
#include "tgbot/types/InputRichBlockParagraph.h"
#include "tgbot/types/InputRichBlockPhoto.h"
#include "tgbot/types/InputRichBlockPreformatted.h"
#include "tgbot/types/InputRichBlockPullQuotation.h"
#include "tgbot/types/InputRichBlockSectionHeading.h"
#include "tgbot/types/InputRichBlockSlideshow.h"
#include "tgbot/types/InputRichBlockTable.h"
#include "tgbot/types/InputRichBlockThinking.h"
#include "tgbot/types/InputRichBlockVideo.h"
#include "tgbot/types/InputRichBlockVoiceNote.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputRichBlock& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const InputRichBlock& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
