// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/InputProfilePhoto.h"
#include "tgbot/Json.h"
#include "tgbot/types/InputProfilePhotoAnimated.h"
#include "tgbot/types/InputProfilePhotoStatic.h"

namespace TgBot {

void from_json(const nlohmann::json& json, InputProfilePhoto& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const InputProfilePhoto& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
