// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Invoice.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Invoice& value) {
    Json::readRequiredField(json, "title", value.title);
    Json::readRequiredField(json, "description", value.description);
    Json::readRequiredField(json, "start_parameter", value.startParameter);
    Json::readRequiredField(json, "currency", value.currency);
    Json::readRequiredField(json, "total_amount", value.totalAmount);
}

void to_json(nlohmann::json& json, const Invoice& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "title", value.title);
    Json::writeRequiredField(json, "description", value.description);
    Json::writeRequiredField(json, "start_parameter", value.startParameter);
    Json::writeRequiredField(json, "currency", value.currency);
    Json::writeRequiredField(json, "total_amount", value.totalAmount);
}

} // namespace TgBot
