// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/KeyboardButtonRequestUsers.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, KeyboardButtonRequestUsers& value) {
    Json::readRequiredField(json, "request_id", value.requestId);
    Json::readOptionalField(json, "user_is_bot", value.userIsBot);
    Json::readOptionalField(json, "user_is_premium", value.userIsPremium);
    Json::readOptionalField(json, "max_quantity", value.maxQuantity);
    Json::readOptionalField(json, "request_name", value.requestName);
    Json::readOptionalField(json, "request_username", value.requestUsername);
    Json::readOptionalField(json, "request_photo", value.requestPhoto);
}

void to_json(nlohmann::json& json, const KeyboardButtonRequestUsers& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "request_id", value.requestId);
    Json::writeOptionalField(json, "user_is_bot", value.userIsBot);
    Json::writeOptionalField(json, "user_is_premium", value.userIsPremium);
    Json::writeOptionalField(json, "max_quantity", value.maxQuantity);
    Json::writeOptionalField(json, "request_name", value.requestName);
    Json::writeOptionalField(json, "request_username", value.requestUsername);
    Json::writeOptionalField(json, "request_photo", value.requestPhoto);
}

} // namespace TgBot
