// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/KeyboardButton.h"
#include "tgbot/Json.h"
#include "tgbot/types/KeyboardButtonPollType.h"
#include "tgbot/types/KeyboardButtonRequestChat.h"
#include "tgbot/types/KeyboardButtonRequestManagedBot.h"
#include "tgbot/types/KeyboardButtonRequestUsers.h"
#include "tgbot/types/WebAppInfo.h"

namespace TgBot {

void from_json(const nlohmann::json& json, KeyboardButton& value) {
    Json::readRequiredField(json, "text", value.text);
    Json::readOptionalField(json, "icon_custom_emoji_id", value.iconCustomEmojiId);
    Json::readOptionalField(json, "style", value.style);
    Json::readOptionalField(json, "request_users", value.requestUsers);
    Json::readOptionalField(json, "request_chat", value.requestChat);
    Json::readOptionalField(json, "request_managed_bot", value.requestManagedBot);
    Json::readOptionalField(json, "request_contact", value.requestContact);
    Json::readOptionalField(json, "request_location", value.requestLocation);
    Json::readOptionalField(json, "request_poll", value.requestPoll);
    Json::readOptionalField(json, "web_app", value.webApp);
}

void to_json(nlohmann::json& json, const KeyboardButton& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "text", value.text);
    Json::writeOptionalField(json, "icon_custom_emoji_id", value.iconCustomEmojiId);
    Json::writeOptionalField(json, "style", value.style);
    Json::writeOptionalField(json, "request_users", value.requestUsers);
    Json::writeOptionalField(json, "request_chat", value.requestChat);
    Json::writeOptionalField(json, "request_managed_bot", value.requestManagedBot);
    Json::writeOptionalField(json, "request_contact", value.requestContact);
    Json::writeOptionalField(json, "request_location", value.requestLocation);
    Json::writeOptionalField(json, "request_poll", value.requestPoll);
    Json::writeOptionalField(json, "web_app", value.webApp);
}

} // namespace TgBot
