// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/KeyboardButtonPollType.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, KeyboardButtonPollType& value) {
    Json::readOptionalField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const KeyboardButtonPollType& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "type", value.type);
}

} // namespace TgBot
