// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/LinkPreviewOptions.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, LinkPreviewOptions& value) {
    Json::readOptionalField(json, "is_disabled", value.isDisabled);
    Json::readOptionalField(json, "url", value.url);
    Json::readOptionalField(json, "prefer_small_media", value.preferSmallMedia);
    Json::readOptionalField(json, "prefer_large_media", value.preferLargeMedia);
    Json::readOptionalField(json, "show_above_text", value.showAboveText);
}

void to_json(nlohmann::json& json, const LinkPreviewOptions& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "is_disabled", value.isDisabled);
    Json::writeOptionalField(json, "url", value.url);
    Json::writeOptionalField(json, "prefer_small_media", value.preferSmallMedia);
    Json::writeOptionalField(json, "prefer_large_media", value.preferLargeMedia);
    Json::writeOptionalField(json, "show_above_text", value.showAboveText);
}

} // namespace TgBot
