// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/LocationAddress.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, LocationAddress& value) {
    Json::readRequiredField(json, "country_code", value.countryCode);
    Json::readOptionalField(json, "state", value.state);
    Json::readOptionalField(json, "city", value.city);
    Json::readOptionalField(json, "street", value.street);
}

void to_json(nlohmann::json& json, const LocationAddress& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "country_code", value.countryCode);
    Json::writeOptionalField(json, "state", value.state);
    Json::writeOptionalField(json, "city", value.city);
    Json::writeOptionalField(json, "street", value.street);
}

} // namespace TgBot
