// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Location.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Location& value) {
    Json::readRequiredField(json, "latitude", value.latitude);
    Json::readRequiredField(json, "longitude", value.longitude);
    Json::readOptionalField(json, "horizontal_accuracy", value.horizontalAccuracy);
    Json::readOptionalField(json, "live_period", value.livePeriod);
    Json::readOptionalField(json, "heading", value.heading);
    Json::readOptionalField(json, "proximity_alert_radius", value.proximityAlertRadius);
}

void to_json(nlohmann::json& json, const Location& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "latitude", value.latitude);
    Json::writeRequiredField(json, "longitude", value.longitude);
    Json::writeOptionalField(json, "horizontal_accuracy", value.horizontalAccuracy);
    Json::writeOptionalField(json, "live_period", value.livePeriod);
    Json::writeOptionalField(json, "heading", value.heading);
    Json::writeOptionalField(json, "proximity_alert_radius", value.proximityAlertRadius);
}

} // namespace TgBot
