// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ManagedBotUpdated.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ManagedBotUpdated& value) {
    Json::readRequiredField(json, "user", value.user);
    Json::readRequiredField(json, "bot", value.bot);
}

void to_json(nlohmann::json& json, const ManagedBotUpdated& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "user", value.user);
    Json::writeRequiredField(json, "bot", value.bot);
}

} // namespace TgBot
