// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/MaskPosition.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, MaskPosition& value) {
    Json::readRequiredField(json, "point", value.point);
    Json::readRequiredField(json, "x_shift", value.xShift);
    Json::readRequiredField(json, "y_shift", value.yShift);
    Json::readRequiredField(json, "scale", value.scale);
}

void to_json(nlohmann::json& json, const MaskPosition& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "point", value.point);
    Json::writeRequiredField(json, "x_shift", value.xShift);
    Json::writeRequiredField(json, "y_shift", value.yShift);
    Json::writeRequiredField(json, "scale", value.scale);
}

} // namespace TgBot
