// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/MenuButtonCommands.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string MenuButtonCommands::TYPE = "commands";

void from_json(const nlohmann::json& json, MenuButtonCommands& value) {
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const MenuButtonCommands& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
