// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/MessageOriginChat.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"

namespace TgBot {

const std::string MessageOriginChat::TYPE = "chat";

void from_json(const nlohmann::json& json, MessageOriginChat& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "date", value.date);
    Json::readRequiredField(json, "sender_chat", value.senderChat);
    Json::readOptionalField(json, "author_signature", value.authorSignature);
}

void to_json(nlohmann::json& json, const MessageOriginChat& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "date", value.date);
    Json::writeRequiredField(json, "sender_chat", value.senderChat);
    Json::writeOptionalField(json, "author_signature", value.authorSignature);
}

} // namespace TgBot
