// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Message.h"
#include "tgbot/Json.h"
#include "tgbot/types/Animation.h"
#include "tgbot/types/Audio.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/ChatBackground.h"
#include "tgbot/types/ChatBoostAdded.h"
#include "tgbot/types/ChatOwnerChanged.h"
#include "tgbot/types/ChatOwnerLeft.h"
#include "tgbot/types/ChatShared.h"
#include "tgbot/types/Checklist.h"
#include "tgbot/types/ChecklistTasksAdded.h"
#include "tgbot/types/ChecklistTasksDone.h"
#include "tgbot/types/CommunityChatAdded.h"
#include "tgbot/types/CommunityChatRemoved.h"
#include "tgbot/types/Contact.h"
#include "tgbot/types/Dice.h"
#include "tgbot/types/DirectMessagePriceChanged.h"
#include "tgbot/types/DirectMessagesTopic.h"
#include "tgbot/types/Document.h"
#include "tgbot/types/ExternalReplyInfo.h"
#include "tgbot/types/ForumTopicClosed.h"
#include "tgbot/types/ForumTopicCreated.h"
#include "tgbot/types/ForumTopicEdited.h"
#include "tgbot/types/ForumTopicReopened.h"
#include "tgbot/types/Game.h"
#include "tgbot/types/GeneralForumTopicHidden.h"
#include "tgbot/types/GeneralForumTopicUnhidden.h"
#include "tgbot/types/GiftInfo.h"
#include "tgbot/types/Giveaway.h"
#include "tgbot/types/GiveawayCompleted.h"
#include "tgbot/types/GiveawayCreated.h"
#include "tgbot/types/GiveawayWinners.h"
#include "tgbot/types/InlineKeyboardMarkup.h"
#include "tgbot/types/Invoice.h"
#include "tgbot/types/LinkPreviewOptions.h"
#include "tgbot/types/LivePhoto.h"
#include "tgbot/types/Location.h"
#include "tgbot/types/ManagedBotCreated.h"
#include "tgbot/types/MaybeInaccessibleMessage.h"
#include "tgbot/types/MessageAutoDeleteTimerChanged.h"
#include "tgbot/types/MessageEntity.h"
#include "tgbot/types/MessageOrigin.h"
#include "tgbot/types/PaidMediaInfo.h"
#include "tgbot/types/PaidMessagePriceChanged.h"
#include "tgbot/types/PassportData.h"
#include "tgbot/types/PhotoSize.h"
#include "tgbot/types/Poll.h"
#include "tgbot/types/PollOptionAdded.h"
#include "tgbot/types/PollOptionDeleted.h"
#include "tgbot/types/ProximityAlertTriggered.h"
#include "tgbot/types/RefundedPayment.h"
#include "tgbot/types/RichMessage.h"
#include "tgbot/types/Sticker.h"
#include "tgbot/types/Story.h"
#include "tgbot/types/SuccessfulPayment.h"
#include "tgbot/types/SuggestedPostApprovalFailed.h"
#include "tgbot/types/SuggestedPostApproved.h"
#include "tgbot/types/SuggestedPostDeclined.h"
#include "tgbot/types/SuggestedPostInfo.h"
#include "tgbot/types/SuggestedPostPaid.h"
#include "tgbot/types/SuggestedPostRefunded.h"
#include "tgbot/types/TextQuote.h"
#include "tgbot/types/UniqueGiftInfo.h"
#include "tgbot/types/User.h"
#include "tgbot/types/UsersShared.h"
#include "tgbot/types/Venue.h"
#include "tgbot/types/Video.h"
#include "tgbot/types/VideoChatEnded.h"
#include "tgbot/types/VideoChatParticipantsInvited.h"
#include "tgbot/types/VideoChatScheduled.h"
#include "tgbot/types/VideoChatStarted.h"
#include "tgbot/types/VideoNote.h"
#include "tgbot/types/Voice.h"
#include "tgbot/types/WebAppData.h"
#include "tgbot/types/WriteAccessAllowed.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Message& value) {
    Json::readRequiredField(json, "message_id", value.messageId);
    Json::readOptionalField(json, "message_thread_id", value.messageThreadId);
    Json::readOptionalField(json, "direct_messages_topic", value.directMessagesTopic);
    Json::readOptionalField(json, "from", value.from);
    Json::readOptionalField(json, "sender_chat", value.senderChat);
    Json::readOptionalField(json, "sender_boost_count", value.senderBoostCount);
    Json::readOptionalField(json, "sender_business_bot", value.senderBusinessBot);
    Json::readOptionalField(json, "sender_tag", value.senderTag);
    Json::readOptionalField(json, "receiver_user", value.receiverUser);
    Json::readOptionalField(json, "ephemeral_message_id", value.ephemeralMessageId);
    Json::readRequiredField(json, "date", value.date);
    Json::readOptionalField(json, "guest_query_id", value.guestQueryId);
    Json::readOptionalField(json, "business_connection_id", value.businessConnectionId);
    Json::readRequiredField(json, "chat", value.chat);
    Json::readOptionalField(json, "forward_origin", value.forwardOrigin);
    Json::readOptionalField(json, "is_topic_message", value.isTopicMessage);
    Json::readOptionalField(json, "is_automatic_forward", value.isAutomaticForward);
    Json::readOptionalField(json, "reply_to_message", value.replyToMessage);
    Json::readOptionalField(json, "external_reply", value.externalReply);
    Json::readOptionalField(json, "quote", value.quote);
    Json::readOptionalField(json, "reply_to_story", value.replyToStory);
    Json::readOptionalField(json, "reply_to_checklist_task_id", value.replyToChecklistTaskId);
    Json::readOptionalField(json, "reply_to_poll_option_id", value.replyToPollOptionId);
    Json::readOptionalField(json, "via_bot", value.viaBot);
    Json::readOptionalField(json, "guest_bot_caller_user", value.guestBotCallerUser);
    Json::readOptionalField(json, "guest_bot_caller_chat", value.guestBotCallerChat);
    Json::readOptionalField(json, "edit_date", value.editDate);
    Json::readOptionalField(json, "has_protected_content", value.hasProtectedContent);
    Json::readOptionalField(json, "is_from_offline", value.isFromOffline);
    Json::readOptionalField(json, "is_paid_post", value.isPaidPost);
    Json::readOptionalField(json, "media_group_id", value.mediaGroupId);
    Json::readOptionalField(json, "author_signature", value.authorSignature);
    Json::readOptionalField(json, "paid_star_count", value.paidStarCount);
    Json::readOptionalField(json, "text", value.text);
    Json::readOptionalField(json, "entities", value.entities);
    Json::readOptionalField(json, "link_preview_options", value.linkPreviewOptions);
    Json::readOptionalField(json, "suggested_post_info", value.suggestedPostInfo);
    Json::readOptionalField(json, "effect_id", value.effectId);
    Json::readOptionalField(json, "rich_message", value.richMessage);
    Json::readOptionalField(json, "animation", value.animation);
    Json::readOptionalField(json, "audio", value.audio);
    Json::readOptionalField(json, "document", value.document);
    Json::readOptionalField(json, "live_photo", value.livePhoto);
    Json::readOptionalField(json, "paid_media", value.paidMedia);
    Json::readOptionalField(json, "photo", value.photo);
    Json::readOptionalField(json, "sticker", value.sticker);
    Json::readOptionalField(json, "story", value.story);
    Json::readOptionalField(json, "video", value.video);
    Json::readOptionalField(json, "video_note", value.videoNote);
    Json::readOptionalField(json, "voice", value.voice);
    Json::readOptionalField(json, "caption", value.caption);
    Json::readOptionalField(json, "caption_entities", value.captionEntities);
    Json::readOptionalField(json, "show_caption_above_media", value.showCaptionAboveMedia);
    Json::readOptionalField(json, "has_media_spoiler", value.hasMediaSpoiler);
    Json::readOptionalField(json, "checklist", value.checklist);
    Json::readOptionalField(json, "contact", value.contact);
    Json::readOptionalField(json, "dice", value.dice);
    Json::readOptionalField(json, "game", value.game);
    Json::readOptionalField(json, "poll", value.poll);
    Json::readOptionalField(json, "venue", value.venue);
    Json::readOptionalField(json, "location", value.location);
    Json::readOptionalField(json, "new_chat_members", value.newChatMembers);
    Json::readOptionalField(json, "left_chat_member", value.leftChatMember);
    Json::readOptionalField(json, "chat_owner_left", value.chatOwnerLeft);
    Json::readOptionalField(json, "chat_owner_changed", value.chatOwnerChanged);
    Json::readOptionalField(json, "new_chat_title", value.newChatTitle);
    Json::readOptionalField(json, "new_chat_photo", value.newChatPhoto);
    Json::readOptionalField(json, "delete_chat_photo", value.deleteChatPhoto);
    Json::readOptionalField(json, "group_chat_created", value.groupChatCreated);
    Json::readOptionalField(json, "supergroup_chat_created", value.supergroupChatCreated);
    Json::readOptionalField(json, "channel_chat_created", value.channelChatCreated);
    Json::readOptionalField(json, "message_auto_delete_timer_changed", value.messageAutoDeleteTimerChanged);
    Json::readOptionalField(json, "migrate_to_chat_id", value.migrateToChatId);
    Json::readOptionalField(json, "migrate_from_chat_id", value.migrateFromChatId);
    Json::readOptionalField(json, "pinned_message", value.pinnedMessage);
    Json::readOptionalField(json, "invoice", value.invoice);
    Json::readOptionalField(json, "successful_payment", value.successfulPayment);
    Json::readOptionalField(json, "refunded_payment", value.refundedPayment);
    Json::readOptionalField(json, "users_shared", value.usersShared);
    Json::readOptionalField(json, "chat_shared", value.chatShared);
    Json::readOptionalField(json, "gift", value.gift);
    Json::readOptionalField(json, "unique_gift", value.uniqueGift);
    Json::readOptionalField(json, "gift_upgrade_sent", value.giftUpgradeSent);
    Json::readOptionalField(json, "connected_website", value.connectedWebsite);
    Json::readOptionalField(json, "write_access_allowed", value.writeAccessAllowed);
    Json::readOptionalField(json, "passport_data", value.passportData);
    Json::readOptionalField(json, "proximity_alert_triggered", value.proximityAlertTriggered);
    Json::readOptionalField(json, "boost_added", value.boostAdded);
    Json::readOptionalField(json, "chat_background_set", value.chatBackgroundSet);
    Json::readOptionalField(json, "checklist_tasks_done", value.checklistTasksDone);
    Json::readOptionalField(json, "checklist_tasks_added", value.checklistTasksAdded);
    Json::readOptionalField(json, "community_chat_added", value.communityChatAdded);
    Json::readOptionalField(json, "community_chat_removed", value.communityChatRemoved);
    Json::readOptionalField(json, "direct_message_price_changed", value.directMessagePriceChanged);
    Json::readOptionalField(json, "forum_topic_created", value.forumTopicCreated);
    Json::readOptionalField(json, "forum_topic_edited", value.forumTopicEdited);
    Json::readOptionalField(json, "forum_topic_closed", value.forumTopicClosed);
    Json::readOptionalField(json, "forum_topic_reopened", value.forumTopicReopened);
    Json::readOptionalField(json, "general_forum_topic_hidden", value.generalForumTopicHidden);
    Json::readOptionalField(json, "general_forum_topic_unhidden", value.generalForumTopicUnhidden);
    Json::readOptionalField(json, "giveaway_created", value.giveawayCreated);
    Json::readOptionalField(json, "giveaway", value.giveaway);
    Json::readOptionalField(json, "giveaway_winners", value.giveawayWinners);
    Json::readOptionalField(json, "giveaway_completed", value.giveawayCompleted);
    Json::readOptionalField(json, "managed_bot_created", value.managedBotCreated);
    Json::readOptionalField(json, "paid_message_price_changed", value.paidMessagePriceChanged);
    Json::readOptionalField(json, "poll_option_added", value.pollOptionAdded);
    Json::readOptionalField(json, "poll_option_deleted", value.pollOptionDeleted);
    Json::readOptionalField(json, "suggested_post_approved", value.suggestedPostApproved);
    Json::readOptionalField(json, "suggested_post_approval_failed", value.suggestedPostApprovalFailed);
    Json::readOptionalField(json, "suggested_post_declined", value.suggestedPostDeclined);
    Json::readOptionalField(json, "suggested_post_paid", value.suggestedPostPaid);
    Json::readOptionalField(json, "suggested_post_refunded", value.suggestedPostRefunded);
    Json::readOptionalField(json, "video_chat_scheduled", value.videoChatScheduled);
    Json::readOptionalField(json, "video_chat_started", value.videoChatStarted);
    Json::readOptionalField(json, "video_chat_ended", value.videoChatEnded);
    Json::readOptionalField(json, "video_chat_participants_invited", value.videoChatParticipantsInvited);
    Json::readOptionalField(json, "web_app_data", value.webAppData);
    Json::readOptionalField(json, "reply_markup", value.replyMarkup);
}

void to_json(nlohmann::json& json, const Message& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "message_id", value.messageId);
    Json::writeOptionalField(json, "message_thread_id", value.messageThreadId);
    Json::writeOptionalField(json, "direct_messages_topic", value.directMessagesTopic);
    Json::writeOptionalField(json, "from", value.from);
    Json::writeOptionalField(json, "sender_chat", value.senderChat);
    Json::writeOptionalField(json, "sender_boost_count", value.senderBoostCount);
    Json::writeOptionalField(json, "sender_business_bot", value.senderBusinessBot);
    Json::writeOptionalField(json, "sender_tag", value.senderTag);
    Json::writeOptionalField(json, "receiver_user", value.receiverUser);
    Json::writeOptionalField(json, "ephemeral_message_id", value.ephemeralMessageId);
    Json::writeRequiredField(json, "date", value.date);
    Json::writeOptionalField(json, "guest_query_id", value.guestQueryId);
    Json::writeOptionalField(json, "business_connection_id", value.businessConnectionId);
    Json::writeRequiredField(json, "chat", value.chat);
    Json::writeOptionalField(json, "forward_origin", value.forwardOrigin);
    Json::writeOptionalField(json, "is_topic_message", value.isTopicMessage);
    Json::writeOptionalField(json, "is_automatic_forward", value.isAutomaticForward);
    Json::writeOptionalField(json, "reply_to_message", value.replyToMessage);
    Json::writeOptionalField(json, "external_reply", value.externalReply);
    Json::writeOptionalField(json, "quote", value.quote);
    Json::writeOptionalField(json, "reply_to_story", value.replyToStory);
    Json::writeOptionalField(json, "reply_to_checklist_task_id", value.replyToChecklistTaskId);
    Json::writeOptionalField(json, "reply_to_poll_option_id", value.replyToPollOptionId);
    Json::writeOptionalField(json, "via_bot", value.viaBot);
    Json::writeOptionalField(json, "guest_bot_caller_user", value.guestBotCallerUser);
    Json::writeOptionalField(json, "guest_bot_caller_chat", value.guestBotCallerChat);
    Json::writeOptionalField(json, "edit_date", value.editDate);
    Json::writeOptionalField(json, "has_protected_content", value.hasProtectedContent);
    Json::writeOptionalField(json, "is_from_offline", value.isFromOffline);
    Json::writeOptionalField(json, "is_paid_post", value.isPaidPost);
    Json::writeOptionalField(json, "media_group_id", value.mediaGroupId);
    Json::writeOptionalField(json, "author_signature", value.authorSignature);
    Json::writeOptionalField(json, "paid_star_count", value.paidStarCount);
    Json::writeOptionalField(json, "text", value.text);
    Json::writeOptionalField(json, "entities", value.entities);
    Json::writeOptionalField(json, "link_preview_options", value.linkPreviewOptions);
    Json::writeOptionalField(json, "suggested_post_info", value.suggestedPostInfo);
    Json::writeOptionalField(json, "effect_id", value.effectId);
    Json::writeOptionalField(json, "rich_message", value.richMessage);
    Json::writeOptionalField(json, "animation", value.animation);
    Json::writeOptionalField(json, "audio", value.audio);
    Json::writeOptionalField(json, "document", value.document);
    Json::writeOptionalField(json, "live_photo", value.livePhoto);
    Json::writeOptionalField(json, "paid_media", value.paidMedia);
    Json::writeOptionalField(json, "photo", value.photo);
    Json::writeOptionalField(json, "sticker", value.sticker);
    Json::writeOptionalField(json, "story", value.story);
    Json::writeOptionalField(json, "video", value.video);
    Json::writeOptionalField(json, "video_note", value.videoNote);
    Json::writeOptionalField(json, "voice", value.voice);
    Json::writeOptionalField(json, "caption", value.caption);
    Json::writeOptionalField(json, "caption_entities", value.captionEntities);
    Json::writeOptionalField(json, "show_caption_above_media", value.showCaptionAboveMedia);
    Json::writeOptionalField(json, "has_media_spoiler", value.hasMediaSpoiler);
    Json::writeOptionalField(json, "checklist", value.checklist);
    Json::writeOptionalField(json, "contact", value.contact);
    Json::writeOptionalField(json, "dice", value.dice);
    Json::writeOptionalField(json, "game", value.game);
    Json::writeOptionalField(json, "poll", value.poll);
    Json::writeOptionalField(json, "venue", value.venue);
    Json::writeOptionalField(json, "location", value.location);
    Json::writeOptionalField(json, "new_chat_members", value.newChatMembers);
    Json::writeOptionalField(json, "left_chat_member", value.leftChatMember);
    Json::writeOptionalField(json, "chat_owner_left", value.chatOwnerLeft);
    Json::writeOptionalField(json, "chat_owner_changed", value.chatOwnerChanged);
    Json::writeOptionalField(json, "new_chat_title", value.newChatTitle);
    Json::writeOptionalField(json, "new_chat_photo", value.newChatPhoto);
    Json::writeOptionalField(json, "delete_chat_photo", value.deleteChatPhoto);
    Json::writeOptionalField(json, "group_chat_created", value.groupChatCreated);
    Json::writeOptionalField(json, "supergroup_chat_created", value.supergroupChatCreated);
    Json::writeOptionalField(json, "channel_chat_created", value.channelChatCreated);
    Json::writeOptionalField(json, "message_auto_delete_timer_changed", value.messageAutoDeleteTimerChanged);
    Json::writeOptionalField(json, "migrate_to_chat_id", value.migrateToChatId);
    Json::writeOptionalField(json, "migrate_from_chat_id", value.migrateFromChatId);
    Json::writeOptionalField(json, "pinned_message", value.pinnedMessage);
    Json::writeOptionalField(json, "invoice", value.invoice);
    Json::writeOptionalField(json, "successful_payment", value.successfulPayment);
    Json::writeOptionalField(json, "refunded_payment", value.refundedPayment);
    Json::writeOptionalField(json, "users_shared", value.usersShared);
    Json::writeOptionalField(json, "chat_shared", value.chatShared);
    Json::writeOptionalField(json, "gift", value.gift);
    Json::writeOptionalField(json, "unique_gift", value.uniqueGift);
    Json::writeOptionalField(json, "gift_upgrade_sent", value.giftUpgradeSent);
    Json::writeOptionalField(json, "connected_website", value.connectedWebsite);
    Json::writeOptionalField(json, "write_access_allowed", value.writeAccessAllowed);
    Json::writeOptionalField(json, "passport_data", value.passportData);
    Json::writeOptionalField(json, "proximity_alert_triggered", value.proximityAlertTriggered);
    Json::writeOptionalField(json, "boost_added", value.boostAdded);
    Json::writeOptionalField(json, "chat_background_set", value.chatBackgroundSet);
    Json::writeOptionalField(json, "checklist_tasks_done", value.checklistTasksDone);
    Json::writeOptionalField(json, "checklist_tasks_added", value.checklistTasksAdded);
    Json::writeOptionalField(json, "community_chat_added", value.communityChatAdded);
    Json::writeOptionalField(json, "community_chat_removed", value.communityChatRemoved);
    Json::writeOptionalField(json, "direct_message_price_changed", value.directMessagePriceChanged);
    Json::writeOptionalField(json, "forum_topic_created", value.forumTopicCreated);
    Json::writeOptionalField(json, "forum_topic_edited", value.forumTopicEdited);
    Json::writeOptionalField(json, "forum_topic_closed", value.forumTopicClosed);
    Json::writeOptionalField(json, "forum_topic_reopened", value.forumTopicReopened);
    Json::writeOptionalField(json, "general_forum_topic_hidden", value.generalForumTopicHidden);
    Json::writeOptionalField(json, "general_forum_topic_unhidden", value.generalForumTopicUnhidden);
    Json::writeOptionalField(json, "giveaway_created", value.giveawayCreated);
    Json::writeOptionalField(json, "giveaway", value.giveaway);
    Json::writeOptionalField(json, "giveaway_winners", value.giveawayWinners);
    Json::writeOptionalField(json, "giveaway_completed", value.giveawayCompleted);
    Json::writeOptionalField(json, "managed_bot_created", value.managedBotCreated);
    Json::writeOptionalField(json, "paid_message_price_changed", value.paidMessagePriceChanged);
    Json::writeOptionalField(json, "poll_option_added", value.pollOptionAdded);
    Json::writeOptionalField(json, "poll_option_deleted", value.pollOptionDeleted);
    Json::writeOptionalField(json, "suggested_post_approved", value.suggestedPostApproved);
    Json::writeOptionalField(json, "suggested_post_approval_failed", value.suggestedPostApprovalFailed);
    Json::writeOptionalField(json, "suggested_post_declined", value.suggestedPostDeclined);
    Json::writeOptionalField(json, "suggested_post_paid", value.suggestedPostPaid);
    Json::writeOptionalField(json, "suggested_post_refunded", value.suggestedPostRefunded);
    Json::writeOptionalField(json, "video_chat_scheduled", value.videoChatScheduled);
    Json::writeOptionalField(json, "video_chat_started", value.videoChatStarted);
    Json::writeOptionalField(json, "video_chat_ended", value.videoChatEnded);
    Json::writeOptionalField(json, "video_chat_participants_invited", value.videoChatParticipantsInvited);
    Json::writeOptionalField(json, "web_app_data", value.webAppData);
    Json::writeOptionalField(json, "reply_markup", value.replyMarkup);
}

} // namespace TgBot
