// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/MessageOriginHiddenUser.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string MessageOriginHiddenUser::TYPE = "hidden_user";

void from_json(const nlohmann::json& json, MessageOriginHiddenUser& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "date", value.date);
    Json::readRequiredField(json, "sender_user_name", value.senderUserName);
}

void to_json(nlohmann::json& json, const MessageOriginHiddenUser& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "date", value.date);
    Json::writeRequiredField(json, "sender_user_name", value.senderUserName);
}

} // namespace TgBot
