// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/MessageAutoDeleteTimerChanged.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, MessageAutoDeleteTimerChanged& value) {
    Json::readRequiredField(json, "message_auto_delete_time", value.messageAutoDeleteTime);
}

void to_json(nlohmann::json& json, const MessageAutoDeleteTimerChanged& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "message_auto_delete_time", value.messageAutoDeleteTime);
}

} // namespace TgBot
