// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/MessageEntity.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

#include <stdexcept>

namespace TgBot {

void from_json(const nlohmann::json& json, MessageEntity::Type& value) {
    const auto text = json.get<std::string>();
    if (text == "mention") {
        value = MessageEntity::Type::Mention;
        return;
    }
    if (text == "hashtag") {
        value = MessageEntity::Type::Hashtag;
        return;
    }
    if (text == "cashtag") {
        value = MessageEntity::Type::Cashtag;
        return;
    }
    if (text == "bot_command") {
        value = MessageEntity::Type::BotCommand;
        return;
    }
    if (text == "url") {
        value = MessageEntity::Type::Url;
        return;
    }
    if (text == "email") {
        value = MessageEntity::Type::Email;
        return;
    }
    if (text == "phone_number") {
        value = MessageEntity::Type::PhoneNumber;
        return;
    }
    if (text == "bold") {
        value = MessageEntity::Type::Bold;
        return;
    }
    if (text == "italic") {
        value = MessageEntity::Type::Italic;
        return;
    }
    if (text == "underline") {
        value = MessageEntity::Type::Underline;
        return;
    }
    if (text == "strikethrough") {
        value = MessageEntity::Type::Strikethrough;
        return;
    }
    if (text == "spoiler") {
        value = MessageEntity::Type::Spoiler;
        return;
    }
    if (text == "blockquote") {
        value = MessageEntity::Type::Blockquote;
        return;
    }
    if (text == "expandable_blockquote") {
        value = MessageEntity::Type::ExpandableBlockquote;
        return;
    }
    if (text == "code") {
        value = MessageEntity::Type::Code;
        return;
    }
    if (text == "pre") {
        value = MessageEntity::Type::Pre;
        return;
    }
    if (text == "text_link") {
        value = MessageEntity::Type::TextLink;
        return;
    }
    if (text == "text_mention") {
        value = MessageEntity::Type::TextMention;
        return;
    }
    if (text == "custom_emoji") {
        value = MessageEntity::Type::CustomEmoji;
        return;
    }
    if (text == "date_time") {
        value = MessageEntity::Type::DateTime;
        return;
    }
    throw std::invalid_argument("Unknown MessageEntity.Type value: " + text);
}

void to_json(nlohmann::json& json, const MessageEntity::Type& value) {
    switch (value) {
    case MessageEntity::Type::Mention:
        json = "mention";
        return;
    case MessageEntity::Type::Hashtag:
        json = "hashtag";
        return;
    case MessageEntity::Type::Cashtag:
        json = "cashtag";
        return;
    case MessageEntity::Type::BotCommand:
        json = "bot_command";
        return;
    case MessageEntity::Type::Url:
        json = "url";
        return;
    case MessageEntity::Type::Email:
        json = "email";
        return;
    case MessageEntity::Type::PhoneNumber:
        json = "phone_number";
        return;
    case MessageEntity::Type::Bold:
        json = "bold";
        return;
    case MessageEntity::Type::Italic:
        json = "italic";
        return;
    case MessageEntity::Type::Underline:
        json = "underline";
        return;
    case MessageEntity::Type::Strikethrough:
        json = "strikethrough";
        return;
    case MessageEntity::Type::Spoiler:
        json = "spoiler";
        return;
    case MessageEntity::Type::Blockquote:
        json = "blockquote";
        return;
    case MessageEntity::Type::ExpandableBlockquote:
        json = "expandable_blockquote";
        return;
    case MessageEntity::Type::Code:
        json = "code";
        return;
    case MessageEntity::Type::Pre:
        json = "pre";
        return;
    case MessageEntity::Type::TextLink:
        json = "text_link";
        return;
    case MessageEntity::Type::TextMention:
        json = "text_mention";
        return;
    case MessageEntity::Type::CustomEmoji:
        json = "custom_emoji";
        return;
    case MessageEntity::Type::DateTime:
        json = "date_time";
        return;
    }
    throw std::invalid_argument("Unknown MessageEntity.Type value");
}

void from_json(const nlohmann::json& json, MessageEntity& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "offset", value.offset);
    Json::readRequiredField(json, "length", value.length);
    Json::readOptionalField(json, "url", value.url);
    Json::readOptionalField(json, "user", value.user);
    Json::readOptionalField(json, "language", value.language);
    Json::readOptionalField(json, "custom_emoji_id", value.customEmojiId);
    Json::readOptionalField(json, "unix_time", value.unixTime);
    Json::readOptionalField(json, "date_time_format", value.dateTimeFormat);
}

void to_json(nlohmann::json& json, const MessageEntity& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "offset", value.offset);
    Json::writeRequiredField(json, "length", value.length);
    Json::writeOptionalField(json, "url", value.url);
    Json::writeOptionalField(json, "user", value.user);
    Json::writeOptionalField(json, "language", value.language);
    Json::writeOptionalField(json, "custom_emoji_id", value.customEmojiId);
    Json::writeOptionalField(json, "unix_time", value.unixTime);
    Json::writeOptionalField(json, "date_time_format", value.dateTimeFormat);
}

} // namespace TgBot
