// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/OwnedGiftRegular.h"
#include "tgbot/Json.h"
#include "tgbot/types/Gift.h"
#include "tgbot/types/MessageEntity.h"
#include "tgbot/types/User.h"

namespace TgBot {

const std::string OwnedGiftRegular::TYPE = "regular";

void from_json(const nlohmann::json& json, OwnedGiftRegular& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "gift", value.gift);
    Json::readOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::readOptionalField(json, "sender_user", value.senderUser);
    Json::readRequiredField(json, "send_date", value.sendDate);
    Json::readOptionalField(json, "text", value.text);
    Json::readOptionalField(json, "entities", value.entities);
    Json::readOptionalField(json, "is_private", value.isPrivate);
    Json::readOptionalField(json, "is_saved", value.isSaved);
    Json::readOptionalField(json, "can_be_upgraded", value.canBeUpgraded);
    Json::readOptionalField(json, "was_refunded", value.wasRefunded);
    Json::readOptionalField(json, "convert_star_count", value.convertStarCount);
    Json::readOptionalField(json, "prepaid_upgrade_star_count", value.prepaidUpgradeStarCount);
    Json::readOptionalField(json, "is_upgrade_separate", value.isUpgradeSeparate);
    Json::readOptionalField(json, "unique_gift_number", value.uniqueGiftNumber);
}

void to_json(nlohmann::json& json, const OwnedGiftRegular& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "gift", value.gift);
    Json::writeOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::writeOptionalField(json, "sender_user", value.senderUser);
    Json::writeRequiredField(json, "send_date", value.sendDate);
    Json::writeOptionalField(json, "text", value.text);
    Json::writeOptionalField(json, "entities", value.entities);
    Json::writeOptionalField(json, "is_private", value.isPrivate);
    Json::writeOptionalField(json, "is_saved", value.isSaved);
    Json::writeOptionalField(json, "can_be_upgraded", value.canBeUpgraded);
    Json::writeOptionalField(json, "was_refunded", value.wasRefunded);
    Json::writeOptionalField(json, "convert_star_count", value.convertStarCount);
    Json::writeOptionalField(json, "prepaid_upgrade_star_count", value.prepaidUpgradeStarCount);
    Json::writeOptionalField(json, "is_upgrade_separate", value.isUpgradeSeparate);
    Json::writeOptionalField(json, "unique_gift_number", value.uniqueGiftNumber);
}

} // namespace TgBot
