// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/OwnedGiftUnique.h"
#include "tgbot/Json.h"
#include "tgbot/types/UniqueGift.h"
#include "tgbot/types/User.h"

namespace TgBot {

const std::string OwnedGiftUnique::TYPE = "unique";

void from_json(const nlohmann::json& json, OwnedGiftUnique& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "gift", value.gift);
    Json::readOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::readOptionalField(json, "sender_user", value.senderUser);
    Json::readRequiredField(json, "send_date", value.sendDate);
    Json::readOptionalField(json, "is_saved", value.isSaved);
    Json::readOptionalField(json, "can_be_transferred", value.canBeTransferred);
    Json::readOptionalField(json, "transfer_star_count", value.transferStarCount);
    Json::readOptionalField(json, "next_transfer_date", value.nextTransferDate);
}

void to_json(nlohmann::json& json, const OwnedGiftUnique& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "gift", value.gift);
    Json::writeOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::writeOptionalField(json, "sender_user", value.senderUser);
    Json::writeRequiredField(json, "send_date", value.sendDate);
    Json::writeOptionalField(json, "is_saved", value.isSaved);
    Json::writeOptionalField(json, "can_be_transferred", value.canBeTransferred);
    Json::writeOptionalField(json, "transfer_star_count", value.transferStarCount);
    Json::writeOptionalField(json, "next_transfer_date", value.nextTransferDate);
}

} // namespace TgBot
