// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PaidMessagePriceChanged.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, PaidMessagePriceChanged& value) {
    Json::readRequiredField(json, "paid_message_star_count", value.paidMessageStarCount);
}

void to_json(nlohmann::json& json, const PaidMessagePriceChanged& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "paid_message_star_count", value.paidMessageStarCount);
}

} // namespace TgBot
