// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PaidMediaVideo.h"
#include "tgbot/Json.h"
#include "tgbot/types/Video.h"

namespace TgBot {

const std::string PaidMediaVideo::TYPE = "video";

void from_json(const nlohmann::json& json, PaidMediaVideo& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "video", value.video);
}

void to_json(nlohmann::json& json, const PaidMediaVideo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "video", value.video);
}

} // namespace TgBot
