// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PaidMediaPhoto.h"
#include "tgbot/Json.h"
#include "tgbot/types/PhotoSize.h"

namespace TgBot {

const std::string PaidMediaPhoto::TYPE = "photo";

void from_json(const nlohmann::json& json, PaidMediaPhoto& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "photo", value.photo);
}

void to_json(nlohmann::json& json, const PaidMediaPhoto& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "photo", value.photo);
}

} // namespace TgBot
