// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PassportElementErrorSelfie.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string PassportElementErrorSelfie::SOURCE = "selfie";

void from_json(const nlohmann::json& json, PassportElementErrorSelfie& value) {
    Json::readRequiredField(json, "source", value.source);
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "file_hash", value.fileHash);
    Json::readRequiredField(json, "message", value.message);
}

void to_json(nlohmann::json& json, const PassportElementErrorSelfie& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "source", value.source);
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "file_hash", value.fileHash);
    Json::writeRequiredField(json, "message", value.message);
}

} // namespace TgBot
