// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PassportElementErrorUnspecified.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string PassportElementErrorUnspecified::SOURCE = "unspecified";

void from_json(const nlohmann::json& json, PassportElementErrorUnspecified& value) {
    Json::readRequiredField(json, "source", value.source);
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "element_hash", value.elementHash);
    Json::readRequiredField(json, "message", value.message);
}

void to_json(nlohmann::json& json, const PassportElementErrorUnspecified& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "source", value.source);
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "element_hash", value.elementHash);
    Json::writeRequiredField(json, "message", value.message);
}

} // namespace TgBot
