// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PhotoSize.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, PhotoSize& value) {
    Json::readRequiredField(json, "file_id", value.fileId);
    Json::readRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::readRequiredField(json, "width", value.width);
    Json::readRequiredField(json, "height", value.height);
    Json::readOptionalField(json, "file_size", value.fileSize);
}

void to_json(nlohmann::json& json, const PhotoSize& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "file_id", value.fileId);
    Json::writeRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::writeRequiredField(json, "width", value.width);
    Json::writeRequiredField(json, "height", value.height);
    Json::writeOptionalField(json, "file_size", value.fileSize);
}

} // namespace TgBot
