// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Poll.h"
#include "tgbot/Json.h"
#include "tgbot/types/MessageEntity.h"
#include "tgbot/types/PollMedia.h"
#include "tgbot/types/PollOption.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Poll& value) {
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "question", value.question);
    Json::readOptionalField(json, "question_entities", value.questionEntities);
    Json::readRequiredField(json, "options", value.options);
    Json::readRequiredField(json, "total_voter_count", value.totalVoterCount);
    Json::readRequiredField(json, "is_closed", value.isClosed);
    Json::readRequiredField(json, "is_anonymous", value.isAnonymous);
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "allows_multiple_answers", value.allowsMultipleAnswers);
    Json::readRequiredField(json, "allows_revoting", value.allowsRevoting);
    Json::readRequiredField(json, "members_only", value.membersOnly);
    Json::readOptionalField(json, "country_codes", value.countryCodes);
    Json::readOptionalField(json, "correct_option_ids", value.correctOptionIds);
    Json::readOptionalField(json, "explanation", value.explanation);
    Json::readOptionalField(json, "explanation_entities", value.explanationEntities);
    Json::readOptionalField(json, "explanation_media", value.explanationMedia);
    Json::readOptionalField(json, "open_period", value.openPeriod);
    Json::readOptionalField(json, "close_date", value.closeDate);
    Json::readOptionalField(json, "description", value.description);
    Json::readOptionalField(json, "description_entities", value.descriptionEntities);
    Json::readOptionalField(json, "media", value.media);
}

void to_json(nlohmann::json& json, const Poll& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "question", value.question);
    Json::writeOptionalField(json, "question_entities", value.questionEntities);
    Json::writeRequiredField(json, "options", value.options);
    Json::writeRequiredField(json, "total_voter_count", value.totalVoterCount);
    Json::writeRequiredField(json, "is_closed", value.isClosed);
    Json::writeRequiredField(json, "is_anonymous", value.isAnonymous);
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "allows_multiple_answers", value.allowsMultipleAnswers);
    Json::writeRequiredField(json, "allows_revoting", value.allowsRevoting);
    Json::writeRequiredField(json, "members_only", value.membersOnly);
    Json::writeOptionalField(json, "country_codes", value.countryCodes);
    Json::writeOptionalField(json, "correct_option_ids", value.correctOptionIds);
    Json::writeOptionalField(json, "explanation", value.explanation);
    Json::writeOptionalField(json, "explanation_entities", value.explanationEntities);
    Json::writeOptionalField(json, "explanation_media", value.explanationMedia);
    Json::writeOptionalField(json, "open_period", value.openPeriod);
    Json::writeOptionalField(json, "close_date", value.closeDate);
    Json::writeOptionalField(json, "description", value.description);
    Json::writeOptionalField(json, "description_entities", value.descriptionEntities);
    Json::writeOptionalField(json, "media", value.media);
}

} // namespace TgBot
