// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PollAnswer.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, PollAnswer& value) {
    Json::readRequiredField(json, "poll_id", value.pollId);
    Json::readOptionalField(json, "voter_chat", value.voterChat);
    Json::readOptionalField(json, "user", value.user);
    Json::readRequiredField(json, "option_ids", value.optionIds);
    Json::readRequiredField(json, "option_persistent_ids", value.optionPersistentIds);
}

void to_json(nlohmann::json& json, const PollAnswer& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "poll_id", value.pollId);
    Json::writeOptionalField(json, "voter_chat", value.voterChat);
    Json::writeOptionalField(json, "user", value.user);
    Json::writeRequiredField(json, "option_ids", value.optionIds);
    Json::writeRequiredField(json, "option_persistent_ids", value.optionPersistentIds);
}

} // namespace TgBot
