// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PollOptionAdded.h"
#include "tgbot/Json.h"
#include "tgbot/types/MaybeInaccessibleMessage.h"
#include "tgbot/types/MessageEntity.h"

namespace TgBot {

void from_json(const nlohmann::json& json, PollOptionAdded& value) {
    Json::readOptionalField(json, "poll_message", value.pollMessage);
    Json::readRequiredField(json, "option_persistent_id", value.optionPersistentId);
    Json::readRequiredField(json, "option_text", value.optionText);
    Json::readOptionalField(json, "option_text_entities", value.optionTextEntities);
}

void to_json(nlohmann::json& json, const PollOptionAdded& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "poll_message", value.pollMessage);
    Json::writeRequiredField(json, "option_persistent_id", value.optionPersistentId);
    Json::writeRequiredField(json, "option_text", value.optionText);
    Json::writeOptionalField(json, "option_text_entities", value.optionTextEntities);
}

} // namespace TgBot
