// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PollOption.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/MessageEntity.h"
#include "tgbot/types/PollMedia.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, PollOption& value) {
    Json::readRequiredField(json, "persistent_id", value.persistentId);
    Json::readRequiredField(json, "text", value.text);
    Json::readOptionalField(json, "text_entities", value.textEntities);
    Json::readOptionalField(json, "media", value.media);
    Json::readRequiredField(json, "voter_count", value.voterCount);
    Json::readOptionalField(json, "added_by_user", value.addedByUser);
    Json::readOptionalField(json, "added_by_chat", value.addedByChat);
    Json::readOptionalField(json, "addition_date", value.additionDate);
}

void to_json(nlohmann::json& json, const PollOption& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "persistent_id", value.persistentId);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeOptionalField(json, "text_entities", value.textEntities);
    Json::writeOptionalField(json, "media", value.media);
    Json::writeRequiredField(json, "voter_count", value.voterCount);
    Json::writeOptionalField(json, "added_by_user", value.addedByUser);
    Json::writeOptionalField(json, "added_by_chat", value.addedByChat);
    Json::writeOptionalField(json, "addition_date", value.additionDate);
}

} // namespace TgBot
