// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/PreparedKeyboardButton.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, PreparedKeyboardButton& value) {
    Json::readRequiredField(json, "id", value.id);
}

void to_json(nlohmann::json& json, const PreparedKeyboardButton& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
}

} // namespace TgBot
