// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ReactionTypeEmoji.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string ReactionTypeEmoji::TYPE = "emoji";

void from_json(const nlohmann::json& json, ReactionTypeEmoji& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "emoji", value.emoji);
}

void to_json(nlohmann::json& json, const ReactionTypeEmoji& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "emoji", value.emoji);
}

} // namespace TgBot
