// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ResponseParameters.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ResponseParameters& value) {
    Json::readOptionalField(json, "migrate_to_chat_id", value.migrateToChatId);
    Json::readOptionalField(json, "retry_after", value.retryAfter);
}

void to_json(nlohmann::json& json, const ResponseParameters& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "migrate_to_chat_id", value.migrateToChatId);
    Json::writeOptionalField(json, "retry_after", value.retryAfter);
}

} // namespace TgBot
