// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RevenueWithdrawalState.h"
#include "tgbot/Json.h"
#include "tgbot/types/RevenueWithdrawalStateFailed.h"
#include "tgbot/types/RevenueWithdrawalStatePending.h"
#include "tgbot/types/RevenueWithdrawalStateSucceeded.h"

namespace TgBot {

void from_json(const nlohmann::json& json, RevenueWithdrawalState& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const RevenueWithdrawalState& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
