// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RevenueWithdrawalStatePending.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string RevenueWithdrawalStatePending::TYPE = "pending";

void from_json(const nlohmann::json& json, RevenueWithdrawalStatePending& value) {
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const RevenueWithdrawalStatePending& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
