// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichTextHashtag.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string RichTextHashtag::TYPE = "hashtag";

void from_json(const nlohmann::json& json, RichTextHashtag& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
    Json::readRequiredField(json, "hashtag", value.hashtag);
}

void to_json(nlohmann::json& json, const RichTextHashtag& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeRequiredField(json, "hashtag", value.hashtag);
}

} // namespace TgBot
