// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockAnchor.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string RichBlockAnchor::TYPE = "anchor";

void from_json(const nlohmann::json& json, RichBlockAnchor& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "name", value.name);
}

void to_json(nlohmann::json& json, const RichBlockAnchor& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "name", value.name);
}

} // namespace TgBot
