// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichTextBotCommand.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string RichTextBotCommand::TYPE = "bot_command";

void from_json(const nlohmann::json& json, RichTextBotCommand& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
    Json::readRequiredField(json, "bot_command", value.botCommand);
}

void to_json(nlohmann::json& json, const RichTextBotCommand& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeRequiredField(json, "bot_command", value.botCommand);
}

} // namespace TgBot
