// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlock.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichBlockAnchor.h"
#include "tgbot/types/RichBlockAnimation.h"
#include "tgbot/types/RichBlockAudio.h"
#include "tgbot/types/RichBlockBlockQuotation.h"
#include "tgbot/types/RichBlockCollage.h"
#include "tgbot/types/RichBlockDetails.h"
#include "tgbot/types/RichBlockDivider.h"
#include "tgbot/types/RichBlockFooter.h"
#include "tgbot/types/RichBlockList.h"
#include "tgbot/types/RichBlockMap.h"
#include "tgbot/types/RichBlockMathematicalExpression.h"
#include "tgbot/types/RichBlockParagraph.h"
#include "tgbot/types/RichBlockPhoto.h"
#include "tgbot/types/RichBlockPreformatted.h"
#include "tgbot/types/RichBlockPullQuotation.h"
#include "tgbot/types/RichBlockSectionHeading.h"
#include "tgbot/types/RichBlockSlideshow.h"
#include "tgbot/types/RichBlockTable.h"
#include "tgbot/types/RichBlockThinking.h"
#include "tgbot/types/RichBlockVideo.h"
#include "tgbot/types/RichBlockVoiceNote.h"

namespace TgBot {

void from_json(const nlohmann::json& json, RichBlock& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const RichBlock& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
