// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockAnimation.h"
#include "tgbot/Json.h"
#include "tgbot/types/Animation.h"
#include "tgbot/types/RichBlockCaption.h"

namespace TgBot {

const std::string RichBlockAnimation::TYPE = "animation";

void from_json(const nlohmann::json& json, RichBlockAnimation& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "animation", value.animation);
    Json::readOptionalField(json, "has_spoiler", value.hasSpoiler);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const RichBlockAnimation& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "animation", value.animation);
    Json::writeOptionalField(json, "has_spoiler", value.hasSpoiler);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
