// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockPhoto.h"
#include "tgbot/Json.h"
#include "tgbot/types/PhotoSize.h"
#include "tgbot/types/RichBlockCaption.h"

namespace TgBot {

const std::string RichBlockPhoto::TYPE = "photo";

void from_json(const nlohmann::json& json, RichBlockPhoto& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "photo", value.photo);
    Json::readOptionalField(json, "has_spoiler", value.hasSpoiler);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const RichBlockPhoto& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "photo", value.photo);
    Json::writeOptionalField(json, "has_spoiler", value.hasSpoiler);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
