// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockVideo.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichBlockCaption.h"
#include "tgbot/types/Video.h"

namespace TgBot {

const std::string RichBlockVideo::TYPE = "video";

void from_json(const nlohmann::json& json, RichBlockVideo& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "video", value.video);
    Json::readOptionalField(json, "has_spoiler", value.hasSpoiler);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const RichBlockVideo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "video", value.video);
    Json::writeOptionalField(json, "has_spoiler", value.hasSpoiler);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
