// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichTextDateTime.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string RichTextDateTime::TYPE = "date_time";

void from_json(const nlohmann::json& json, RichTextDateTime& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
    Json::readRequiredField(json, "unix_time", value.unixTime);
    Json::readRequiredField(json, "date_time_format", value.dateTimeFormat);
}

void to_json(nlohmann::json& json, const RichTextDateTime& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeRequiredField(json, "unix_time", value.unixTime);
    Json::writeRequiredField(json, "date_time_format", value.dateTimeFormat);
}

} // namespace TgBot
