// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockMap.h"
#include "tgbot/Json.h"
#include "tgbot/types/Location.h"
#include "tgbot/types/RichBlockCaption.h"

namespace TgBot {

const std::string RichBlockMap::TYPE = "map";

void from_json(const nlohmann::json& json, RichBlockMap& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "location", value.location);
    Json::readRequiredField(json, "zoom", value.zoom);
    Json::readRequiredField(json, "width", value.width);
    Json::readRequiredField(json, "height", value.height);
    Json::readOptionalField(json, "caption", value.caption);
}

void to_json(nlohmann::json& json, const RichBlockMap& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "location", value.location);
    Json::writeRequiredField(json, "zoom", value.zoom);
    Json::writeRequiredField(json, "width", value.width);
    Json::writeRequiredField(json, "height", value.height);
    Json::writeOptionalField(json, "caption", value.caption);
}

} // namespace TgBot
