// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichTextMention.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string RichTextMention::TYPE = "mention";

void from_json(const nlohmann::json& json, RichTextMention& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
    Json::readRequiredField(json, "username", value.username);
}

void to_json(nlohmann::json& json, const RichTextMention& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeRequiredField(json, "username", value.username);
}

} // namespace TgBot
