// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockPreformatted.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

const std::string RichBlockPreformatted::TYPE = "pre";

void from_json(const nlohmann::json& json, RichBlockPreformatted& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "text", value.text);
    Json::readOptionalField(json, "language", value.language);
}

void to_json(nlohmann::json& json, const RichBlockPreformatted& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "text", value.text);
    Json::writeOptionalField(json, "language", value.language);
}

} // namespace TgBot
