// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichTextMathematicalExpression.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string RichTextMathematicalExpression::TYPE = "mathematical_expression";

void from_json(const nlohmann::json& json, RichTextMathematicalExpression& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "expression", value.expression);
}

void to_json(nlohmann::json& json, const RichTextMathematicalExpression& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "expression", value.expression);
}

} // namespace TgBot
