// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichText.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichTextAnchor.h"
#include "tgbot/types/RichTextAnchorLink.h"
#include "tgbot/types/RichTextBankCardNumber.h"
#include "tgbot/types/RichTextBold.h"
#include "tgbot/types/RichTextBotCommand.h"
#include "tgbot/types/RichTextCashtag.h"
#include "tgbot/types/RichTextCode.h"
#include "tgbot/types/RichTextCustomEmoji.h"
#include "tgbot/types/RichTextDateTime.h"
#include "tgbot/types/RichTextEmailAddress.h"
#include "tgbot/types/RichTextHashtag.h"
#include "tgbot/types/RichTextItalic.h"
#include "tgbot/types/RichTextMarked.h"
#include "tgbot/types/RichTextMathematicalExpression.h"
#include "tgbot/types/RichTextMention.h"
#include "tgbot/types/RichTextPhoneNumber.h"
#include "tgbot/types/RichTextReference.h"
#include "tgbot/types/RichTextReferenceLink.h"
#include "tgbot/types/RichTextSpoiler.h"
#include "tgbot/types/RichTextStrikethrough.h"
#include "tgbot/types/RichTextSubscript.h"
#include "tgbot/types/RichTextSuperscript.h"
#include "tgbot/types/RichTextTextMention.h"
#include "tgbot/types/RichTextUnderline.h"
#include "tgbot/types/RichTextUrl.h"

namespace TgBot {

void from_json(const nlohmann::json& json, RichText& value) {
    Json::decode(json, value.value);
}

void to_json(nlohmann::json& json, const RichText& value) {
    json = Json::encode(value.value);
}

} // namespace TgBot
