// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichBlockTableCell.h"
#include "tgbot/Json.h"
#include "tgbot/types/RichText.h"

namespace TgBot {

void from_json(const nlohmann::json& json, RichBlockTableCell& value) {
    Json::readOptionalField(json, "text", value.text);
    Json::readOptionalField(json, "is_header", value.isHeader);
    Json::readOptionalField(json, "colspan", value.colspan);
    Json::readOptionalField(json, "rowspan", value.rowspan);
    Json::readRequiredField(json, "align", value.align);
    Json::readRequiredField(json, "valign", value.valign);
}

void to_json(nlohmann::json& json, const RichBlockTableCell& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "text", value.text);
    Json::writeOptionalField(json, "is_header", value.isHeader);
    Json::writeOptionalField(json, "colspan", value.colspan);
    Json::writeOptionalField(json, "rowspan", value.rowspan);
    Json::writeRequiredField(json, "align", value.align);
    Json::writeRequiredField(json, "valign", value.valign);
}

} // namespace TgBot
