// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/RichTextCustomEmoji.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string RichTextCustomEmoji::TYPE = "custom_emoji";

void from_json(const nlohmann::json& json, RichTextCustomEmoji& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "custom_emoji_id", value.customEmojiId);
    Json::readRequiredField(json, "alternative_text", value.alternativeText);
}

void to_json(nlohmann::json& json, const RichTextCustomEmoji& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "custom_emoji_id", value.customEmojiId);
    Json::writeRequiredField(json, "alternative_text", value.alternativeText);
}

} // namespace TgBot
