// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/ShippingQuery.h"
#include "tgbot/Json.h"
#include "tgbot/types/ShippingAddress.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, ShippingQuery& value) {
    Json::readRequiredField(json, "id", value.id);
    Json::readRequiredField(json, "from", value.from);
    Json::readRequiredField(json, "invoice_payload", value.invoicePayload);
    Json::readRequiredField(json, "shipping_address", value.shippingAddress);
}

void to_json(nlohmann::json& json, const ShippingQuery& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "id", value.id);
    Json::writeRequiredField(json, "from", value.from);
    Json::writeRequiredField(json, "invoice_payload", value.invoicePayload);
    Json::writeRequiredField(json, "shipping_address", value.shippingAddress);
}

} // namespace TgBot
