// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/StarAmount.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, StarAmount& value) {
    Json::readRequiredField(json, "amount", value.amount);
    Json::readOptionalField(json, "nanostar_amount", value.nanostarAmount);
}

void to_json(nlohmann::json& json, const StarAmount& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "amount", value.amount);
    Json::writeOptionalField(json, "nanostar_amount", value.nanostarAmount);
}

} // namespace TgBot
