// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Sticker.h"
#include "tgbot/Json.h"
#include "tgbot/types/File.h"
#include "tgbot/types/MaskPosition.h"
#include "tgbot/types/PhotoSize.h"

#include <stdexcept>

namespace TgBot {

void from_json(const nlohmann::json& json, Sticker::Type& value) {
    const auto text = json.get<std::string>();
    if (text == "regular") {
        value = Sticker::Type::Regular;
        return;
    }
    if (text == "mask") {
        value = Sticker::Type::Mask;
        return;
    }
    if (text == "custom_emoji") {
        value = Sticker::Type::CustomEmoji;
        return;
    }
    throw std::invalid_argument("Unknown Sticker.Type value: " + text);
}

void to_json(nlohmann::json& json, const Sticker::Type& value) {
    switch (value) {
    case Sticker::Type::Regular:
        json = "regular";
        return;
    case Sticker::Type::Mask:
        json = "mask";
        return;
    case Sticker::Type::CustomEmoji:
        json = "custom_emoji";
        return;
    }
    throw std::invalid_argument("Unknown Sticker.Type value");
}

void from_json(const nlohmann::json& json, Sticker& value) {
    Json::readRequiredField(json, "file_id", value.fileId);
    Json::readRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "width", value.width);
    Json::readRequiredField(json, "height", value.height);
    Json::readRequiredField(json, "is_animated", value.isAnimated);
    Json::readRequiredField(json, "is_video", value.isVideo);
    Json::readOptionalField(json, "thumbnail", value.thumbnail);
    Json::readOptionalField(json, "emoji", value.emoji);
    Json::readOptionalField(json, "set_name", value.setName);
    Json::readOptionalField(json, "premium_animation", value.premiumAnimation);
    Json::readOptionalField(json, "mask_position", value.maskPosition);
    Json::readOptionalField(json, "custom_emoji_id", value.customEmojiId);
    Json::readOptionalField(json, "needs_repainting", value.needsRepainting);
    Json::readOptionalField(json, "file_size", value.fileSize);
}

void to_json(nlohmann::json& json, const Sticker& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "file_id", value.fileId);
    Json::writeRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "width", value.width);
    Json::writeRequiredField(json, "height", value.height);
    Json::writeRequiredField(json, "is_animated", value.isAnimated);
    Json::writeRequiredField(json, "is_video", value.isVideo);
    Json::writeOptionalField(json, "thumbnail", value.thumbnail);
    Json::writeOptionalField(json, "emoji", value.emoji);
    Json::writeOptionalField(json, "set_name", value.setName);
    Json::writeOptionalField(json, "premium_animation", value.premiumAnimation);
    Json::writeOptionalField(json, "mask_position", value.maskPosition);
    Json::writeOptionalField(json, "custom_emoji_id", value.customEmojiId);
    Json::writeOptionalField(json, "needs_repainting", value.needsRepainting);
    Json::writeOptionalField(json, "file_size", value.fileSize);
}

} // namespace TgBot
