// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/StoryAreaTypeLink.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string StoryAreaTypeLink::TYPE = "link";

void from_json(const nlohmann::json& json, StoryAreaTypeLink& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "url", value.url);
}

void to_json(nlohmann::json& json, const StoryAreaTypeLink& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "url", value.url);
}

} // namespace TgBot
