// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/StoryAreaTypeSuggestedReaction.h"
#include "tgbot/Json.h"
#include "tgbot/types/ReactionType.h"

namespace TgBot {

const std::string StoryAreaTypeSuggestedReaction::TYPE = "suggested_reaction";

void from_json(const nlohmann::json& json, StoryAreaTypeSuggestedReaction& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "reaction_type", value.reactionType);
    Json::readOptionalField(json, "is_dark", value.isDark);
    Json::readOptionalField(json, "is_flipped", value.isFlipped);
}

void to_json(nlohmann::json& json, const StoryAreaTypeSuggestedReaction& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "reaction_type", value.reactionType);
    Json::writeOptionalField(json, "is_dark", value.isDark);
    Json::writeOptionalField(json, "is_flipped", value.isFlipped);
}

} // namespace TgBot
