// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/StoryAreaTypeWeather.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string StoryAreaTypeWeather::TYPE = "weather";

void from_json(const nlohmann::json& json, StoryAreaTypeWeather& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "temperature", value.temperature);
    Json::readRequiredField(json, "emoji", value.emoji);
    Json::readRequiredField(json, "background_color", value.backgroundColor);
}

void to_json(nlohmann::json& json, const StoryAreaTypeWeather& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "temperature", value.temperature);
    Json::writeRequiredField(json, "emoji", value.emoji);
    Json::writeRequiredField(json, "background_color", value.backgroundColor);
}

} // namespace TgBot
