// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/StoryArea.h"
#include "tgbot/Json.h"
#include "tgbot/types/StoryAreaPosition.h"
#include "tgbot/types/StoryAreaType.h"

namespace TgBot {

void from_json(const nlohmann::json& json, StoryArea& value) {
    Json::readRequiredField(json, "position", value.position);
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const StoryArea& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "position", value.position);
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
