// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/SuggestedPostDeclined.h"
#include "tgbot/Json.h"
#include "tgbot/types/Message.h"

namespace TgBot {

void from_json(const nlohmann::json& json, SuggestedPostDeclined& value) {
    Json::readOptionalField(json, "suggested_post_message", value.suggestedPostMessage);
    Json::readOptionalField(json, "comment", value.comment);
}

void to_json(nlohmann::json& json, const SuggestedPostDeclined& value) {
    json = nlohmann::json::object();
    Json::writeOptionalField(json, "suggested_post_message", value.suggestedPostMessage);
    Json::writeOptionalField(json, "comment", value.comment);
}

} // namespace TgBot
