// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/SuggestedPostPrice.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, SuggestedPostPrice& value) {
    Json::readRequiredField(json, "currency", value.currency);
    Json::readRequiredField(json, "amount", value.amount);
}

void to_json(nlohmann::json& json, const SuggestedPostPrice& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "currency", value.currency);
    Json::writeRequiredField(json, "amount", value.amount);
}

} // namespace TgBot
