// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/SuggestedPostInfo.h"
#include "tgbot/Json.h"
#include "tgbot/types/SuggestedPostPrice.h"

namespace TgBot {

void from_json(const nlohmann::json& json, SuggestedPostInfo& value) {
    Json::readRequiredField(json, "state", value.state);
    Json::readOptionalField(json, "price", value.price);
    Json::readOptionalField(json, "send_date", value.sendDate);
}

void to_json(nlohmann::json& json, const SuggestedPostInfo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "state", value.state);
    Json::writeOptionalField(json, "price", value.price);
    Json::writeOptionalField(json, "send_date", value.sendDate);
}

} // namespace TgBot
