// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/TransactionPartnerOther.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string TransactionPartnerOther::TYPE = "other";

void from_json(const nlohmann::json& json, TransactionPartnerOther& value) {
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const TransactionPartnerOther& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
