// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/TransactionPartnerTelegramApi.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string TransactionPartnerTelegramApi::TYPE = "telegram_api";

void from_json(const nlohmann::json& json, TransactionPartnerTelegramApi& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "request_count", value.requestCount);
}

void to_json(nlohmann::json& json, const TransactionPartnerTelegramApi& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "request_count", value.requestCount);
}

} // namespace TgBot
