// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/TransactionPartnerChat.h"
#include "tgbot/Json.h"
#include "tgbot/types/Chat.h"
#include "tgbot/types/Gift.h"

namespace TgBot {

const std::string TransactionPartnerChat::TYPE = "chat";

void from_json(const nlohmann::json& json, TransactionPartnerChat& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readRequiredField(json, "chat", value.chat);
    Json::readOptionalField(json, "gift", value.gift);
}

void to_json(nlohmann::json& json, const TransactionPartnerChat& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeRequiredField(json, "chat", value.chat);
    Json::writeOptionalField(json, "gift", value.gift);
}

} // namespace TgBot
