// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/TransactionPartnerAffiliateProgram.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

const std::string TransactionPartnerAffiliateProgram::TYPE = "affiliate_program";

void from_json(const nlohmann::json& json, TransactionPartnerAffiliateProgram& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readOptionalField(json, "sponsor_user", value.sponsorUser);
    Json::readRequiredField(json, "commission_per_mille", value.commissionPerMille);
}

void to_json(nlohmann::json& json, const TransactionPartnerAffiliateProgram& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeOptionalField(json, "sponsor_user", value.sponsorUser);
    Json::writeRequiredField(json, "commission_per_mille", value.commissionPerMille);
}

} // namespace TgBot
