// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/TransactionPartnerTelegramAds.h"
#include "tgbot/Json.h"

namespace TgBot {

const std::string TransactionPartnerTelegramAds::TYPE = "telegram_ads";

void from_json(const nlohmann::json& json, TransactionPartnerTelegramAds& value) {
    Json::readRequiredField(json, "type", value.type);
}

void to_json(nlohmann::json& json, const TransactionPartnerTelegramAds& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
}

} // namespace TgBot
