// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/TransactionPartnerFragment.h"
#include "tgbot/Json.h"
#include "tgbot/types/RevenueWithdrawalState.h"

namespace TgBot {

const std::string TransactionPartnerFragment::TYPE = "fragment";

void from_json(const nlohmann::json& json, TransactionPartnerFragment& value) {
    Json::readRequiredField(json, "type", value.type);
    Json::readOptionalField(json, "withdrawal_state", value.withdrawalState);
}

void to_json(nlohmann::json& json, const TransactionPartnerFragment& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "type", value.type);
    Json::writeOptionalField(json, "withdrawal_state", value.withdrawalState);
}

} // namespace TgBot
