// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/UniqueGiftInfo.h"
#include "tgbot/Json.h"
#include "tgbot/types/UniqueGift.h"

namespace TgBot {

void from_json(const nlohmann::json& json, UniqueGiftInfo& value) {
    Json::readRequiredField(json, "gift", value.gift);
    Json::readRequiredField(json, "origin", value.origin);
    Json::readOptionalField(json, "last_resale_currency", value.lastResaleCurrency);
    Json::readOptionalField(json, "last_resale_amount", value.lastResaleAmount);
    Json::readOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::readOptionalField(json, "transfer_star_count", value.transferStarCount);
    Json::readOptionalField(json, "next_transfer_date", value.nextTransferDate);
}

void to_json(nlohmann::json& json, const UniqueGiftInfo& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "gift", value.gift);
    Json::writeRequiredField(json, "origin", value.origin);
    Json::writeOptionalField(json, "last_resale_currency", value.lastResaleCurrency);
    Json::writeOptionalField(json, "last_resale_amount", value.lastResaleAmount);
    Json::writeOptionalField(json, "owned_gift_id", value.ownedGiftId);
    Json::writeOptionalField(json, "transfer_star_count", value.transferStarCount);
    Json::writeOptionalField(json, "next_transfer_date", value.nextTransferDate);
}

} // namespace TgBot
