// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/UniqueGiftBackdropColors.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, UniqueGiftBackdropColors& value) {
    Json::readRequiredField(json, "center_color", value.centerColor);
    Json::readRequiredField(json, "edge_color", value.edgeColor);
    Json::readRequiredField(json, "symbol_color", value.symbolColor);
    Json::readRequiredField(json, "text_color", value.textColor);
}

void to_json(nlohmann::json& json, const UniqueGiftBackdropColors& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "center_color", value.centerColor);
    Json::writeRequiredField(json, "edge_color", value.edgeColor);
    Json::writeRequiredField(json, "symbol_color", value.symbolColor);
    Json::writeRequiredField(json, "text_color", value.textColor);
}

} // namespace TgBot
