// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/UserProfilePhotos.h"
#include "tgbot/Json.h"
#include "tgbot/types/PhotoSize.h"

namespace TgBot {

void from_json(const nlohmann::json& json, UserProfilePhotos& value) {
    Json::readRequiredField(json, "total_count", value.totalCount);
    Json::readRequiredField(json, "photos", value.photos);
}

void to_json(nlohmann::json& json, const UserProfilePhotos& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "total_count", value.totalCount);
    Json::writeRequiredField(json, "photos", value.photos);
}

} // namespace TgBot
