// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/VideoChatParticipantsInvited.h"
#include "tgbot/Json.h"
#include "tgbot/types/User.h"

namespace TgBot {

void from_json(const nlohmann::json& json, VideoChatParticipantsInvited& value) {
    Json::readRequiredField(json, "users", value.users);
}

void to_json(nlohmann::json& json, const VideoChatParticipantsInvited& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "users", value.users);
}

} // namespace TgBot
