// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/Video.h"
#include "tgbot/Json.h"
#include "tgbot/types/PhotoSize.h"
#include "tgbot/types/VideoQuality.h"

namespace TgBot {

void from_json(const nlohmann::json& json, Video& value) {
    Json::readRequiredField(json, "file_id", value.fileId);
    Json::readRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::readRequiredField(json, "width", value.width);
    Json::readRequiredField(json, "height", value.height);
    Json::readRequiredField(json, "duration", value.duration);
    Json::readOptionalField(json, "thumbnail", value.thumbnail);
    Json::readOptionalField(json, "cover", value.cover);
    Json::readOptionalField(json, "start_timestamp", value.startTimestamp);
    Json::readOptionalField(json, "qualities", value.qualities);
    Json::readOptionalField(json, "file_name", value.fileName);
    Json::readOptionalField(json, "mime_type", value.mimeType);
    Json::readOptionalField(json, "file_size", value.fileSize);
}

void to_json(nlohmann::json& json, const Video& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "file_id", value.fileId);
    Json::writeRequiredField(json, "file_unique_id", value.fileUniqueId);
    Json::writeRequiredField(json, "width", value.width);
    Json::writeRequiredField(json, "height", value.height);
    Json::writeRequiredField(json, "duration", value.duration);
    Json::writeOptionalField(json, "thumbnail", value.thumbnail);
    Json::writeOptionalField(json, "cover", value.cover);
    Json::writeOptionalField(json, "start_timestamp", value.startTimestamp);
    Json::writeOptionalField(json, "qualities", value.qualities);
    Json::writeOptionalField(json, "file_name", value.fileName);
    Json::writeOptionalField(json, "mime_type", value.mimeType);
    Json::writeOptionalField(json, "file_size", value.fileSize);
}

} // namespace TgBot
