// Generated by `make api-generate`. Do not edit.

#include "tgbot/types/VideoChatEnded.h"
#include "tgbot/Json.h"

namespace TgBot {

void from_json(const nlohmann::json& json, VideoChatEnded& value) {
    Json::readRequiredField(json, "duration", value.duration);
}

void to_json(nlohmann::json& json, const VideoChatEnded& value) {
    json = nlohmann::json::object();
    Json::writeRequiredField(json, "duration", value.duration);
}

} // namespace TgBot
