#ifndef TGBOT_TGBOT_H
#define TGBOT_TGBOT_H

#include "maxbot/Api.h"
#include "maxbot/Bot.h"
#include "maxbot/EventBroadcaster.h"
#include "maxbot/EventHandler.h"
#include "maxbot/BotException.h"
#include "maxbot/BotTypeParser.h"
#include "maxbot/net/BoostHttpOnlySslClient.h"
#include "maxbot/net/CurlHttpClient.h"
#include "maxbot/net/HttpClient.h"
#include "maxbot/net/HttpParser.h"
#include "maxbot/net/HttpReqArg.h"
#include "maxbot/net/HttpServer.h"
#include "maxbot/net/BotLongPoll.h"
#include "maxbot/net/BotWebhookLocalServer.h"
#include "maxbot/net/BotWebhookServer.h"
#include "maxbot/net/BotWebhookTcpServer.h"
#include "maxbot/net/Url.h"
#include "maxbot/maxbot.h"
#include "maxbot/tools/FileTools.h"
#include "maxbot/tools/StringTools.h"
#include "maxbot/types/Animation.h"
#include "maxbot/types/Audio.h"
#include "maxbot/types/CallbackGame.h"
#include "maxbot/types/CallbackQuery.h"
#include "maxbot/types/Chat.h"
#include "maxbot/types/ChatMember.h"
#include "maxbot/types/ChatPhoto.h"
#include "maxbot/types/ChosenInlineResult.h"
#include "maxbot/types/Contact.h"
#include "maxbot/types/Document.h"
#include "maxbot/types/File.h"
#include "maxbot/types/ForceReply.h"
#include "maxbot/types/Game.h"
#include "maxbot/types/GameHighScore.h"
#include "maxbot/types/GenericReply.h"
#include "maxbot/types/InlineKeyboardButton.h"
#include "maxbot/types/InlineKeyboardMarkup.h"
#include "maxbot/types/InlineQuery.h"
#include "maxbot/types/InlineQueryResult.h"
#include "maxbot/types/InlineQueryResultArticle.h"
#include "maxbot/types/InlineQueryResultAudio.h"
#include "maxbot/types/InlineQueryResultCachedAudio.h"
#include "maxbot/types/InlineQueryResultCachedDocument.h"
#include "maxbot/types/InlineQueryResultCachedGif.h"
#include "maxbot/types/InlineQueryResultCachedMpeg4Gif.h"
#include "maxbot/types/InlineQueryResultCachedPhoto.h"
#include "maxbot/types/InlineQueryResultCachedSticker.h"
#include "maxbot/types/InlineQueryResultCachedVideo.h"
#include "maxbot/types/InlineQueryResultCachedVoice.h"
#include "maxbot/types/InlineQueryResultContact.h"
#include "maxbot/types/InlineQueryResultDocument.h"
#include "maxbot/types/InlineQueryResultGame.h"
#include "maxbot/types/InlineQueryResultGif.h"
#include "maxbot/types/InlineQueryResultLocation.h"
#include "maxbot/types/InlineQueryResultMpeg4Gif.h"
#include "maxbot/types/InlineQueryResultPhoto.h"
#include "maxbot/types/InlineQueryResultVenue.h"
#include "maxbot/types/InlineQueryResultVideo.h"
#include "maxbot/types/InlineQueryResultVoice.h"
#include "maxbot/types/InputContactMessageContent.h"
#include "maxbot/types/InputFile.h"
#include "maxbot/types/InputLocationMessageContent.h"
#include "maxbot/types/InputMedia.h"
#include "maxbot/types/InputMediaPhoto.h"
#include "maxbot/types/InputMediaVideo.h"
#include "maxbot/types/InputMessageContent.h"
#include "maxbot/types/InputTextMessageContent.h"
#include "maxbot/types/InputVenueMessageContent.h"
#include "maxbot/types/Invoice.h"
#include "maxbot/types/KeyboardButton.h"
#include "maxbot/types/LabeledPrice.h"
#include "maxbot/types/Location.h"
#include "maxbot/types/MaskPosition.h"
#include "maxbot/types/Message.h"
#include "maxbot/types/MessageEntity.h"
#include "maxbot/types/OrderInfo.h"
#include "maxbot/types/PhotoSize.h"
#include "maxbot/types/PreCheckoutQuery.h"
#include "maxbot/types/ReplyKeyboardMarkup.h"
#include "maxbot/types/ReplyKeyboardRemove.h"
#include "maxbot/types/ResponseParameters.h"
#include "maxbot/types/ShippingAddress.h"
#include "maxbot/types/ShippingOption.h"
#include "maxbot/types/ShippingQuery.h"
#include "maxbot/types/Sticker.h"
#include "maxbot/types/StickerSet.h"
#include "maxbot/types/SuccessfulPayment.h"
#include "maxbot/types/Update.h"
#include "maxbot/types/User.h"
#include "maxbot/types/UserProfilePhotos.h"
#include "maxbot/types/Venue.h"
#include "maxbot/types/Video.h"
#include "maxbot/types/VideoNote.h"
#include "maxbot/types/Voice.h"
#include "maxbot/types/WebhookInfo.h"
#include "maxbot/types/BotCommand.h"


/**
 * @defgroup general
 * @defgroup types
 * @defgroup net
 * @defgroup tools
 *
 * @mainpage
 * [Go to GitHub](https://github.com/reo7sp/maxbot-cpp)
 *
 */

#endif //TGBOT_TGBOT_H
