#!/bin/bash
set -e -o pipefail

./generate-docs
git checkout gh-pages
find . -maxdepth 1 -not -name "docs" -not -name ".git" -print0 | xargs -0 rm -r
mv docs/* .
mv docs/.nojekyll .
rmdir docs
git add -A
git commit -m "Updated docs $(date)"
git push origin gh-pages
