// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

/**
 * @brief This object describes the types of gifts that can be gifted to a user or a chat.
 */
struct AcceptedGiftTypes {
    using Ptr = std::shared_ptr<AcceptedGiftTypes>;

    /**
     * @brief True, if unlimited regular gifts are accepted
    */
    bool unlimitedGifts { };

    /**
     * @brief True, if limited regular gifts are accepted
    */
    bool limitedGifts { };

    /**
     * @brief True, if unique gifts or gifts that can be upgraded to unique for free are accepted
    */
    bool uniqueGifts { };

    /**
     * @brief True, if a Telegram Premium subscription is accepted
    */
    bool premiumSubscription { };

    /**
     * @brief True, if transfers of unique gifts from channels are accepted
    */
    bool giftsFromChannels { };
};

TGBOT_API void from_json(const nlohmann::json& json, AcceptedGiftTypes& value);
TGBOT_API void to_json(nlohmann::json& json, const AcceptedGiftTypes& value);

} // namespace TgBot
