// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct BackgroundFill;
struct Document;

/**
 * @brief The background is a .PNG or .TGV (gzipped subset of SVG with MIME type
 * “application/x-tgwallpattern”) pattern to be combined with the background fill chosen by the
 * user.
 */
struct BackgroundTypePattern {
    using Ptr = std::shared_ptr<BackgroundTypePattern>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the background, always “pattern”
    */
    std::string type { TYPE };

    /**
     * @brief Document with the pattern
    */
    std::shared_ptr<Document> document { };

    /**
     * @brief The background fill that is combined with the pattern
    */
    std::shared_ptr<BackgroundFill> fill { };

    /**
     * @brief Intensity of the pattern when it is shown above the filled background; 0-100
    */
    std::int32_t intensity { };

    /**
     * @brief Optional. True, if the background fill must be applied only to the pattern itself. All
     * other pixels are black in this case. For dark themes only.
    */
    std::optional<bool> isInverted { };

    /**
     * @brief Optional. True, if the background moves slightly when the device is tilted
    */
    std::optional<bool> isMoving { };
};

TGBOT_API void from_json(const nlohmann::json& json, BackgroundTypePattern& value);
TGBOT_API void to_json(nlohmann::json& json, const BackgroundTypePattern& value);

} // namespace TgBot
