// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct BackgroundFill;

/**
 * @brief The background is automatically filled based on the selected colors.
 */
struct BackgroundTypeFill {
    using Ptr = std::shared_ptr<BackgroundTypeFill>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the background, always “fill”
    */
    std::string type { TYPE };

    /**
     * @brief The background fill
    */
    std::shared_ptr<BackgroundFill> fill { };

    /**
     * @brief Dimming of the background in dark themes, as a percentage; 0-100
    */
    std::int32_t darkThemeDimming { };
};

TGBOT_API void from_json(const nlohmann::json& json, BackgroundTypeFill& value);
TGBOT_API void to_json(nlohmann::json& json, const BackgroundTypeFill& value);

} // namespace TgBot
