// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief The background is filled using the selected color.
 */
struct BackgroundFillSolid {
    using Ptr = std::shared_ptr<BackgroundFillSolid>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the background fill, always “solid”
    */
    std::string type { TYPE };

    /**
     * @brief The color of the background fill in the RGB24 format
    */
    std::int32_t color { };
};

TGBOT_API void from_json(const nlohmann::json& json, BackgroundFillSolid& value);
TGBOT_API void to_json(nlohmann::json& json, const BackgroundFillSolid& value);

} // namespace TgBot
