// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>

namespace TgBot {

/**
 * @brief Describes the birthdate of a user.
 */
struct Birthdate {
    using Ptr = std::shared_ptr<Birthdate>;

    /**
     * @brief Day of the user's birth; 1-31
    */
    std::int32_t day { };

    /**
     * @brief Month of the user's birth; 1-12
    */
    std::int32_t month { };

    /**
     * @brief Optional. Year of the user's birth
    */
    std::optional<std::int32_t> year { };
};

TGBOT_API void from_json(const nlohmann::json& json, Birthdate& value);
TGBOT_API void to_json(nlohmann::json& json, const Birthdate& value);

} // namespace TgBot
