// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct BotCommandScopeAllChatAdministrators;
struct BotCommandScopeAllGroupChats;
struct BotCommandScopeAllPrivateChats;
struct BotCommandScopeChat;
struct BotCommandScopeChatAdministrators;
struct BotCommandScopeChatMember;
struct BotCommandScopeDefault;

/**
 * @brief This object represents the scope to which bot commands are applied. Currently, the following
 * 7 scopes are supported: BotCommandScopeDefault BotCommandScopeAllPrivateChats
 * BotCommandScopeAllGroupChats BotCommandScopeAllChatAdministrators BotCommandScopeChat
 * BotCommandScopeChatAdministrators BotCommandScopeChatMember
 */
struct BotCommandScope {
    using Ptr = std::shared_ptr<BotCommandScope>;

    std::variant<std::shared_ptr<BotCommandScopeDefault>, std::shared_ptr<BotCommandScopeAllPrivateChats>,
                 std::shared_ptr<BotCommandScopeAllGroupChats>, std::shared_ptr<BotCommandScopeAllChatAdministrators>,
                 std::shared_ptr<BotCommandScopeChat>, std::shared_ptr<BotCommandScopeChatAdministrators>,
                 std::shared_ptr<BotCommandScopeChatMember>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, BotCommandScope& value);
TGBOT_API void to_json(nlohmann::json& json, const BotCommandScope& value);

} // namespace TgBot
