// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Represents the scope of bot commands, covering all group and supergroup chats.
 */
struct BotCommandScopeAllGroupChats {
    using Ptr = std::shared_ptr<BotCommandScopeAllGroupChats>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Scope type, must be all_group_chats
    */
    std::string type { TYPE };
};

TGBOT_API void from_json(const nlohmann::json& json, BotCommandScopeAllGroupChats& value);
TGBOT_API void to_json(nlohmann::json& json, const BotCommandScopeAllGroupChats& value);

} // namespace TgBot
