// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents a bot command.
 */
struct BotCommand {
    using Ptr = std::shared_ptr<BotCommand>;

    /**
     * @brief Text of the command; 1-32 characters. Can contain only lowercase English letters, digits
     * and underscores.
    */
    std::string command { };

    /**
     * @brief Description of the command; 1-256 characters
    */
    std::string description { };

    /**
     * @brief Optional. True, if the command sends an ephemeral message, which can be seen only by the
     * sender of the message and the bot
    */
    std::optional<bool> isEphemeral { };
};

TGBOT_API void from_json(const nlohmann::json& json, BotCommand& value);
TGBOT_API void to_json(nlohmann::json& json, const BotCommand& value);

} // namespace TgBot
