// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct User;

/**
 * @brief This object contains information about changes to a user payment subscription toward the
 * current bot.
 */
struct BotSubscriptionUpdated {
    using Ptr = std::shared_ptr<BotSubscriptionUpdated>;

    /**
     * @brief User who subscribed for payments toward the bot
    */
    std::shared_ptr<User> user { };

    /**
     * @brief Bot-specified invoice payload
    */
    std::string invoicePayload { };

    /**
     * @brief The new state of the subscription. Currently, it can be one of “canceled” if the user
     * canceled the subscription, “active” if the user re-enabled a previously canceled
     * subscription, or “failed” if payment for the subscription failed.
    */
    std::string state { };
};

TGBOT_API void from_json(const nlohmann::json& json, BotSubscriptionUpdated& value);
TGBOT_API void to_json(nlohmann::json& json, const BotSubscriptionUpdated& value);

} // namespace TgBot
