// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>

namespace TgBot {

/**
 * @brief Represents the rights of a business bot.
 */
struct BusinessBotRights {
    using Ptr = std::shared_ptr<BusinessBotRights>;

    /**
     * @brief Optional. True, if the bot can send and edit messages in the private chats that had
     * incoming messages in the last 24 hours
    */
    std::optional<bool> canReply { };

    /**
     * @brief Optional. True, if the bot can mark incoming private messages as read
    */
    std::optional<bool> canReadMessages { };

    /**
     * @brief Optional. True, if the bot can delete messages sent by the bot
    */
    std::optional<bool> canDeleteSentMessages { };

    /**
     * @brief Optional. True, if the bot can delete all private messages in managed chats
    */
    std::optional<bool> canDeleteAllMessages { };

    /**
     * @brief Optional. True, if the bot can edit the first and last name of the business account
    */
    std::optional<bool> canEditName { };

    /**
     * @brief Optional. True, if the bot can edit the bio of the business account
    */
    std::optional<bool> canEditBio { };

    /**
     * @brief Optional. True, if the bot can edit the profile photo of the business account
    */
    std::optional<bool> canEditProfilePhoto { };

    /**
     * @brief Optional. True, if the bot can edit the username of the business account
    */
    std::optional<bool> canEditUsername { };

    /**
     * @brief Optional. True, if the bot can change the privacy settings pertaining to gifts for the
     * business account
    */
    std::optional<bool> canChangeGiftSettings { };

    /**
     * @brief Optional. True, if the bot can view gifts and the amount of Telegram Stars owned by the
     * business account
    */
    std::optional<bool> canViewGiftsAndStars { };

    /**
     * @brief Optional. True, if the bot can convert regular gifts owned by the business account to
     * Telegram Stars
    */
    std::optional<bool> canConvertGiftsToStars { };

    /**
     * @brief Optional. True, if the bot can transfer and upgrade gifts owned by the business account
    */
    std::optional<bool> canTransferAndUpgradeGifts { };

    /**
     * @brief Optional. True, if the bot can transfer Telegram Stars received by the business account
     * to its own account, or use them to upgrade and transfer gifts
    */
    std::optional<bool> canTransferStars { };

    /**
     * @brief Optional. True, if the bot can post, edit and delete stories on behalf of the business
     * account
    */
    std::optional<bool> canManageStories { };
};

TGBOT_API void from_json(const nlohmann::json& json, BusinessBotRights& value);
TGBOT_API void to_json(nlohmann::json& json, const BusinessBotRights& value);

} // namespace TgBot
