// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>
#include <vector>

namespace TgBot {

struct BusinessOpeningHoursInterval;

/**
 * @brief Describes the opening hours of a business.
 */
struct BusinessOpeningHours {
    using Ptr = std::shared_ptr<BusinessOpeningHours>;

    /**
     * @brief Unique name of the time zone for which the opening hours are defined
    */
    std::string timeZoneName { };

    /**
     * @brief List of time intervals describing business opening hours
    */
    std::vector<std::shared_ptr<BusinessOpeningHoursInterval>> openingHours { };
};

TGBOT_API void from_json(const nlohmann::json& json, BusinessOpeningHours& value);
TGBOT_API void to_json(nlohmann::json& json, const BusinessOpeningHours& value);

} // namespace TgBot
