// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct Sticker;

/**
 * @brief Contains information about the start page settings of a Telegram Business account.
 */
struct BusinessIntro {
    using Ptr = std::shared_ptr<BusinessIntro>;

    /**
     * @brief Optional. Title text of the business intro
    */
    std::optional<std::string> title { };

    /**
     * @brief Optional. Message text of the business intro
    */
    std::optional<std::string> message { };

    /**
     * @brief Optional. Sticker of the business intro
    */
    std::shared_ptr<Sticker> sticker { };
};

TGBOT_API void from_json(const nlohmann::json& json, BusinessIntro& value);
TGBOT_API void to_json(nlohmann::json& json, const BusinessIntro& value);

} // namespace TgBot
