// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct MaybeInaccessibleMessage;
struct User;

/**
 * @brief This object represents an incoming callback query from a callback button in an inline
 * keyboard. If the button that originated the query was attached to a message sent by the bot,
 * the field message will be present. If the button was attached to a message sent via the bot
 * (in inline mode), the field inline_message_id will be present. Exactly one of the fields
 * data or game_short_name will be present.
 */
struct CallbackQuery {
    using Ptr = std::shared_ptr<CallbackQuery>;

    /**
     * @brief Unique identifier for this query
    */
    std::string id { };

    /**
     * @brief Sender
    */
    std::shared_ptr<User> from { };

    /**
     * @brief Optional. Message sent by the bot with the callback button that originated the query
    */
    std::shared_ptr<MaybeInaccessibleMessage> message { };

    /**
     * @brief Optional. Identifier of the message sent via the bot in inline mode, that originated the
     * query
    */
    std::optional<std::string> inlineMessageId { };

    /**
     * @brief Global identifier, uniquely corresponding to the chat to which the message with the
     * callback button was sent. Useful for high scores in games.
    */
    std::string chatInstance { };

    /**
     * @brief Optional. Data associated with the callback button. Be aware that the message originated
     * the query can contain no callback buttons with this data.
    */
    std::optional<std::string> data { };

    /**
     * @brief Optional. Short name of a Game to be returned, serves as the unique identifier for the
     * game
    */
    std::optional<std::string> gameShortName { };
};

TGBOT_API void from_json(const nlohmann::json& json, CallbackQuery& value);
TGBOT_API void to_json(nlohmann::json& json, const CallbackQuery& value);

} // namespace TgBot
