// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct User;

/**
 * @brief Represents a chat member that has some additional privileges.
 */
struct ChatMemberAdministrator {
    using Ptr = std::shared_ptr<ChatMemberAdministrator>;

    static TGBOT_API const std::string STATUS;

    /**
     * @brief The member's status in the chat, always “administrator”
    */
    std::string status { STATUS };

    /**
     * @brief Information about the user
    */
    std::shared_ptr<User> user { };

    /**
     * @brief True, if the bot is allowed to edit administrator privileges of that user
    */
    bool canBeEdited { };

    /**
     * @brief True, if the user's presence in the chat is hidden
    */
    bool isAnonymous { };

    /**
     * @brief True, if the administrator can access the chat event log, get boost list, see hidden
     * supergroup and channel members, report spam messages, ignore slow mode, and send
     * messages to the chat without paying Telegram Stars. Implied by any other administrator
     * privilege.
    */
    bool canManageChat { };

    /**
     * @brief True, if the administrator can delete messages of other users
    */
    bool canDeleteMessages { };

    /**
     * @brief True, if the administrator can manage video chats
    */
    bool canManageVideoChats { };

    /**
     * @brief True, if the administrator can restrict, ban or unban chat members, or access supergroup
     * statistics
    */
    bool canRestrictMembers { };

    /**
     * @brief True, if the administrator can add new administrators with a subset of their own
     * privileges or demote administrators that they have promoted, directly or indirectly
     * (promoted by administrators that were appointed by the user)
    */
    bool canPromoteMembers { };

    /**
     * @brief True, if the user is allowed to change the chat title, photo and other settings
    */
    bool canChangeInfo { };

    /**
     * @brief True, if the user is allowed to invite new users to the chat
    */
    bool canInviteUsers { };

    /**
     * @brief True, if the administrator can post stories to the chat
    */
    bool canPostStories { };

    /**
     * @brief True, if the administrator can edit stories posted by other users, post stories to the
     * chat page, pin chat stories, and access the chat's story archive
    */
    bool canEditStories { };

    /**
     * @brief True, if the administrator can delete stories posted by other users
    */
    bool canDeleteStories { };

    /**
     * @brief Optional. True, if the administrator can post messages in the channel, approve suggested
     * posts, or access channel statistics; for channels only
    */
    std::optional<bool> canPostMessages { };

    /**
     * @brief Optional. True, if the administrator can edit messages of other users and can pin
     * messages; for channels only
    */
    std::optional<bool> canEditMessages { };

    /**
     * @brief Optional. True, if the user is allowed to pin messages; for groups and supergroups only
    */
    std::optional<bool> canPinMessages { };

    /**
     * @brief Optional. True, if the user is allowed to create, rename, close, and reopen forum
     * topics; for supergroups only
    */
    std::optional<bool> canManageTopics { };

    /**
     * @brief Optional. True, if the administrator can manage direct messages of the channel and
     * decline suggested posts; for channels only
    */
    std::optional<bool> canManageDirectMessages { };

    /**
     * @brief Optional. True, if the administrator can edit the tags of regular members; for groups
     * and supergroups only. If omitted, defaults to the value of can_pin_messages.
    */
    std::optional<bool> canManageTags { };

    /**
     * @brief Optional. Custom title for this user
    */
    std::optional<std::string> customTitle { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatMemberAdministrator& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatMemberAdministrator& value);

} // namespace TgBot
