// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct ChatMemberAdministrator;
struct ChatMemberBanned;
struct ChatMemberLeft;
struct ChatMemberMember;
struct ChatMemberOwner;
struct ChatMemberRestricted;

/**
 * @brief This object contains information about one member of a chat. Currently, the following 6
 * types of chat members are supported: ChatMemberOwner ChatMemberAdministrator
 * ChatMemberMember ChatMemberRestricted ChatMemberLeft ChatMemberBanned
 */
struct ChatMember {
    using Ptr = std::shared_ptr<ChatMember>;

    std::variant<std::shared_ptr<ChatMemberOwner>, std::shared_ptr<ChatMemberAdministrator>,
                 std::shared_ptr<ChatMemberMember>, std::shared_ptr<ChatMemberRestricted>,
                 std::shared_ptr<ChatMemberLeft>, std::shared_ptr<ChatMemberBanned>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, ChatMember& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatMember& value);

} // namespace TgBot
