// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct Chat;
struct ChatBoostSource;

/**
 * @brief This object represents a boost removed from a chat.
 */
struct ChatBoostRemoved {
    using Ptr = std::shared_ptr<ChatBoostRemoved>;

    /**
     * @brief Chat which was boosted
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Unique identifier of the boost
    */
    std::string boostId { };

    /**
     * @brief Point in time (Unix timestamp) when the boost was removed
    */
    std::int32_t removeDate { };

    /**
     * @brief Source of the removed boost
    */
    std::shared_ptr<ChatBoostSource> source { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatBoostRemoved& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatBoostRemoved& value);

} // namespace TgBot
