// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

/**
 * @brief This object represents a service message about a user boosting a chat.
 */
struct ChatBoostAdded {
    using Ptr = std::shared_ptr<ChatBoostAdded>;

    /**
     * @brief Number of boosts added by the user
    */
    std::int32_t boostCount { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatBoostAdded& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatBoostAdded& value);

} // namespace TgBot
