// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct User;

/**
 * @brief Represents a chat member that is under certain restrictions in the chat. Supergroups only.
 */
struct ChatMemberRestricted {
    using Ptr = std::shared_ptr<ChatMemberRestricted>;

    static TGBOT_API const std::string STATUS;

    /**
     * @brief The member's status in the chat, always “restricted”
    */
    std::string status { STATUS };

    /**
     * @brief Optional. Tag of the member
    */
    std::optional<std::string> tag { };

    /**
     * @brief Information about the user
    */
    std::shared_ptr<User> user { };

    /**
     * @brief True, if the user is a member of the chat at the moment of the request
    */
    bool isMember { };

    /**
     * @brief True, if the user is allowed to send text messages, rich messages, contacts, giveaways,
     * giveaway winners, invoices, locations and venues
    */
    bool canSendMessages { };

    /**
     * @brief True, if the user is allowed to send audios
    */
    bool canSendAudios { };

    /**
     * @brief True, if the user is allowed to send documents
    */
    bool canSendDocuments { };

    /**
     * @brief True, if the user is allowed to send photos
    */
    bool canSendPhotos { };

    /**
     * @brief True, if the user is allowed to send videos
    */
    bool canSendVideos { };

    /**
     * @brief True, if the user is allowed to send video notes
    */
    bool canSendVideoNotes { };

    /**
     * @brief True, if the user is allowed to send voice notes
    */
    bool canSendVoiceNotes { };

    /**
     * @brief True, if the user is allowed to send polls and checklists
    */
    bool canSendPolls { };

    /**
     * @brief True, if the user is allowed to send animations, games, stickers and use inline bots
    */
    bool canSendOtherMessages { };

    /**
     * @brief True, if the user is allowed to add web page previews to their messages
    */
    bool canAddWebPagePreviews { };

    /**
     * @brief True, if the user is allowed to react to messages
    */
    bool canReactToMessages { };

    /**
     * @brief True, if the user is allowed to edit their own tag
    */
    bool canEditTag { };

    /**
     * @brief True, if the user is allowed to change the chat title, photo and other settings
    */
    bool canChangeInfo { };

    /**
     * @brief True, if the user is allowed to invite new users to the chat
    */
    bool canInviteUsers { };

    /**
     * @brief True, if the user is allowed to pin messages
    */
    bool canPinMessages { };

    /**
     * @brief True, if the user is allowed to create forum topics
    */
    bool canManageTopics { };

    /**
     * @brief Date when restrictions will be lifted for this user; Unix time. If 0, then the user is
     * restricted forever.
    */
    std::int32_t untilDate { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatMemberRestricted& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatMemberRestricted& value);

} // namespace TgBot
