// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct User;

/**
 * @brief Represents a chat member that owns the chat and has all administrator privileges.
 */
struct ChatMemberOwner {
    using Ptr = std::shared_ptr<ChatMemberOwner>;

    static TGBOT_API const std::string STATUS;

    /**
     * @brief The member's status in the chat, always “creator”
    */
    std::string status { STATUS };

    /**
     * @brief Information about the user
    */
    std::shared_ptr<User> user { };

    /**
     * @brief True, if the user's presence in the chat is hidden
    */
    bool isAnonymous { };

    /**
     * @brief Optional. Custom title for this user
    */
    std::optional<std::string> customTitle { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatMemberOwner& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatMemberOwner& value);

} // namespace TgBot
