// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct User;

/**
 * @brief Represents an invite link for a chat.
 */
struct ChatInviteLink {
    using Ptr = std::shared_ptr<ChatInviteLink>;

    /**
     * @brief The invite link. If the link was created by another chat administrator, then the second
     * part of the link will be replaced with “…”.
    */
    std::string inviteLink { };

    /**
     * @brief Creator of the link
    */
    std::shared_ptr<User> creator { };

    /**
     * @brief True, if users joining the chat via the link need to be approved by chat administrators
    */
    bool createsJoinRequest { };

    /**
     * @brief True, if the link is primary
    */
    bool isPrimary { };

    /**
     * @brief True, if the link is revoked
    */
    bool isRevoked { };

    /**
     * @brief Optional. Invite link name
    */
    std::optional<std::string> name { };

    /**
     * @brief Optional. Point in time (Unix timestamp) when the link will expire or has been expired
    */
    std::optional<std::int32_t> expireDate { };

    /**
     * @brief Optional. The maximum number of users that can be members of the chat simultaneously
     * after joining the chat via this invite link; 1-99999
    */
    std::optional<std::int32_t> memberLimit { };

    /**
     * @brief Optional. Number of pending join requests created using this link
    */
    std::optional<std::int32_t> pendingJoinRequestCount { };

    /**
     * @brief Optional. The number of seconds the subscription will be active for before the next
     * payment
    */
    std::optional<std::int32_t> subscriptionPeriod { };

    /**
     * @brief Optional. The amount of Telegram Stars a user must pay initially and after each
     * subsequent subscription period to be a member of the chat using the link
    */
    std::optional<std::int32_t> subscriptionPrice { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatInviteLink& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatInviteLink& value);

} // namespace TgBot
