// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents a chat.
 */
struct Chat {
    using Ptr = std::shared_ptr<Chat>;

    enum class Type { Private, Group, Supergroup, Channel };

    /**
     * @brief Unique identifier for this chat. This number may have more than 32 significant bits and
     * some programming languages may have difficulty/silent defects in interpreting it. But it
     * has at most 52 significant bits, so a signed 64-bit integer or double-precision float
     * type are safe for storing this identifier.
    */
    std::int64_t id { };

    /**
     * @brief Type of the chat, can be either “private”, “group”, “supergroup” or “channel”
    */
    Type type { };

    /**
     * @brief Optional. Title, for supergroups, channels and group chats
    */
    std::optional<std::string> title { };

    /**
     * @brief Optional. Username, for private chats, supergroups and channels if available
    */
    std::optional<std::string> username { };

    /**
     * @brief Optional. First name of the other party in a private chat
    */
    std::optional<std::string> firstName { };

    /**
     * @brief Optional. Last name of the other party in a private chat
    */
    std::optional<std::string> lastName { };

    /**
     * @brief Optional. True, if the supergroup chat is a forum (has topics enabled)
    */
    std::optional<bool> isForum { };

    /**
     * @brief Optional. True, if the chat is the direct messages chat of a channel
    */
    std::optional<bool> isDirectMessages { };
};

TGBOT_API void from_json(const nlohmann::json& json, Chat::Type& value);
TGBOT_API void to_json(nlohmann::json& json, const Chat::Type& value);

TGBOT_API void from_json(const nlohmann::json& json, Chat& value);
TGBOT_API void to_json(nlohmann::json& json, const Chat& value);

} // namespace TgBot
