// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct Chat;
struct ChatInviteLink;
struct User;

/**
 * @brief Represents a join request sent to a chat.
 */
struct ChatJoinRequest {
    using Ptr = std::shared_ptr<ChatJoinRequest>;

    /**
     * @brief Chat to which the request was sent
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief User that sent the join request
    */
    std::shared_ptr<User> from { };

    /**
     * @brief Identifier of a private chat with the user who sent the join request. This number may
     * have more than 32 significant bits and some programming languages may have
     * difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so
     * a 64-bit integer or double-precision float type are safe for storing this identifier.
     * The bot can use this identifier for 5 minutes to send messages until the join request is
     * processed, assuming no other administrator contacted the user.
    */
    std::int64_t userChatId { };

    /**
     * @brief Date the request was sent in Unix time
    */
    std::int32_t date { };

    /**
     * @brief Optional. Bio of the user
    */
    std::optional<std::string> bio { };

    /**
     * @brief Optional. Chat invite link that was used by the user to send the join request
    */
    std::shared_ptr<ChatInviteLink> inviteLink { };

    /**
     * @brief Optional. Identifier of the join request query; for bots assigned to process join
     * requests only. If present, then the bot must call sendChatJoinRequestWebApp or directly
     * call answerChatJoinRequestQuery within 10 seconds.
    */
    std::optional<std::string> queryId { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatJoinRequest& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatJoinRequest& value);

} // namespace TgBot
