// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

struct Chat;
struct ChatBoost;

/**
 * @brief This object represents a boost added to a chat or changed.
 */
struct ChatBoostUpdated {
    using Ptr = std::shared_ptr<ChatBoostUpdated>;

    /**
     * @brief Chat which was boosted
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Information about the chat boost
    */
    std::shared_ptr<ChatBoost> boost { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChatBoostUpdated& value);
TGBOT_API void to_json(nlohmann::json& json, const ChatBoostUpdated& value);

} // namespace TgBot
