// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct ChecklistTask;
struct MessageEntity;

/**
 * @brief Describes a checklist.
 */
struct Checklist {
    using Ptr = std::shared_ptr<Checklist>;

    /**
     * @brief Title of the checklist
    */
    std::string title { };

    /**
     * @brief Optional. Special entities that appear in the checklist title
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> titleEntities { };

    /**
     * @brief List of tasks in the checklist
    */
    std::vector<std::shared_ptr<ChecklistTask>> tasks { };

    /**
     * @brief Optional. True, if users other than the creator of the list can add tasks to the list
    */
    std::optional<bool> othersCanAddTasks { };

    /**
     * @brief Optional. True, if users other than the creator of the list can mark tasks as done or
     * not done
    */
    std::optional<bool> othersCanMarkTasksAsDone { };
};

TGBOT_API void from_json(const nlohmann::json& json, Checklist& value);
TGBOT_API void to_json(nlohmann::json& json, const Checklist& value);

} // namespace TgBot
