// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct Location;
struct User;

/**
 * @brief Represents a result of an inline query that was chosen by the user and sent to their chat
 * partner.
 */
struct ChosenInlineResult {
    using Ptr = std::shared_ptr<ChosenInlineResult>;

    /**
     * @brief The unique identifier for the result that was chosen
    */
    std::string resultId { };

    /**
     * @brief The user that chose the result
    */
    std::shared_ptr<User> from { };

    /**
     * @brief Optional. Sender location, only for bots that require user location
    */
    std::shared_ptr<Location> location { };

    /**
     * @brief Optional. Identifier of the sent inline message. Available only if there is an inline
     * keyboard attached to the message. Will be also received in callback queries and can be
     * used to edit the message.
    */
    std::optional<std::string> inlineMessageId { };

    /**
     * @brief The query that was used to obtain the result
    */
    std::string query { };
};

TGBOT_API void from_json(const nlohmann::json& json, ChosenInlineResult& value);
TGBOT_API void to_json(nlohmann::json& json, const ChosenInlineResult& value);

} // namespace TgBot
