// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Represents a community (a group of chats).
 */
struct Community {
    using Ptr = std::shared_ptr<Community>;

    /**
     * @brief Unique identifier for this community. This number may have more than 32 significant bits
     * and some programming languages may have difficulty/silent defects in interpreting it.
     * But it has at most 52 significant bits, so a signed 64-bit integer or double-precision
     * float type are safe for storing this identifier.
    */
    std::int64_t id { };

    /**
     * @brief Name of the community
    */
    std::string name { };
};

TGBOT_API void from_json(const nlohmann::json& json, Community& value);
TGBOT_API void to_json(nlohmann::json& json, const Community& value);

} // namespace TgBot
