// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief This object represents an inline keyboard button that copies specified text to the
 * clipboard.
 */
struct CopyTextButton {
    using Ptr = std::shared_ptr<CopyTextButton>;

    /**
     * @brief The text to be copied to the clipboard; 1-256 characters
    */
    std::string text { };
};

TGBOT_API void from_json(const nlohmann::json& json, CopyTextButton& value);
TGBOT_API void to_json(nlohmann::json& json, const CopyTextButton& value);

} // namespace TgBot
