// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief This object represents an animated emoji that displays a random value.
 */
struct Dice {
    using Ptr = std::shared_ptr<Dice>;

    /**
     * @brief Emoji on which the dice throw animation is based
    */
    std::string emoji { };

    /**
     * @brief Value of the dice, 1-6 for “”, “” and “” base emoji, 1-5 for “” and “” base emoji, 1-64
     * for “” base emoji
    */
    std::int32_t value { };
};

TGBOT_API void from_json(const nlohmann::json& json, Dice& value);
TGBOT_API void to_json(nlohmann::json& json, const Dice& value);

} // namespace TgBot
