// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct PassportFile;

/**
 * @brief Describes documents or other Telegram Passport elements shared with the bot by the user.
 */
struct EncryptedPassportElement {
    using Ptr = std::shared_ptr<EncryptedPassportElement>;

    /**
     * @brief Element type. One of “personal_details”, “passport”, “driver_license”, “identity_card”,
     * “internal_passport”, “address”, “utility_bill”, “bank_statement”, “rental_agreement”,
     * “passport_registration”, “temporary_registration”, “phone_number”, “email”.
    */
    std::string type { };

    /**
     * @brief Optional. Base64-encoded encrypted Telegram Passport element data provided by the user;
     * available only for “personal_details”, “passport”, “driver_license”, “identity_card”,
     * “internal_passport” and “address” types. Can be decrypted and verified using the
     * accompanying EncryptedCredentials.
    */
    std::optional<std::string> data { };

    /**
     * @brief Optional. User's verified phone number; available only for “phone_number” type
    */
    std::optional<std::string> phoneNumber { };

    /**
     * @brief Optional. User's verified email address; available only for “email” type
    */
    std::optional<std::string> email { };

    /**
     * @brief Optional. Array of encrypted files with documents provided by the user; available only
     * for “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration” and
     * “temporary_registration” types. Files can be decrypted and verified using the
     * accompanying EncryptedCredentials.
    */
    std::optional<std::vector<std::shared_ptr<PassportFile>>> files { };

    /**
     * @brief Optional. Encrypted file with the front side of the document, provided by the user;
     * available only for “passport”, “driver_license”, “identity_card” and
     * “internal_passport”. The file can be decrypted and verified using the accompanying
     * EncryptedCredentials.
    */
    std::shared_ptr<PassportFile> frontSide { };

    /**
     * @brief Optional. Encrypted file with the reverse side of the document, provided by the user;
     * available only for “driver_license” and “identity_card”. The file can be decrypted and
     * verified using the accompanying EncryptedCredentials.
    */
    std::shared_ptr<PassportFile> reverseSide { };

    /**
     * @brief Optional. Encrypted file with the selfie of the user holding a document, provided by the
     * user; available if requested for “passport”, “driver_license”, “identity_card” and
     * “internal_passport”. The file can be decrypted and verified using the accompanying
     * EncryptedCredentials.
    */
    std::shared_ptr<PassportFile> selfie { };

    /**
     * @brief Optional. Array of encrypted files with translated versions of documents provided by the
     * user; available if requested for “passport”, “driver_license”, “identity_card”,
     * “internal_passport”, “utility_bill”, “bank_statement”, “rental_agreement”,
     * “passport_registration” and “temporary_registration” types. Files can be decrypted and
     * verified using the accompanying EncryptedCredentials.
    */
    std::optional<std::vector<std::shared_ptr<PassportFile>>> translation { };

    /**
     * @brief Base64-encoded element hash for using in PassportElementErrorUnspecified
    */
    std::string hash { };
};

TGBOT_API void from_json(const nlohmann::json& json, EncryptedPassportElement& value);
TGBOT_API void to_json(nlohmann::json& json, const EncryptedPassportElement& value);

} // namespace TgBot
