// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents a file ready to be downloaded. The file can be downloaded via the
 * link https://api.telegram.org/file/bot<token>/<file_path>. It is guaranteed that the link
 * will be valid for at least 1 hour. When the link expires, a new one can be requested by
 * calling getFile.
 */
struct File {
    using Ptr = std::shared_ptr<File>;

    /**
     * @brief Identifier for this file, which can be used to download or reuse the file
    */
    std::string fileId { };

    /**
     * @brief Unique identifier for this file, which is supposed to be the same over time and for
     * different bots. Can't be used to download or reuse the file.
    */
    std::string fileUniqueId { };

    /**
     * @brief Optional. File size in bytes. It can be bigger than 2^31 and some programming languages
     * may have difficulty/silent defects in interpreting it. But it has at most 52 significant
     * bits, so a signed 64-bit integer or double-precision float type are safe for storing
     * this value.
    */
    std::optional<std::int64_t> fileSize { };

    /**
     * @brief Optional. File path. Use https://api.telegram.org/file/bot<token>/<file_path> to get the
     * file.
    */
    std::optional<std::string> filePath { };
};

TGBOT_API void from_json(const nlohmann::json& json, File& value);
TGBOT_API void to_json(nlohmann::json& json, const File& value);

} // namespace TgBot
