// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief Upon receiving a message with this object, Telegram clients will display a reply interface
 * to the user (act as if the user has selected the bot's message and tapped 'Reply'). This can
 * be extremely useful if you want to create user-friendly step-by-step interfaces without
 * having to sacrifice privacy mode. Not supported in channels and for messages sent on behalf
 * of a user account.
 */
struct ForceReply {
    using Ptr = std::shared_ptr<ForceReply>;

    /**
     * @brief Shows reply interface to the user, as if they manually selected the bot's message and
     * tapped 'Reply'
    */
    bool forceReply { };

    /**
     * @brief Optional. The placeholder to be shown in the input field when the reply is active; 1-64
     * characters
    */
    std::optional<std::string> inputFieldPlaceholder { };

    /**
     * @brief Optional. Use this parameter if you want to force reply from specific users only.
     * Targets: 1) users that are @mentioned in the text of the Message object; 2) if the bot's
     * message is a reply to a message in the same chat and forum topic, sender of the original
     * message.
    */
    std::optional<bool> selective { };
};

TGBOT_API void from_json(const nlohmann::json& json, ForceReply& value);
TGBOT_API void to_json(nlohmann::json& json, const ForceReply& value);

} // namespace TgBot
