// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents a service message about an edited forum topic.
 */
struct ForumTopicEdited {
    using Ptr = std::shared_ptr<ForumTopicEdited>;

    /**
     * @brief Optional. New name of the topic, if it was edited
    */
    std::optional<std::string> name { };

    /**
     * @brief Optional. New identifier of the custom emoji shown as the topic icon, if it was edited;
     * an empty string if the icon was removed
    */
    std::optional<std::string> iconCustomEmojiId { };
};

TGBOT_API void from_json(const nlohmann::json& json, ForumTopicEdited& value);
TGBOT_API void to_json(nlohmann::json& json, const ForumTopicEdited& value);

} // namespace TgBot
