// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

/**
 * @brief This object represents a service message about a forum topic reopened in the chat. Currently
 * holds no information.
 */
struct ForumTopicReopened {
    using Ptr = std::shared_ptr<ForumTopicReopened>;
};

TGBOT_API void from_json(const nlohmann::json& json, ForumTopicReopened& value);
TGBOT_API void to_json(nlohmann::json& json, const ForumTopicReopened& value);

} // namespace TgBot
