// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct Animation;
struct MessageEntity;
struct PhotoSize;

/**
 * @brief This object represents a game. Use BotFather to create and edit games, their short names
 * will act as unique identifiers.
 */
struct Game {
    using Ptr = std::shared_ptr<Game>;

    /**
     * @brief Title of the game
    */
    std::string title { };

    /**
     * @brief Description of the game
    */
    std::string description { };

    /**
     * @brief Photo that will be displayed in the game message in chats
    */
    std::vector<std::shared_ptr<PhotoSize>> photo { };

    /**
     * @brief Optional. Brief description of the game or high scores included in the game message. Can
     * be automatically edited to include current high scores for the game when the bot calls
     * setGameScore, or manually edited using editMessageText. 0-4096 characters.
    */
    std::optional<std::string> text { };

    /**
     * @brief Optional. Special entities that appear in text, such as usernames, URLs, bot commands,
     * etc.
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> textEntities { };

    /**
     * @brief Optional. Animation that will be displayed in the game message in chats. Upload via
     * BotFather.
    */
    std::shared_ptr<Animation> animation { };
};

TGBOT_API void from_json(const nlohmann::json& json, Game& value);
TGBOT_API void to_json(nlohmann::json& json, const Game& value);

} // namespace TgBot
