// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

struct Chat;

/**
 * @brief This object describes a message that was deleted or is otherwise inaccessible to the bot.
 */
struct InaccessibleMessage {
    using Ptr = std::shared_ptr<InaccessibleMessage>;

    /**
     * @brief Chat the message belonged to
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Unique message identifier inside the chat
    */
    std::int32_t messageId { };

    /**
     * @brief Always 0. The field can be used to differentiate regular and inaccessible messages.
    */
    std::int32_t date { };
};

TGBOT_API void from_json(const nlohmann::json& json, InaccessibleMessage& value);
TGBOT_API void to_json(nlohmann::json& json, const InaccessibleMessage& value);

} // namespace TgBot
