// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct InlineKeyboardMarkup;
struct InputMessageContent;
struct MessageEntity;

/**
 * @brief Represents a link to a file. By default, this file will be sent by the user with an optional
 * caption. Alternatively, you can use input_message_content to send a message with the
 * specified content instead of the file. Currently, only .PDF and .ZIP files can be sent using
 * this method.
 */
struct InlineQueryResultDocument {
    using Ptr = std::shared_ptr<InlineQueryResultDocument>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the result, must be document
    */
    std::string type { TYPE };

    /**
     * @brief Unique identifier for this result, 1-64 bytes
    */
    std::string id { };

    /**
     * @brief Title for the result
    */
    std::string title { };

    /**
     * @brief Optional. Caption of the document to be sent, 0-1024 characters after entities parsing
    */
    std::optional<std::string> caption { };

    /**
     * @brief Optional. Mode for parsing entities in the document caption. See formatting options for
     * more details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the caption, which can be specified
     * instead of parse_mode
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> captionEntities { };

    /**
     * @brief A valid URL for the file
    */
    std::string documentUrl { };

    /**
     * @brief MIME type of the content of the file, either “application/pdf” or “application/zip”
    */
    std::string mimeType { };

    /**
     * @brief Optional. Short description of the result
    */
    std::optional<std::string> description { };

    /**
     * @brief Optional. Inline keyboard attached to the message
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };

    /**
     * @brief Optional. Content of the message to be sent instead of the file
    */
    std::shared_ptr<InputMessageContent> inputMessageContent { };

    /**
     * @brief Optional. URL of the thumbnail (JPEG only) for the file
    */
    std::optional<std::string> thumbnailUrl { };

    /**
     * @brief Optional. Thumbnail width
    */
    std::optional<std::int32_t> thumbnailWidth { };

    /**
     * @brief Optional. Thumbnail height
    */
    std::optional<std::int32_t> thumbnailHeight { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultDocument& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultDocument& value);

} // namespace TgBot
