// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct InlineKeyboardMarkup;
struct InputMessageContent;

/**
 * @brief Represents a link to a sticker stored on the Telegram servers. By default, this sticker will
 * be sent by the user. Alternatively, you can use input_message_content to send a message with
 * the specified content instead of the sticker.
 */
struct InlineQueryResultCachedSticker {
    using Ptr = std::shared_ptr<InlineQueryResultCachedSticker>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the result, must be sticker
    */
    std::string type { TYPE };

    /**
     * @brief Unique identifier for this result, 1-64 bytes
    */
    std::string id { };

    /**
     * @brief A valid file identifier of the sticker
    */
    std::string stickerFileId { };

    /**
     * @brief Optional. Inline keyboard attached to the message
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };

    /**
     * @brief Optional. Content of the message to be sent instead of the sticker
    */
    std::shared_ptr<InputMessageContent> inputMessageContent { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultCachedSticker& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultCachedSticker& value);

} // namespace TgBot
