// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct InlineQueryResultArticle;
struct InlineQueryResultAudio;
struct InlineQueryResultCachedAudio;
struct InlineQueryResultCachedDocument;
struct InlineQueryResultCachedGif;
struct InlineQueryResultCachedMpeg4Gif;
struct InlineQueryResultCachedPhoto;
struct InlineQueryResultCachedSticker;
struct InlineQueryResultCachedVideo;
struct InlineQueryResultCachedVoice;
struct InlineQueryResultContact;
struct InlineQueryResultDocument;
struct InlineQueryResultGame;
struct InlineQueryResultGif;
struct InlineQueryResultLocation;
struct InlineQueryResultMpeg4Gif;
struct InlineQueryResultPhoto;
struct InlineQueryResultVenue;
struct InlineQueryResultVideo;
struct InlineQueryResultVoice;

/**
 * @brief This object represents one result of an inline query. Telegram clients currently support
 * results of the following 20 types: InlineQueryResultCachedAudio
 * InlineQueryResultCachedDocument InlineQueryResultCachedGif InlineQueryResultCachedMpeg4Gif
 * InlineQueryResultCachedPhoto InlineQueryResultCachedSticker InlineQueryResultCachedVideo
 * InlineQueryResultCachedVoice InlineQueryResultArticle InlineQueryResultAudio
 * InlineQueryResultContact InlineQueryResultGame InlineQueryResultDocument
 * InlineQueryResultGif InlineQueryResultLocation InlineQueryResultMpeg4Gif
 * InlineQueryResultPhoto InlineQueryResultVenue InlineQueryResultVideo InlineQueryResultVoice
 * Note: All URLs passed in inline query results will be available to end users and therefore
 * must be assumed to be public.
 */
struct InlineQueryResult {
    using Ptr = std::shared_ptr<InlineQueryResult>;

    std::variant<std::shared_ptr<InlineQueryResultCachedAudio>, std::shared_ptr<InlineQueryResultCachedDocument>,
                 std::shared_ptr<InlineQueryResultCachedGif>, std::shared_ptr<InlineQueryResultCachedMpeg4Gif>,
                 std::shared_ptr<InlineQueryResultCachedPhoto>, std::shared_ptr<InlineQueryResultCachedSticker>,
                 std::shared_ptr<InlineQueryResultCachedVideo>, std::shared_ptr<InlineQueryResultCachedVoice>,
                 std::shared_ptr<InlineQueryResultArticle>, std::shared_ptr<InlineQueryResultAudio>,
                 std::shared_ptr<InlineQueryResultContact>, std::shared_ptr<InlineQueryResultGame>,
                 std::shared_ptr<InlineQueryResultDocument>, std::shared_ptr<InlineQueryResultGif>,
                 std::shared_ptr<InlineQueryResultLocation>, std::shared_ptr<InlineQueryResultMpeg4Gif>,
                 std::shared_ptr<InlineQueryResultPhoto>, std::shared_ptr<InlineQueryResultVenue>,
                 std::shared_ptr<InlineQueryResultVideo>, std::shared_ptr<InlineQueryResultVoice>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResult& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResult& value);

} // namespace TgBot
