// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct InlineKeyboardMarkup;
struct InputMessageContent;
struct MessageEntity;

/**
 * @brief Represents a link to a video animation (H.264/MPEG-4 AVC video without sound). By default,
 * this animated MPEG-4 file will be sent by the user with optional caption. Alternatively, you
 * can use input_message_content to send a message with the specified content instead of the
 * animation.
 */
struct InlineQueryResultMpeg4Gif {
    using Ptr = std::shared_ptr<InlineQueryResultMpeg4Gif>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the result, must be mpeg4_gif
    */
    std::string type { TYPE };

    /**
     * @brief Unique identifier for this result, 1-64 bytes
    */
    std::string id { };

    /**
     * @brief A valid URL for the MPEG4 file
    */
    std::string mpeg4Url { };

    /**
     * @brief Optional. Video width
    */
    std::optional<std::int32_t> mpeg4Width { };

    /**
     * @brief Optional. Video height
    */
    std::optional<std::int32_t> mpeg4Height { };

    /**
     * @brief Optional. Video duration in seconds
    */
    std::optional<std::int32_t> mpeg4Duration { };

    /**
     * @brief URL of the static (JPEG or GIF) or animated (MPEG4) thumbnail for the result
    */
    std::string thumbnailUrl { };

    /**
     * @brief Optional. MIME type of the thumbnail, must be one of “image/jpeg”, “image/gif”, or
     * “video/mp4”. Defaults to “image/jpeg”.
    */
    std::optional<std::string> thumbnailMimeType { };

    /**
     * @brief Optional. Title for the result
    */
    std::optional<std::string> title { };

    /**
     * @brief Optional. Caption of the MPEG-4 file to be sent, 0-1024 characters after entities
     * parsing
    */
    std::optional<std::string> caption { };

    /**
     * @brief Optional. Mode for parsing entities in the caption. See formatting options for more
     * details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the caption, which can be specified
     * instead of parse_mode
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> captionEntities { };

    /**
     * @brief Optional. Pass True if the caption must be shown above the message media
    */
    std::optional<bool> showCaptionAboveMedia { };

    /**
     * @brief Optional. Inline keyboard attached to the message
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };

    /**
     * @brief Optional. Content of the message to be sent instead of the video animation
    */
    std::shared_ptr<InputMessageContent> inputMessageContent { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultMpeg4Gif& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultMpeg4Gif& value);

} // namespace TgBot
