// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct InlineKeyboardMarkup;
struct InputMessageContent;
struct MessageEntity;

/**
 * @brief Represents a link to a file stored on the Telegram servers. By default, this file will be
 * sent by the user with an optional caption. Alternatively, you can use input_message_content
 * to send a message with the specified content instead of the file.
 */
struct InlineQueryResultCachedDocument {
    using Ptr = std::shared_ptr<InlineQueryResultCachedDocument>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the result, must be document
    */
    std::string type { TYPE };

    /**
     * @brief Unique identifier for this result, 1-64 bytes
    */
    std::string id { };

    /**
     * @brief Title for the result
    */
    std::string title { };

    /**
     * @brief A valid file identifier for the file
    */
    std::string documentFileId { };

    /**
     * @brief Optional. Short description of the result
    */
    std::optional<std::string> description { };

    /**
     * @brief Optional. Caption of the document to be sent, 0-1024 characters after entities parsing
    */
    std::optional<std::string> caption { };

    /**
     * @brief Optional. Mode for parsing entities in the document caption. See formatting options for
     * more details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the caption, which can be specified
     * instead of parse_mode
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> captionEntities { };

    /**
     * @brief Optional. Inline keyboard attached to the message
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };

    /**
     * @brief Optional. Content of the message to be sent instead of the file
    */
    std::shared_ptr<InputMessageContent> inputMessageContent { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultCachedDocument& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultCachedDocument& value);

} // namespace TgBot
