// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct InlineKeyboardMarkup;
struct InputMessageContent;

/**
 * @brief Represents a contact with a phone number. By default, this contact will be sent by the user.
 * Alternatively, you can use input_message_content to send a message with the specified
 * content instead of the contact.
 */
struct InlineQueryResultContact {
    using Ptr = std::shared_ptr<InlineQueryResultContact>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the result, must be contact
    */
    std::string type { TYPE };

    /**
     * @brief Unique identifier for this result, 1-64 Bytes
    */
    std::string id { };

    /**
     * @brief Contact's phone number
    */
    std::string phoneNumber { };

    /**
     * @brief Contact's first name
    */
    std::string firstName { };

    /**
     * @brief Optional. Contact's last name
    */
    std::optional<std::string> lastName { };

    /**
     * @brief Optional. Additional data about the contact in the form of a vCard, 0-2048 bytes
    */
    std::optional<std::string> vcard { };

    /**
     * @brief Optional. Inline keyboard attached to the message
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };

    /**
     * @brief Optional. Content of the message to be sent instead of the contact
    */
    std::shared_ptr<InputMessageContent> inputMessageContent { };

    /**
     * @brief Optional. Url of the thumbnail for the result
    */
    std::optional<std::string> thumbnailUrl { };

    /**
     * @brief Optional. Thumbnail width
    */
    std::optional<std::int32_t> thumbnailWidth { };

    /**
     * @brief Optional. Thumbnail height
    */
    std::optional<std::int32_t> thumbnailHeight { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultContact& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultContact& value);

} // namespace TgBot
