// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct InlineKeyboardMarkup;
struct InputMessageContent;
struct MessageEntity;

/**
 * @brief Represents a link to a page containing an embedded video player or a video file. By default,
 * this video file will be sent by the user with an optional caption. Alternatively, you can
 * use input_message_content to send a message with the specified content instead of the video.
 */
struct InlineQueryResultVideo {
    using Ptr = std::shared_ptr<InlineQueryResultVideo>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the result, must be video
    */
    std::string type { TYPE };

    /**
     * @brief Unique identifier for this result, 1-64 bytes
    */
    std::string id { };

    /**
     * @brief A valid URL for the embedded video player or video file
    */
    std::string videoUrl { };

    /**
     * @brief MIME type of the content of the video URL, “text/html” or “video/mp4”
    */
    std::string mimeType { };

    /**
     * @brief URL of the thumbnail (JPEG only) for the video
    */
    std::string thumbnailUrl { };

    /**
     * @brief Title for the result
    */
    std::string title { };

    /**
     * @brief Optional. Caption of the video to be sent, 0-1024 characters after entities parsing
    */
    std::optional<std::string> caption { };

    /**
     * @brief Optional. Mode for parsing entities in the video caption. See formatting options for
     * more details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the caption, which can be specified
     * instead of parse_mode
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> captionEntities { };

    /**
     * @brief Optional. Pass True if the caption must be shown above the message media
    */
    std::optional<bool> showCaptionAboveMedia { };

    /**
     * @brief Optional. Video width
    */
    std::optional<std::int32_t> videoWidth { };

    /**
     * @brief Optional. Video height
    */
    std::optional<std::int32_t> videoHeight { };

    /**
     * @brief Optional. Video duration in seconds
    */
    std::optional<std::int32_t> videoDuration { };

    /**
     * @brief Optional. Short description of the result
    */
    std::optional<std::string> description { };

    /**
     * @brief Optional. Inline keyboard attached to the message
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };

    /**
     * @brief Optional. Content of the message to be sent instead of the video. This field is required
     * if InlineQueryResultVideo is used to send an HTML-page as a result (e.g., a YouTube
     * video).
    */
    std::shared_ptr<InputMessageContent> inputMessageContent { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultVideo& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultVideo& value);

} // namespace TgBot
