// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct WebAppInfo;

/**
 * @brief This object represents a button to be shown above inline query results. You must use exactly
 * one of the optional fields.
 */
struct InlineQueryResultsButton {
    using Ptr = std::shared_ptr<InlineQueryResultsButton>;

    /**
     * @brief Label text on the button
    */
    std::string text { };

    /**
     * @brief Optional. Description of the Web App that will be launched when the user presses the
     * button. The Web App will be able to switch back to the inline mode using the method
     * switchInlineQuery inside the Web App.
    */
    std::shared_ptr<WebAppInfo> webApp { };

    /**
     * @brief Optional. Deep-linking parameter for the /start message sent to the bot when a user
     * presses the button. 1-64 characters, only A-Z, a-z, 0-9, _ and - are allowed.Example: An
     * inline bot that sends YouTube videos can ask the user to connect the bot to their
     * YouTube account to adapt search results accordingly. To do this, it displays a 'Connect
     * your YouTube account' button above the results, or even before showing any. The user
     * presses the button, switches to a private chat with the bot and, in doing so, passes a
     * start parameter that instructs the bot to return an OAuth link. Once done, the bot can
     * offer a switch_inline button so that the user can easily return to the chat where they
     * wanted to use the bot's inline capabilities.
    */
    std::optional<std::string> startParameter { };
};

TGBOT_API void from_json(const nlohmann::json& json, InlineQueryResultsButton& value);
TGBOT_API void to_json(nlohmann::json& json, const InlineQueryResultsButton& value);

} // namespace TgBot
