// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct InputMediaAnimation;
struct InputMediaAudio;
struct InputMediaDocument;
struct InputMediaLivePhoto;
struct InputMediaPhoto;
struct InputMediaVideo;

/**
 * @brief This object represents the content of a media message to be sent. It should be one of
 * InputMediaAnimation InputMediaAudio InputMediaDocument InputMediaLivePhoto InputMediaPhoto
 * InputMediaVideo
 */
struct InputMedia {
    using Ptr = std::shared_ptr<InputMedia>;

    std::variant<std::shared_ptr<InputMediaAnimation>, std::shared_ptr<InputMediaAudio>,
                 std::shared_ptr<InputMediaDocument>, std::shared_ptr<InputMediaLivePhoto>,
                 std::shared_ptr<InputMediaPhoto>, std::shared_ptr<InputMediaVideo>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, InputMedia& value);
TGBOT_API void to_json(nlohmann::json& json, const InputMedia& value);

} // namespace TgBot
