// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief A block with an anchor, corresponding to the HTML tag <a> with the attribute name.
 */
struct InputRichBlockAnchor {
    using Ptr = std::shared_ptr<InputRichBlockAnchor>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “anchor”
    */
    std::string type { TYPE };

    /**
     * @brief The name of the anchor
    */
    std::string name { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockAnchor& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockAnchor& value);

} // namespace TgBot
