// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>
#include <vector>

namespace TgBot {

struct InputRichBlockListItem;

/**
 * @brief A list of blocks, corresponding to the HTML tag <ul> or <ol> with multiple nested tags <li>.
 */
struct InputRichBlockList {
    using Ptr = std::shared_ptr<InputRichBlockList>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “list”
    */
    std::string type { TYPE };

    /**
     * @brief Items of the list
    */
    std::vector<std::shared_ptr<InputRichBlockListItem>> items { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockList& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockList& value);

} // namespace TgBot
