// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct MessageEntity;

/**
 * @brief Describes a task to add to a checklist.
 */
struct InputChecklistTask {
    using Ptr = std::shared_ptr<InputChecklistTask>;

    /**
     * @brief Unique identifier of the task; must be positive and unique among all task identifiers
     * currently present in the checklist
    */
    std::int32_t id { };

    /**
     * @brief Text of the task; 1-100 characters after entities parsing
    */
    std::string text { };

    /**
     * @brief Optional. Mode for parsing entities in the text. See formatting options for more
     * details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the text, which can be specified
     * instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler,
     * custom_emoji, and date_time entities are allowed.
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> textEntities { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputChecklistTask& value);
TGBOT_API void to_json(nlohmann::json& json, const InputChecklistTask& value);

} // namespace TgBot
