// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief Represents a venue to be sent.
 */
struct InputMediaVenue {
    using Ptr = std::shared_ptr<InputMediaVenue>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the media, must be venue
    */
    std::string type { TYPE };

    /**
     * @brief Latitude of the location
    */
    double latitude { };

    /**
     * @brief Longitude of the location
    */
    double longitude { };

    /**
     * @brief Name of the venue
    */
    std::string title { };

    /**
     * @brief Address of the venue
    */
    std::string address { };

    /**
     * @brief Optional. Foursquare identifier of the venue
    */
    std::optional<std::string> foursquareId { };

    /**
     * @brief Optional. Foursquare type of the venue, if known. (For example,
     * “arts_entertainment/default”, “arts_entertainment/aquarium” or “food/icecream”.)
    */
    std::optional<std::string> foursquareType { };

    /**
     * @brief Optional. Google Places identifier of the venue
    */
    std::optional<std::string> googlePlaceId { };

    /**
     * @brief Optional. Google Places type of the venue. (See supported types.)
    */
    std::optional<std::string> googlePlaceType { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputMediaVenue& value);
TGBOT_API void to_json(nlohmann::json& json, const InputMediaVenue& value);

} // namespace TgBot
