// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct InputMediaVoiceNote;
struct RichBlockCaption;

/**
 * @brief A block with a voice note, corresponding to the HTML tag <audio>.
 */
struct InputRichBlockVoiceNote {
    using Ptr = std::shared_ptr<InputRichBlockVoiceNote>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “voice_note”
    */
    std::string type { TYPE };

    /**
     * @brief The voice note. Caption is ignored.
    */
    std::shared_ptr<InputMediaVoiceNote> voiceNote { };

    /**
     * @brief Optional. Caption of the block
    */
    std::shared_ptr<RichBlockCaption> caption { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockVoiceNote& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockVoiceNote& value);

} // namespace TgBot
