// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct MessageEntity;

/**
 * @brief Represents a video to be sent.
 */
struct InputMediaVideo {
    using Ptr = std::shared_ptr<InputMediaVideo>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the media, must be video
    */
    std::string type { TYPE };

    /**
     * @brief File to send. Pass a file_id to send a file that exists on the Telegram servers
     * (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass
     * “attach://<file_attach_name>” to upload a new one using multipart/form-data under
     * <file_attach_name> name. More information on Sending Files »
    */
    std::string media { };

    /**
     * @brief Optional. Thumbnail of the file sent; can be ignored if thumbnail generation for the
     * file is supported server-side. The thumbnail should be in JPEG format and less than 200
     * kB in size. A thumbnail's width and height should not exceed 320. Ignored if the file is
     * not uploaded using multipart/form-data. Thumbnails can't be reused and can be only
     * uploaded as a new file, so you can pass “attach://<file_attach_name>” if the thumbnail
     * was uploaded using multipart/form-data under <file_attach_name>. More information on
     * Sending Files »
    */
    std::optional<std::string> thumbnail { };

    /**
     * @brief Optional. Cover for the video in the message. Pass a file_id to send a file that exists
     * on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from
     * the Internet, or pass “attach://<file_attach_name>” to upload a new one using
     * multipart/form-data under <file_attach_name> name. More information on Sending Files »
    */
    std::optional<std::string> cover { };

    /**
     * @brief Optional. Start timestamp for the video in the message
    */
    std::optional<std::int32_t> startTimestamp { };

    /**
     * @brief Optional. Caption of the video to be sent, 0-1024 characters after entities parsing
    */
    std::optional<std::string> caption { };

    /**
     * @brief Optional. Mode for parsing entities in the video caption. See formatting options for
     * more details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the caption, which can be specified
     * instead of parse_mode
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> captionEntities { };

    /**
     * @brief Optional. Pass True if the caption must be shown above the message media
    */
    std::optional<bool> showCaptionAboveMedia { };

    /**
     * @brief Optional. Video width
    */
    std::optional<std::int32_t> width { };

    /**
     * @brief Optional. Video height
    */
    std::optional<std::int32_t> height { };

    /**
     * @brief Optional. Video duration in seconds
    */
    std::optional<std::int32_t> duration { };

    /**
     * @brief Optional. Pass True if the uploaded video is suitable for streaming
    */
    std::optional<bool> supportsStreaming { };

    /**
     * @brief Optional. Pass True if the video needs to be covered with a spoiler animation
    */
    std::optional<bool> hasSpoiler { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputMediaVideo& value);
TGBOT_API void to_json(nlohmann::json& json, const InputMediaVideo& value);

} // namespace TgBot
