// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>

namespace TgBot {

/**
 * @brief Represents the content of a location message to be sent as the result of an inline query.
 */
struct InputLocationMessageContent {
    using Ptr = std::shared_ptr<InputLocationMessageContent>;

    /**
     * @brief Latitude of the location in degrees
    */
    double latitude { };

    /**
     * @brief Longitude of the location in degrees
    */
    double longitude { };

    /**
     * @brief Optional. The radius of uncertainty for the location, measured in meters; 0-1500
    */
    std::optional<double> horizontalAccuracy { };

    /**
     * @brief Optional. Period in seconds during which the location can be updated, must be between 60
     * and 86400, or 0x7FFFFFFF for live locations that can be edited indefinitely
    */
    std::optional<std::int32_t> livePeriod { };

    /**
     * @brief Optional. For live locations, a direction in which the user is moving, in degrees. Must
     * be between 1 and 360 if specified.
    */
    std::optional<std::int32_t> heading { };

    /**
     * @brief Optional. For live locations, a maximum distance for proximity alerts about approaching
     * another chat member, in meters. Must be between 1 and 100000 if specified.
    */
    std::optional<std::int32_t> proximityAlertRadius { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputLocationMessageContent& value);
TGBOT_API void to_json(nlohmann::json& json, const InputLocationMessageContent& value);

} // namespace TgBot
