// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Represents an HTTP link to be sent.
 */
struct InputMediaLink {
    using Ptr = std::shared_ptr<InputMediaLink>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the media, must be link
    */
    std::string type { TYPE };

    /**
     * @brief HTTP URL of the link
    */
    std::string url { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputMediaLink& value);
TGBOT_API void to_json(nlohmann::json& json, const InputMediaLink& value);

} // namespace TgBot
