// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct MaskPosition;

/**
 * @brief This object describes a sticker to be added to a sticker set.
 */
struct InputSticker {
    using Ptr = std::shared_ptr<InputSticker>;

    /**
     * @brief The added sticker. Pass a file_id as a String to send a file that already exists on the
     * Telegram servers, pass an HTTP URL as a String for Telegram to get a file from the
     * Internet, or pass “attach://<file_attach_name>” to upload a new file using
     * multipart/form-data under <file_attach_name> name. Animated and video stickers can't be
     * uploaded via HTTP URL. More information on Sending Files »
    */
    std::string sticker { };

    /**
     * @brief Format of the added sticker, must be one of “static” for a .WEBP or .PNG image,
     * “animated” for a .TGS animation, “video” for a .WEBM video
    */
    std::string format { };

    /**
     * @brief List of 1-20 emoji associated with the sticker
    */
    std::vector<std::string> emojiList { };

    /**
     * @brief Optional. Position where the mask should be placed on faces. For “mask” stickers only.
    */
    std::shared_ptr<MaskPosition> maskPosition { };

    /**
     * @brief Optional. List of 0-20 search keywords for the sticker with total length of up to 64
     * characters. For “regular” and “custom_emoji” stickers only.
    */
    std::optional<std::vector<std::string>> keywords { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputSticker& value);
TGBOT_API void to_json(nlohmann::json& json, const InputSticker& value);

} // namespace TgBot
