// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct InputMediaAnimation;
struct RichBlockCaption;

/**
 * @brief A block with an animation, corresponding to the HTML tag <video>.
 */
struct InputRichBlockAnimation {
    using Ptr = std::shared_ptr<InputRichBlockAnimation>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “animation”
    */
    std::string type { TYPE };

    /**
     * @brief The animation. Caption is ignored.
    */
    std::shared_ptr<InputMediaAnimation> animation { };

    /**
     * @brief Optional. Caption of the block
    */
    std::shared_ptr<RichBlockCaption> caption { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockAnimation& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockAnimation& value);

} // namespace TgBot
