// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A block with a “Thinking…” placeholder, corresponding to the custom HTML tag <tg-thinking>.
 * The block may be used only in sendRichMessageDraft, therefore it can't be received in
 * messages. See https://t.me/addemoji/AIActions for examples of custom emoji that are
 * recommended for usage in the block.
 */
struct InputRichBlockThinking {
    using Ptr = std::shared_ptr<InputRichBlockThinking>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “thinking”
    */
    std::string type { TYPE };

    /**
     * @brief Text of the block. See https://t.me/addemoji/AIActions for examples of custom emoji that
     * are recommended for usage in the block.
    */
    std::shared_ptr<RichText> text { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockThinking& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockThinking& value);

} // namespace TgBot
