// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief A static profile photo in the .JPG format.
 */
struct InputProfilePhotoStatic {
    using Ptr = std::shared_ptr<InputProfilePhotoStatic>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the profile photo, must be static
    */
    std::string type { TYPE };

    /**
     * @brief The static profile photo. Profile photos can't be reused and can only be uploaded as a
     * new file, so you can pass “attach://<file_attach_name>” if the photo was uploaded using
     * multipart/form-data under <file_attach_name>. More information on Sending Files »
    */
    std::string photo { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputProfilePhotoStatic& value);
TGBOT_API void to_json(nlohmann::json& json, const InputProfilePhotoStatic& value);

} // namespace TgBot
