// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct LinkPreviewOptions;
struct MessageEntity;

/**
 * @brief Represents the content of a text message to be sent as the result of an inline query.
 */
struct InputTextMessageContent {
    using Ptr = std::shared_ptr<InputTextMessageContent>;

    /**
     * @brief Text of the message to be sent, 1-4096 characters
    */
    std::string messageText { };

    /**
     * @brief Optional. Mode for parsing entities in the message text. See formatting options for more
     * details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in message text, which can be specified
     * instead of parse_mode
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> entities { };

    /**
     * @brief Optional. Link preview generation options for the message
    */
    std::shared_ptr<LinkPreviewOptions> linkPreviewOptions { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputTextMessageContent& value);
TGBOT_API void to_json(nlohmann::json& json, const InputTextMessageContent& value);

} // namespace TgBot
