// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct InputPaidMediaLivePhoto;
struct InputPaidMediaPhoto;
struct InputPaidMediaVideo;

/**
 * @brief This object describes the paid media to be sent. Currently, it can be one of
 * InputPaidMediaLivePhoto InputPaidMediaPhoto InputPaidMediaVideo
 */
struct InputPaidMedia {
    using Ptr = std::shared_ptr<InputPaidMedia>;

    std::variant<std::shared_ptr<InputPaidMediaLivePhoto>, std::shared_ptr<InputPaidMediaPhoto>,
                 std::shared_ptr<InputPaidMediaVideo>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, InputPaidMedia& value);
TGBOT_API void to_json(nlohmann::json& json, const InputPaidMedia& value);

} // namespace TgBot
