// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct InputRichBlock;
struct RichText;

/**
 * @brief An expandable block for details disclosure, corresponding to the HTML tag <details>.
 */
struct InputRichBlockDetails {
    using Ptr = std::shared_ptr<InputRichBlockDetails>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “details”
    */
    std::string type { TYPE };

    /**
     * @brief Always shown summary of the block
    */
    std::shared_ptr<RichText> summary { };

    /**
     * @brief Content of the block
    */
    std::vector<std::shared_ptr<InputRichBlock>> blocks { };

    /**
     * @brief Optional. Pass True if the content of the block is visible by default
    */
    std::optional<bool> isOpen { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockDetails& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockDetails& value);

} // namespace TgBot
