// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct InputMediaAnimation;
struct InputMediaLink;
struct InputMediaLivePhoto;
struct InputMediaLocation;
struct InputMediaPhoto;
struct InputMediaSticker;
struct InputMediaVenue;
struct InputMediaVideo;

/**
 * @brief This object represents the content of a poll option to be sent. It should be one of
 * InputMediaAnimation InputMediaLink InputMediaLivePhoto InputMediaLocation InputMediaPhoto
 * InputMediaSticker InputMediaVenue InputMediaVideo
 */
struct InputPollOptionMedia {
    using Ptr = std::shared_ptr<InputPollOptionMedia>;

    std::variant<std::shared_ptr<InputMediaAnimation>, std::shared_ptr<InputMediaLink>,
                 std::shared_ptr<InputMediaLivePhoto>, std::shared_ptr<InputMediaLocation>,
                 std::shared_ptr<InputMediaPhoto>, std::shared_ptr<InputMediaSticker>, std::shared_ptr<InputMediaVenue>,
                 std::shared_ptr<InputMediaVideo>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, InputPollOptionMedia& value);
TGBOT_API void to_json(nlohmann::json& json, const InputPollOptionMedia& value);

} // namespace TgBot
