// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct InputRichBlockAnchor;
struct InputRichBlockAnimation;
struct InputRichBlockAudio;
struct InputRichBlockBlockQuotation;
struct InputRichBlockCollage;
struct InputRichBlockDetails;
struct InputRichBlockDivider;
struct InputRichBlockFooter;
struct InputRichBlockList;
struct InputRichBlockMap;
struct InputRichBlockMathematicalExpression;
struct InputRichBlockParagraph;
struct InputRichBlockPhoto;
struct InputRichBlockPreformatted;
struct InputRichBlockPullQuotation;
struct InputRichBlockSectionHeading;
struct InputRichBlockSlideshow;
struct InputRichBlockTable;
struct InputRichBlockThinking;
struct InputRichBlockVideo;
struct InputRichBlockVoiceNote;

/**
 * @brief This object represents a block in a rich formatted message to be sent. Currently, it can be
 * any of the following types: InputRichBlockParagraph InputRichBlockSectionHeading
 * InputRichBlockPreformatted InputRichBlockFooter InputRichBlockDivider
 * InputRichBlockMathematicalExpression InputRichBlockAnchor InputRichBlockList
 * InputRichBlockBlockQuotation InputRichBlockPullQuotation InputRichBlockCollage
 * InputRichBlockSlideshow InputRichBlockTable InputRichBlockDetails InputRichBlockMap
 * InputRichBlockAnimation InputRichBlockAudio InputRichBlockPhoto InputRichBlockVideo
 * InputRichBlockVoiceNote InputRichBlockThinking
 */
struct InputRichBlock {
    using Ptr = std::shared_ptr<InputRichBlock>;

    std::variant<std::shared_ptr<InputRichBlockParagraph>, std::shared_ptr<InputRichBlockSectionHeading>,
                 std::shared_ptr<InputRichBlockPreformatted>, std::shared_ptr<InputRichBlockFooter>,
                 std::shared_ptr<InputRichBlockDivider>, std::shared_ptr<InputRichBlockMathematicalExpression>,
                 std::shared_ptr<InputRichBlockAnchor>, std::shared_ptr<InputRichBlockList>,
                 std::shared_ptr<InputRichBlockBlockQuotation>, std::shared_ptr<InputRichBlockPullQuotation>,
                 std::shared_ptr<InputRichBlockCollage>, std::shared_ptr<InputRichBlockSlideshow>,
                 std::shared_ptr<InputRichBlockTable>, std::shared_ptr<InputRichBlockDetails>,
                 std::shared_ptr<InputRichBlockMap>, std::shared_ptr<InputRichBlockAnimation>,
                 std::shared_ptr<InputRichBlockAudio>, std::shared_ptr<InputRichBlockPhoto>,
                 std::shared_ptr<InputRichBlockVideo>, std::shared_ptr<InputRichBlockVoiceNote>,
                 std::shared_ptr<InputRichBlockThinking>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlock& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlock& value);

} // namespace TgBot
