// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief The paid media to send is a photo.
 */
struct InputPaidMediaPhoto {
    using Ptr = std::shared_ptr<InputPaidMediaPhoto>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the media, must be photo
    */
    std::string type { TYPE };

    /**
     * @brief File to send. Pass a file_id to send a file that exists on the Telegram servers
     * (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass
     * “attach://<file_attach_name>” to upload a new one using multipart/form-data under
     * <file_attach_name> name. More information on Sending Files »
    */
    std::string media { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputPaidMediaPhoto& value);
TGBOT_API void to_json(nlohmann::json& json, const InputPaidMediaPhoto& value);

} // namespace TgBot
