// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct InputChecklistTask;
struct MessageEntity;

/**
 * @brief Describes a checklist to create.
 */
struct InputChecklist {
    using Ptr = std::shared_ptr<InputChecklist>;

    /**
     * @brief Title of the checklist; 1-255 characters after entities parsing
    */
    std::string title { };

    /**
     * @brief Optional. Mode for parsing entities in the title. See formatting options for more
     * details.
    */
    std::optional<std::string> parseMode { };

    /**
     * @brief Optional. List of special entities that appear in the title, which can be specified
     * instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler,
     * custom_emoji, and date_time entities are allowed.
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> titleEntities { };

    /**
     * @brief List of 1-30 tasks in the checklist
    */
    std::vector<std::shared_ptr<InputChecklistTask>> tasks { };

    /**
     * @brief Optional. Pass True if other users can add tasks to the checklist
    */
    std::optional<bool> othersCanAddTasks { };

    /**
     * @brief Optional. Pass True if other users can mark tasks as done or not done in the checklist
    */
    std::optional<bool> othersCanMarkTasksAsDone { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputChecklist& value);
TGBOT_API void to_json(nlohmann::json& json, const InputChecklist& value);

} // namespace TgBot
