// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct LabeledPrice;

/**
 * @brief Represents the content of an invoice message to be sent as the result of an inline query.
 */
struct InputInvoiceMessageContent {
    using Ptr = std::shared_ptr<InputInvoiceMessageContent>;

    /**
     * @brief Product name, 1-32 characters
    */
    std::string title { };

    /**
     * @brief Product description, 1-255 characters
    */
    std::string description { };

    /**
     * @brief Bot-defined invoice payload, 1-128 bytes. This will not be displayed to the user, use it
     * for your internal processes.
    */
    std::string payload { };

    /**
     * @brief Optional. Payment provider token, obtained via @BotFather. Pass an empty string for
     * payments in Telegram Stars.
    */
    std::optional<std::string> providerToken { };

    /**
     * @brief Three-letter ISO 4217 currency code, see more on currencies. Pass “XTR” for payments in
     * Telegram Stars.
    */
    std::string currency { };

    /**
     * @brief Price breakdown, a JSON-serialized list of components (e.g. product price, tax,
     * discount, delivery cost, delivery tax, bonus, etc.). Must contain exactly one item for
     * payments in Telegram Stars.
    */
    std::vector<std::shared_ptr<LabeledPrice>> prices { };

    /**
     * @brief Optional. The maximum accepted amount for tips in the smallest units of the currency
     * (integer, not float/double). For example, for a maximum tip of US$ 1.45 pass
     * max_tip_amount = 145. See the exp parameter in currencies.json, it shows the number of
     * digits past the decimal point for each currency (2 for the majority of currencies).
     * Defaults to 0. Not supported for payments in Telegram Stars.
    */
    std::optional<std::int32_t> maxTipAmount { };

    /**
     * @brief Optional. A JSON-serialized Array of suggested amounts of tip in the smallest units of
     * the currency (integer, not float/double). At most 4 suggested tip amounts can be
     * specified. The suggested tip amounts must be positive, passed in a strictly increased
     * order and must not exceed max_tip_amount.
    */
    std::optional<std::vector<std::int32_t>> suggestedTipAmounts { };

    /**
     * @brief Optional. A JSON-serialized object for data about the invoice, which will be shared with
     * the payment provider. A detailed description of the required fields should be provided
     * by the payment provider.
    */
    std::optional<std::string> providerData { };

    /**
     * @brief Optional. URL of the product photo for the invoice. Can be a photo of the goods or a
     * marketing image for a service.
    */
    std::optional<std::string> photoUrl { };

    /**
     * @brief Optional. Photo size in bytes
    */
    std::optional<std::int32_t> photoSize { };

    /**
     * @brief Optional. Photo width
    */
    std::optional<std::int32_t> photoWidth { };

    /**
     * @brief Optional. Photo height
    */
    std::optional<std::int32_t> photoHeight { };

    /**
     * @brief Optional. Pass True if you require the user's full name to complete the order. Ignored
     * for payments in Telegram Stars.
    */
    std::optional<bool> needName { };

    /**
     * @brief Optional. Pass True if you require the user's phone number to complete the order.
     * Ignored for payments in Telegram Stars.
    */
    std::optional<bool> needPhoneNumber { };

    /**
     * @brief Optional. Pass True if you require the user's email address to complete the order.
     * Ignored for payments in Telegram Stars.
    */
    std::optional<bool> needEmail { };

    /**
     * @brief Optional. Pass True if you require the user's shipping address to complete the order.
     * Ignored for payments in Telegram Stars.
    */
    std::optional<bool> needShippingAddress { };

    /**
     * @brief Optional. Pass True if the user's phone number should be sent to the provider. Ignored
     * for payments in Telegram Stars.
    */
    std::optional<bool> sendPhoneNumberToProvider { };

    /**
     * @brief Optional. Pass True if the user's email address should be sent to the provider. Ignored
     * for payments in Telegram Stars.
    */
    std::optional<bool> sendEmailToProvider { };

    /**
     * @brief Optional. Pass True if the final price depends on the shipping method. Ignored for
     * payments in Telegram Stars.
    */
    std::optional<bool> isFlexible { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputInvoiceMessageContent& value);
TGBOT_API void to_json(nlohmann::json& json, const InputInvoiceMessageContent& value);

} // namespace TgBot
