// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct Location;
struct RichBlockCaption;

/**
 * @brief A block with a map, corresponding to the custom HTML tag <tg-map>. The map's width and
 * height must not exceed 10000 in total. The width and height ratio must be at most 20.
 */
struct InputRichBlockMap {
    using Ptr = std::shared_ptr<InputRichBlockMap>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “map”
    */
    std::string type { TYPE };

    /**
     * @brief Location of the center of the map
    */
    std::shared_ptr<Location> location { };

    /**
     * @brief Map zoom level; 0-24
    */
    std::int32_t zoom { };

    /**
     * @brief Map width; 0-10000
    */
    std::int32_t width { };

    /**
     * @brief Map height; 0-10000
    */
    std::int32_t height { };

    /**
     * @brief Optional. Caption of the block
    */
    std::shared_ptr<RichBlockCaption> caption { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockMap& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockMap& value);

} // namespace TgBot
