// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A quotation with centered text, loosely corresponding to the HTML tag <aside>.
 */
struct InputRichBlockPullQuotation {
    using Ptr = std::shared_ptr<InputRichBlockPullQuotation>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “pullquote”
    */
    std::string type { TYPE };

    /**
     * @brief Text of the block
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief Optional. Credit of the block
    */
    std::shared_ptr<RichText> credit { };
};

TGBOT_API void from_json(const nlohmann::json& json, InputRichBlockPullQuotation& value);
TGBOT_API void to_json(nlohmann::json& json, const InputRichBlockPullQuotation& value);

} // namespace TgBot
