// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief This object contains basic information about an invoice.
 */
struct Invoice {
    using Ptr = std::shared_ptr<Invoice>;

    /**
     * @brief Product name
    */
    std::string title { };

    /**
     * @brief Product description
    */
    std::string description { };

    /**
     * @brief Unique bot deep-linking parameter that can be used to generate this invoice
    */
    std::string startParameter { };

    /**
     * @brief Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
    */
    std::string currency { };

    /**
     * @brief Total price in the smallest units of the currency (integer, not float/double). For
     * example, for a price of US$ 1.45 pass amount = 145. See the exp parameter in
     * currencies.json, it shows the number of digits past the decimal point for each currency
     * (2 for the majority of currencies).
    */
    std::int32_t totalAmount { };
};

TGBOT_API void from_json(const nlohmann::json& json, Invoice& value);
TGBOT_API void to_json(nlohmann::json& json, const Invoice& value);

} // namespace TgBot
