// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Represents an HTTP link.
 */
struct Link {
    using Ptr = std::shared_ptr<Link>;

    /**
     * @brief URL of the link
    */
    std::string url { };
};

TGBOT_API void from_json(const nlohmann::json& json, Link& value);
TGBOT_API void to_json(nlohmann::json& json, const Link& value);

} // namespace TgBot
