// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>

namespace TgBot {

/**
 * @brief This object represents a point on the map.
 */
struct Location {
    using Ptr = std::shared_ptr<Location>;

    /**
     * @brief Latitude as defined by the sender
    */
    double latitude { };

    /**
     * @brief Longitude as defined by the sender
    */
    double longitude { };

    /**
     * @brief Optional. The radius of uncertainty for the location, measured in meters; 0-1500
    */
    std::optional<double> horizontalAccuracy { };

    /**
     * @brief Optional. Time relative to the message sending date, during which the location can be
     * updated; in seconds. For active live locations only.
    */
    std::optional<std::int32_t> livePeriod { };

    /**
     * @brief Optional. The direction in which user is moving, in degrees; 1-360. For active live
     * locations only.
    */
    std::optional<std::int32_t> heading { };

    /**
     * @brief Optional. The maximum distance for proximity alerts about approaching another chat
     * member, in meters. For sent live locations only.
    */
    std::optional<std::int32_t> proximityAlertRadius { };
};

TGBOT_API void from_json(const nlohmann::json& json, Location& value);
TGBOT_API void to_json(nlohmann::json& json, const Location& value);

} // namespace TgBot
