// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

struct User;

/**
 * @brief This object contains information about the creation, token update, or owner update of a bot
 * that is managed by the current bot.
 */
struct ManagedBotUpdated {
    using Ptr = std::shared_ptr<ManagedBotUpdated>;

    /**
     * @brief User that created the bot
    */
    std::shared_ptr<User> user { };

    /**
     * @brief Information about the bot. Token of the bot can be fetched using the method
     * getManagedBotToken.
    */
    std::shared_ptr<User> bot { };
};

TGBOT_API void from_json(const nlohmann::json& json, ManagedBotUpdated& value);
TGBOT_API void to_json(nlohmann::json& json, const ManagedBotUpdated& value);

} // namespace TgBot
