// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief This object describes the position on faces where a mask should be placed by default.
 */
struct MaskPosition {
    using Ptr = std::shared_ptr<MaskPosition>;

    /**
     * @brief The part of the face relative to which the mask should be placed. One of “forehead”,
     * “eyes”, “mouth”, or “chin”.
    */
    std::string point { };

    /**
     * @brief Shift by X-axis measured in widths of the mask scaled to the face size, from left to
     * right. For example, choosing -1.0 will place mask just to the left of the default mask
     * position.
    */
    double xShift { };

    /**
     * @brief Shift by Y-axis measured in heights of the mask scaled to the face size, from top to
     * bottom. For example, 1.0 will place the mask just below the default mask position.
    */
    double yShift { };

    /**
     * @brief Mask scaling coefficient. For example, 2.0 means double size.
    */
    double scale { };
};

TGBOT_API void from_json(const nlohmann::json& json, MaskPosition& value);
TGBOT_API void to_json(nlohmann::json& json, const MaskPosition& value);

} // namespace TgBot
