// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct InaccessibleMessage;
struct Message;

/**
 * @brief This object describes a message that can be inaccessible to the bot. It can be one of
 * Message InaccessibleMessage
 */
struct MaybeInaccessibleMessage {
    using Ptr = std::shared_ptr<MaybeInaccessibleMessage>;

    std::variant<std::shared_ptr<Message>, std::shared_ptr<InaccessibleMessage>> value;
};

TGBOT_API void from_json(const nlohmann::json& json, MaybeInaccessibleMessage& value);
TGBOT_API void to_json(nlohmann::json& json, const MaybeInaccessibleMessage& value);

} // namespace TgBot
