// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct WebAppInfo;

/**
 * @brief Represents a menu button, which launches a Web App.
 */
struct MenuButtonWebApp {
    using Ptr = std::shared_ptr<MenuButtonWebApp>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the button, must be web_app
    */
    std::string type { TYPE };

    /**
     * @brief Text on the button
    */
    std::string text { };

    /**
     * @brief Description of the Web App that will be launched when the user presses the button. The
     * Web App will be able to send an arbitrary message on behalf of the user using the method
     * answerWebAppQuery. Alternatively, a t.me link to a Web App of the bot can be specified
     * in the object instead of the Web App's URL, in which case the Web App will be opened as
     * if the user pressed the link.
    */
    std::shared_ptr<WebAppInfo> webApp { };
};

TGBOT_API void from_json(const nlohmann::json& json, MenuButtonWebApp& value);
TGBOT_API void to_json(nlohmann::json& json, const MenuButtonWebApp& value);

} // namespace TgBot
