// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Describes that no specific value for the menu button was set.
 */
struct MenuButtonDefault {
    using Ptr = std::shared_ptr<MenuButtonDefault>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the button, must be default
    */
    std::string type { TYPE };
};

TGBOT_API void from_json(const nlohmann::json& json, MenuButtonDefault& value);
TGBOT_API void to_json(nlohmann::json& json, const MenuButtonDefault& value);

} // namespace TgBot
