// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct MenuButtonCommands;
struct MenuButtonDefault;
struct MenuButtonWebApp;

/**
 * @brief This object describes the bot's menu button in a private chat. It should be one of
 * MenuButtonCommands MenuButtonWebApp MenuButtonDefault If a menu button other than
 * MenuButtonDefault is set for a private chat, then it is applied in the chat. Otherwise the
 * default menu button is applied. By default, the menu button opens the list of bot commands.
 */
struct MenuButton {
    using Ptr = std::shared_ptr<MenuButton>;

    std::variant<std::shared_ptr<MenuButtonCommands>, std::shared_ptr<MenuButtonWebApp>,
                 std::shared_ptr<MenuButtonDefault>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, MenuButton& value);
TGBOT_API void to_json(nlohmann::json& json, const MenuButton& value);

} // namespace TgBot
