// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct MessageOriginChannel;
struct MessageOriginChat;
struct MessageOriginHiddenUser;
struct MessageOriginUser;

/**
 * @brief This object describes the origin of a message. It can be one of MessageOriginUser
 * MessageOriginHiddenUser MessageOriginChat MessageOriginChannel
 */
struct MessageOrigin {
    using Ptr = std::shared_ptr<MessageOrigin>;

    std::variant<std::shared_ptr<MessageOriginUser>, std::shared_ptr<MessageOriginHiddenUser>,
                 std::shared_ptr<MessageOriginChat>, std::shared_ptr<MessageOriginChannel>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, MessageOrigin& value);
TGBOT_API void to_json(nlohmann::json& json, const MessageOrigin& value);

} // namespace TgBot
