// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <vector>

namespace TgBot {

struct Chat;
struct ReactionCount;

/**
 * @brief This object represents reaction changes on a message with anonymous reactions.
 */
struct MessageReactionCountUpdated {
    using Ptr = std::shared_ptr<MessageReactionCountUpdated>;

    /**
     * @brief The chat containing the message
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Unique message identifier inside the chat
    */
    std::int32_t messageId { };

    /**
     * @brief Date of the change in Unix time
    */
    std::int32_t date { };

    /**
     * @brief List of reactions that are present on the message
    */
    std::vector<std::shared_ptr<ReactionCount>> reactions { };
};

TGBOT_API void from_json(const nlohmann::json& json, MessageReactionCountUpdated& value);
TGBOT_API void to_json(nlohmann::json& json, const MessageReactionCountUpdated& value);

} // namespace TgBot
