// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

/**
 * @brief This object represents a service message about a change in auto-delete timer settings.
 */
struct MessageAutoDeleteTimerChanged {
    using Ptr = std::shared_ptr<MessageAutoDeleteTimerChanged>;

    /**
     * @brief New auto-delete time for messages in the chat; in seconds
    */
    std::int32_t messageAutoDeleteTime { };
};

TGBOT_API void from_json(const nlohmann::json& json, MessageAutoDeleteTimerChanged& value);
TGBOT_API void to_json(nlohmann::json& json, const MessageAutoDeleteTimerChanged& value);

} // namespace TgBot
