// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct User;

/**
 * @brief The message was originally sent by a known user.
 */
struct MessageOriginUser {
    using Ptr = std::shared_ptr<MessageOriginUser>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the message origin, always “user”
    */
    std::string type { TYPE };

    /**
     * @brief Date the message was sent originally in Unix time
    */
    std::int32_t date { };

    /**
     * @brief User that sent the message originally
    */
    std::shared_ptr<User> senderUser { };
};

TGBOT_API void from_json(const nlohmann::json& json, MessageOriginUser& value);
TGBOT_API void to_json(nlohmann::json& json, const MessageOriginUser& value);

} // namespace TgBot
