// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct Animation;
struct Audio;
struct Chat;
struct ChatBackground;
struct ChatBoostAdded;
struct ChatOwnerChanged;
struct ChatOwnerLeft;
struct ChatShared;
struct Checklist;
struct ChecklistTasksAdded;
struct ChecklistTasksDone;
struct CommunityChatAdded;
struct CommunityChatRemoved;
struct Contact;
struct Dice;
struct DirectMessagePriceChanged;
struct DirectMessagesTopic;
struct Document;
struct ExternalReplyInfo;
struct ForumTopicClosed;
struct ForumTopicCreated;
struct ForumTopicEdited;
struct ForumTopicReopened;
struct Game;
struct GeneralForumTopicHidden;
struct GeneralForumTopicUnhidden;
struct GiftInfo;
struct Giveaway;
struct GiveawayCompleted;
struct GiveawayCreated;
struct GiveawayWinners;
struct InlineKeyboardMarkup;
struct Invoice;
struct LinkPreviewOptions;
struct LivePhoto;
struct Location;
struct ManagedBotCreated;
struct MaybeInaccessibleMessage;
struct MessageAutoDeleteTimerChanged;
struct MessageEntity;
struct MessageOrigin;
struct PaidMediaInfo;
struct PaidMessagePriceChanged;
struct PassportData;
struct PhotoSize;
struct Poll;
struct PollOptionAdded;
struct PollOptionDeleted;
struct ProximityAlertTriggered;
struct RefundedPayment;
struct RichMessage;
struct Sticker;
struct Story;
struct SuccessfulPayment;
struct SuggestedPostApprovalFailed;
struct SuggestedPostApproved;
struct SuggestedPostDeclined;
struct SuggestedPostInfo;
struct SuggestedPostPaid;
struct SuggestedPostRefunded;
struct TextQuote;
struct UniqueGiftInfo;
struct User;
struct UsersShared;
struct Venue;
struct Video;
struct VideoChatEnded;
struct VideoChatParticipantsInvited;
struct VideoChatScheduled;
struct VideoChatStarted;
struct VideoNote;
struct Voice;
struct WebAppData;
struct WriteAccessAllowed;

/**
 * @brief This object represents a message.
 */
struct Message {
    using Ptr = std::shared_ptr<Message>;

    /**
     * @brief Unique message identifier inside this chat; 0 for ephemeral messages. In specific
     * instances (e.g., a message containing a video sent to a big chat), the server might
     * automatically schedule a message instead of sending it immediately. In such cases, this
     * field will be 0 and the relevant message will be unusable until it is actually sent.
    */
    std::int32_t messageId { };

    /**
     * @brief Optional. Unique identifier of a message thread or forum topic to which the message
     * belongs; for supergroups and private chats only
    */
    std::optional<std::int32_t> messageThreadId { };

    /**
     * @brief Optional. Information about the direct messages chat topic that contains the message
    */
    std::shared_ptr<DirectMessagesTopic> directMessagesTopic { };

    /**
     * @brief Optional. Sender of the message; may be empty for messages sent to channels. For
     * backward compatibility, if the message was sent on behalf of a chat, the field contains
     * a fake sender user in non-channel chats.
    */
    std::shared_ptr<User> from { };

    /**
     * @brief Optional. Sender of the message when sent on behalf of a chat. For example, the
     * supergroup itself for messages sent by its anonymous administrators or a linked channel
     * for messages automatically forwarded to the channel's discussion group. For backward
     * compatibility, if the message was sent on behalf of a chat, the field from contains a
     * fake sender user in non-channel chats.
    */
    std::shared_ptr<Chat> senderChat { };

    /**
     * @brief Optional. If the sender of the message boosted the chat, the number of boosts added by
     * the user
    */
    std::optional<std::int32_t> senderBoostCount { };

    /**
     * @brief Optional. The bot that actually sent the message on behalf of the business account.
     * Available only for outgoing messages sent on behalf of the connected business account.
    */
    std::shared_ptr<User> senderBusinessBot { };

    /**
     * @brief Optional. Tag or custom title of the sender of the message; for supergroups only
    */
    std::optional<std::string> senderTag { };

    /**
     * @brief Optional. For ephemeral messages, the user who received the message
    */
    std::shared_ptr<User> receiverUser { };

    /**
     * @brief Optional. For ephemeral messages, identifier of the ephemeral message inside this chat.
     * The identifier may be reused for another ephemeral message after the message is deleted
     * or expires.
    */
    std::optional<std::int32_t> ephemeralMessageId { };

    /**
     * @brief Date the message was sent in Unix time. It is always a positive number, representing a
     * valid date.
    */
    std::int32_t date { };

    /**
     * @brief Optional. The unique identifier for the guest query. Use this identifier with the method
     * answerGuestQuery to send a response message. If non-empty, the message belongs to the
     * chat where the guest bot was summoned, which may not coincide with other existing bot
     * chats sharing the same identifier.
    */
    std::optional<std::string> guestQueryId { };

    /**
     * @brief Optional. Unique identifier of the business connection from which the message was
     * received. If non-empty, the message belongs to a chat of the corresponding business
     * account that is independent from any potential bot chat which might share the same
     * identifier.
    */
    std::optional<std::string> businessConnectionId { };

    /**
     * @brief Chat the message belongs to
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Optional. Information about the original message for forwarded messages
    */
    std::shared_ptr<MessageOrigin> forwardOrigin { };

    /**
     * @brief Optional. True, if the message is sent to a topic in a forum supergroup or a private
     * chat with the bot
    */
    std::optional<bool> isTopicMessage { };

    /**
     * @brief Optional. True, if the message is a channel post that was automatically forwarded to the
     * connected discussion group
    */
    std::optional<bool> isAutomaticForward { };

    /**
     * @brief Optional. For replies in the same chat and message thread, the original message. Note
     * that the Message object in this field will not contain further reply_to_message fields
     * even if it itself is a reply. If the message is a reply to an ephemeral message, then
     * this field may be omitted.
    */
    std::shared_ptr<Message> replyToMessage { };

    /**
     * @brief Optional. Information about the message that is being replied to, which may come from
     * another chat or forum topic
    */
    std::shared_ptr<ExternalReplyInfo> externalReply { };

    /**
     * @brief Optional. For replies that quote part of the original message, the quoted part of the
     * message
    */
    std::shared_ptr<TextQuote> quote { };

    /**
     * @brief Optional. For replies to a story, the original story
    */
    std::shared_ptr<Story> replyToStory { };

    /**
     * @brief Optional. Identifier of the specific checklist task that is being replied to
    */
    std::optional<std::int32_t> replyToChecklistTaskId { };

    /**
     * @brief Optional. Persistent identifier of the specific poll option that is being replied to
    */
    std::optional<std::string> replyToPollOptionId { };

    /**
     * @brief Optional. Bot through which the message was sent
    */
    std::shared_ptr<User> viaBot { };

    /**
     * @brief Optional. For a message sent by a guest bot, this is the user whose original message
     * triggered the bot's response
    */
    std::shared_ptr<User> guestBotCallerUser { };

    /**
     * @brief Optional. For a message sent by a guest bot, this is the chat whose original message
     * triggered the bot's response
    */
    std::shared_ptr<Chat> guestBotCallerChat { };

    /**
     * @brief Optional. Date the message was last edited in Unix time
    */
    std::optional<std::int32_t> editDate { };

    /**
     * @brief Optional. True, if the message can't be forwarded
    */
    std::optional<bool> hasProtectedContent { };

    /**
     * @brief Optional. True, if the message was sent by an implicit action, for example, as an away
     * or a greeting business message, or as a scheduled message
    */
    std::optional<bool> isFromOffline { };

    /**
     * @brief Optional. True, if the message is a paid post. Note that such posts must not be deleted
     * for 24 hours to receive the payment and can't be edited.
    */
    std::optional<bool> isPaidPost { };

    /**
     * @brief Optional. The unique identifier inside this chat of a media message group this message
     * belongs to
    */
    std::optional<std::string> mediaGroupId { };

    /**
     * @brief Optional. Signature of the post author for messages in channels, or the custom title of
     * an anonymous group administrator
    */
    std::optional<std::string> authorSignature { };

    /**
     * @brief Optional. The number of Telegram Stars that were paid by the sender of the message to
     * send it
    */
    std::optional<std::int32_t> paidStarCount { };

    /**
     * @brief Optional. For text messages, the actual UTF-8 text of the message
    */
    std::optional<std::string> text { };

    /**
     * @brief Optional. For text messages, special entities like usernames, URLs, bot commands, etc.
     * that appear in the text
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> entities { };

    /**
     * @brief Optional. Options used for link preview generation for the message, if it is a text
     * message and link preview options were changed
    */
    std::shared_ptr<LinkPreviewOptions> linkPreviewOptions { };

    /**
     * @brief Optional. Information about suggested post parameters if the message is a suggested post
     * in a channel direct messages chat. If the message is an approved or declined suggested
     * post, then it can't be edited.
    */
    std::shared_ptr<SuggestedPostInfo> suggestedPostInfo { };

    /**
     * @brief Optional. Unique identifier of the message effect added to the message
    */
    std::optional<std::string> effectId { };

    /**
     * @brief Optional. Message is a rich formatted message
    */
    std::shared_ptr<RichMessage> richMessage { };

    /**
     * @brief Optional. Message is an animation, information about the animation. For backward
     * compatibility, when this field is set, the document field will also be set.
    */
    std::shared_ptr<Animation> animation { };

    /**
     * @brief Optional. Message is an audio file, information about the file
    */
    std::shared_ptr<Audio> audio { };

    /**
     * @brief Optional. Message is a general file, information about the file
    */
    std::shared_ptr<Document> document { };

    /**
     * @brief Optional. Message is a live photo, information about the live photo. For backward
     * compatibility, when this field is set, the photo field will also be set.
    */
    std::shared_ptr<LivePhoto> livePhoto { };

    /**
     * @brief Optional. Message contains paid media; information about the paid media
    */
    std::shared_ptr<PaidMediaInfo> paidMedia { };

    /**
     * @brief Optional. Message is a photo, available sizes of the photo
    */
    std::optional<std::vector<std::shared_ptr<PhotoSize>>> photo { };

    /**
     * @brief Optional. Message is a sticker, information about the sticker
    */
    std::shared_ptr<Sticker> sticker { };

    /**
     * @brief Optional. Message is a forwarded story
    */
    std::shared_ptr<Story> story { };

    /**
     * @brief Optional. Message is a video, information about the video
    */
    std::shared_ptr<Video> video { };

    /**
     * @brief Optional. Message is a video note, information about the video message
    */
    std::shared_ptr<VideoNote> videoNote { };

    /**
     * @brief Optional. Message is a voice message, information about the file
    */
    std::shared_ptr<Voice> voice { };

    /**
     * @brief Optional. Caption for the animation, audio, document, paid media, photo, video or voice
    */
    std::optional<std::string> caption { };

    /**
     * @brief Optional. For messages with a caption, special entities like usernames, URLs, bot
     * commands, etc. that appear in the caption
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> captionEntities { };

    /**
     * @brief Optional. True, if the caption must be shown above the message media
    */
    std::optional<bool> showCaptionAboveMedia { };

    /**
     * @brief Optional. True, if the message media is covered by a spoiler animation
    */
    std::optional<bool> hasMediaSpoiler { };

    /**
     * @brief Optional. Message is a checklist
    */
    std::shared_ptr<Checklist> checklist { };

    /**
     * @brief Optional. Message is a shared contact, information about the contact
    */
    std::shared_ptr<Contact> contact { };

    /**
     * @brief Optional. Message is a dice with random value
    */
    std::shared_ptr<Dice> dice { };

    /**
     * @brief Optional. Message is a game, information about the game. More about games »
    */
    std::shared_ptr<Game> game { };

    /**
     * @brief Optional. Message is a native poll, information about the poll
    */
    std::shared_ptr<Poll> poll { };

    /**
     * @brief Optional. Message is a venue, information about the venue. For backward compatibility,
     * when this field is set, the location field will also be set.
    */
    std::shared_ptr<Venue> venue { };

    /**
     * @brief Optional. Message is a shared location, information about the location
    */
    std::shared_ptr<Location> location { };

    /**
     * @brief Optional. New members that were added to the group or supergroup and information about
     * them (the bot itself may be one of these members)
    */
    std::optional<std::vector<std::shared_ptr<User>>> newChatMembers { };

    /**
     * @brief Optional. A member was removed from the group, information about them (this member may
     * be the bot itself)
    */
    std::shared_ptr<User> leftChatMember { };

    /**
     * @brief Optional. Service message: chat owner has left
    */
    std::shared_ptr<ChatOwnerLeft> chatOwnerLeft { };

    /**
     * @brief Optional. Service message: chat owner has changed
    */
    std::shared_ptr<ChatOwnerChanged> chatOwnerChanged { };

    /**
     * @brief Optional. A chat title was changed to this value
    */
    std::optional<std::string> newChatTitle { };

    /**
     * @brief Optional. A chat photo was change to this value
    */
    std::optional<std::vector<std::shared_ptr<PhotoSize>>> newChatPhoto { };

    /**
     * @brief Optional. Service message: the chat photo was deleted
    */
    std::optional<bool> deleteChatPhoto { };

    /**
     * @brief Optional. Service message: the group has been created
    */
    std::optional<bool> groupChatCreated { };

    /**
     * @brief Optional. Service message: the supergroup has been created. This field can't be received
     * in a message coming through updates, because bot can't be a member of a supergroup when
     * it is created. It can only be found in reply_to_message if someone replies to a very
     * first message in a directly created supergroup.
    */
    std::optional<bool> supergroupChatCreated { };

    /**
     * @brief Optional. Service message: the channel has been created. This field can't be received in
     * a message coming through updates, because bot can't be a member of a channel when it is
     * created. It can only be found in reply_to_message if someone replies to a very first
     * message in a channel.
    */
    std::optional<bool> channelChatCreated { };

    /**
     * @brief Optional. Service message: auto-delete timer settings changed in the chat
    */
    std::shared_ptr<MessageAutoDeleteTimerChanged> messageAutoDeleteTimerChanged { };

    /**
     * @brief Optional. The group has been migrated to a supergroup with the specified identifier.
     * This number may have more than 32 significant bits and some programming languages may
     * have difficulty/silent defects in interpreting it. But it has at most 52 significant
     * bits, so a signed 64-bit integer or double-precision float type are safe for storing
     * this identifier.
    */
    std::optional<std::int64_t> migrateToChatId { };

    /**
     * @brief Optional. The supergroup has been migrated from a group with the specified identifier.
     * This number may have more than 32 significant bits and some programming languages may
     * have difficulty/silent defects in interpreting it. But it has at most 52 significant
     * bits, so a signed 64-bit integer or double-precision float type are safe for storing
     * this identifier.
    */
    std::optional<std::int64_t> migrateFromChatId { };

    /**
     * @brief Optional. Specified message was pinned. Note that the Message object in this field will
     * not contain further reply_to_message fields even if it itself is a reply.
    */
    std::shared_ptr<MaybeInaccessibleMessage> pinnedMessage { };

    /**
     * @brief Optional. Message is an invoice for a payment, information about the invoice. More about
     * payments »
    */
    std::shared_ptr<Invoice> invoice { };

    /**
     * @brief Optional. Message is a service message about a successful payment, information about the
     * payment. More about payments »
    */
    std::shared_ptr<SuccessfulPayment> successfulPayment { };

    /**
     * @brief Optional. Message is a service message about a refunded payment, information about the
     * payment. More about payments »
    */
    std::shared_ptr<RefundedPayment> refundedPayment { };

    /**
     * @brief Optional. Service message: users were shared with the bot
    */
    std::shared_ptr<UsersShared> usersShared { };

    /**
     * @brief Optional. Service message: a chat was shared with the bot
    */
    std::shared_ptr<ChatShared> chatShared { };

    /**
     * @brief Optional. Service message: a regular gift was sent or received
    */
    std::shared_ptr<GiftInfo> gift { };

    /**
     * @brief Optional. Service message: a unique gift was sent or received
    */
    std::shared_ptr<UniqueGiftInfo> uniqueGift { };

    /**
     * @brief Optional. Service message: upgrade of a gift was purchased after the gift was sent
    */
    std::shared_ptr<GiftInfo> giftUpgradeSent { };

    /**
     * @brief Optional. The domain name of the website on which the user has logged in. More about
     * Telegram Login »
    */
    std::optional<std::string> connectedWebsite { };

    /**
     * @brief Optional. Service message: the user allowed the bot to write messages after adding it to
     * the attachment or side menu, launching a Web App from a link, or accepting an explicit
     * request from a Web App sent by the method requestWriteAccess
    */
    std::shared_ptr<WriteAccessAllowed> writeAccessAllowed { };

    /**
     * @brief Optional. Telegram Passport data
    */
    std::shared_ptr<PassportData> passportData { };

    /**
     * @brief Optional. Service message: a user in the chat triggered another user's proximity alert
     * while sharing Live Location
    */
    std::shared_ptr<ProximityAlertTriggered> proximityAlertTriggered { };

    /**
     * @brief Optional. Service message: user boosted the chat
    */
    std::shared_ptr<ChatBoostAdded> boostAdded { };

    /**
     * @brief Optional. Service message: chat background set
    */
    std::shared_ptr<ChatBackground> chatBackgroundSet { };

    /**
     * @brief Optional. Service message: some tasks in a checklist were marked as done or not done
    */
    std::shared_ptr<ChecklistTasksDone> checklistTasksDone { };

    /**
     * @brief Optional. Service message: tasks were added to a checklist
    */
    std::shared_ptr<ChecklistTasksAdded> checklistTasksAdded { };

    /**
     * @brief Optional. Service message: chat added to a Community
    */
    std::shared_ptr<CommunityChatAdded> communityChatAdded { };

    /**
     * @brief Optional. Service message: chat removed from a Community
    */
    std::shared_ptr<CommunityChatRemoved> communityChatRemoved { };

    /**
     * @brief Optional. Service message: the price for paid messages in the corresponding direct
     * messages chat of a channel has changed
    */
    std::shared_ptr<DirectMessagePriceChanged> directMessagePriceChanged { };

    /**
     * @brief Optional. Service message: forum topic created
    */
    std::shared_ptr<ForumTopicCreated> forumTopicCreated { };

    /**
     * @brief Optional. Service message: forum topic edited
    */
    std::shared_ptr<ForumTopicEdited> forumTopicEdited { };

    /**
     * @brief Optional. Service message: forum topic closed
    */
    std::shared_ptr<ForumTopicClosed> forumTopicClosed { };

    /**
     * @brief Optional. Service message: forum topic reopened
    */
    std::shared_ptr<ForumTopicReopened> forumTopicReopened { };

    /**
     * @brief Optional. Service message: the 'General' forum topic hidden
    */
    std::shared_ptr<GeneralForumTopicHidden> generalForumTopicHidden { };

    /**
     * @brief Optional. Service message: the 'General' forum topic unhidden
    */
    std::shared_ptr<GeneralForumTopicUnhidden> generalForumTopicUnhidden { };

    /**
     * @brief Optional. Service message: a scheduled giveaway was created
    */
    std::shared_ptr<GiveawayCreated> giveawayCreated { };

    /**
     * @brief Optional. The message is a scheduled giveaway message
    */
    std::shared_ptr<Giveaway> giveaway { };

    /**
     * @brief Optional. A giveaway with public winners was completed
    */
    std::shared_ptr<GiveawayWinners> giveawayWinners { };

    /**
     * @brief Optional. Service message: a giveaway without public winners was completed
    */
    std::shared_ptr<GiveawayCompleted> giveawayCompleted { };

    /**
     * @brief Optional. Service message: user created a bot that will be managed by the current bot
    */
    std::shared_ptr<ManagedBotCreated> managedBotCreated { };

    /**
     * @brief Optional. Service message: the price for paid messages has changed in the chat
    */
    std::shared_ptr<PaidMessagePriceChanged> paidMessagePriceChanged { };

    /**
     * @brief Optional. Service message: answer option was added to a poll
    */
    std::shared_ptr<PollOptionAdded> pollOptionAdded { };

    /**
     * @brief Optional. Service message: answer option was deleted from a poll
    */
    std::shared_ptr<PollOptionDeleted> pollOptionDeleted { };

    /**
     * @brief Optional. Service message: a suggested post was approved
    */
    std::shared_ptr<SuggestedPostApproved> suggestedPostApproved { };

    /**
     * @brief Optional. Service message: approval of a suggested post has failed
    */
    std::shared_ptr<SuggestedPostApprovalFailed> suggestedPostApprovalFailed { };

    /**
     * @brief Optional. Service message: a suggested post was declined
    */
    std::shared_ptr<SuggestedPostDeclined> suggestedPostDeclined { };

    /**
     * @brief Optional. Service message: payment for a suggested post was received
    */
    std::shared_ptr<SuggestedPostPaid> suggestedPostPaid { };

    /**
     * @brief Optional. Service message: payment for a suggested post was refunded
    */
    std::shared_ptr<SuggestedPostRefunded> suggestedPostRefunded { };

    /**
     * @brief Optional. Service message: video chat scheduled
    */
    std::shared_ptr<VideoChatScheduled> videoChatScheduled { };

    /**
     * @brief Optional. Service message: video chat started
    */
    std::shared_ptr<VideoChatStarted> videoChatStarted { };

    /**
     * @brief Optional. Service message: video chat ended
    */
    std::shared_ptr<VideoChatEnded> videoChatEnded { };

    /**
     * @brief Optional. Service message: new participants invited to a video chat
    */
    std::shared_ptr<VideoChatParticipantsInvited> videoChatParticipantsInvited { };

    /**
     * @brief Optional. Service message: data sent by a Web App
    */
    std::shared_ptr<WebAppData> webAppData { };

    /**
     * @brief Optional. Inline keyboard attached to the message. login_url buttons are represented as
     * ordinary url buttons.
    */
    std::shared_ptr<InlineKeyboardMarkup> replyMarkup { };
};

TGBOT_API void from_json(const nlohmann::json& json, Message& value);
TGBOT_API void to_json(nlohmann::json& json, const Message& value);

} // namespace TgBot
