// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief The message was originally sent by an unknown user.
 */
struct MessageOriginHiddenUser {
    using Ptr = std::shared_ptr<MessageOriginHiddenUser>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the message origin, always “hidden_user”
    */
    std::string type { TYPE };

    /**
     * @brief Date the message was sent originally in Unix time
    */
    std::int32_t date { };

    /**
     * @brief Name of the user that sent the message originally
    */
    std::string senderUserName { };
};

TGBOT_API void from_json(const nlohmann::json& json, MessageOriginHiddenUser& value);
TGBOT_API void to_json(nlohmann::json& json, const MessageOriginHiddenUser& value);

} // namespace TgBot
