// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct ShippingAddress;

/**
 * @brief This object represents information about an order.
 */
struct OrderInfo {
    using Ptr = std::shared_ptr<OrderInfo>;

    /**
     * @brief Optional. User name
    */
    std::optional<std::string> name { };

    /**
     * @brief Optional. User's phone number
    */
    std::optional<std::string> phoneNumber { };

    /**
     * @brief Optional. User email
    */
    std::optional<std::string> email { };

    /**
     * @brief Optional. User shipping address
    */
    std::shared_ptr<ShippingAddress> shippingAddress { };
};

TGBOT_API void from_json(const nlohmann::json& json, OrderInfo& value);
TGBOT_API void to_json(nlohmann::json& json, const OrderInfo& value);

} // namespace TgBot
