// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct Gift;
struct MessageEntity;
struct User;

/**
 * @brief Describes a regular gift owned by a user or a chat.
 */
struct OwnedGiftRegular {
    using Ptr = std::shared_ptr<OwnedGiftRegular>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the gift, always “regular”
    */
    std::string type { TYPE };

    /**
     * @brief Information about the regular gift
    */
    std::shared_ptr<Gift> gift { };

    /**
     * @brief Optional. Unique identifier of the gift for the bot; for gifts received on behalf of
     * business accounts only
    */
    std::optional<std::string> ownedGiftId { };

    /**
     * @brief Optional. Sender of the gift if it is a known user
    */
    std::shared_ptr<User> senderUser { };

    /**
     * @brief Date the gift was sent in Unix time
    */
    std::int32_t sendDate { };

    /**
     * @brief Optional. Text of the message that was added to the gift
    */
    std::optional<std::string> text { };

    /**
     * @brief Optional. Special entities that appear in the text
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> entities { };

    /**
     * @brief Optional. True, if the sender and gift text are shown only to the gift receiver;
     * otherwise, everyone will be able to see them
    */
    std::optional<bool> isPrivate { };

    /**
     * @brief Optional. True, if the gift is displayed on the account's profile page; for gifts
     * received on behalf of business accounts only
    */
    std::optional<bool> isSaved { };

    /**
     * @brief Optional. True, if the gift can be upgraded to a unique gift; for gifts received on
     * behalf of business accounts only
    */
    std::optional<bool> canBeUpgraded { };

    /**
     * @brief Optional. True, if the gift was refunded and isn't available anymore
    */
    std::optional<bool> wasRefunded { };

    /**
     * @brief Optional. Number of Telegram Stars that can be claimed by the receiver instead of the
     * gift; omitted if the gift cannot be converted to Telegram Stars; for gifts received on
     * behalf of business accounts only
    */
    std::optional<std::int32_t> convertStarCount { };

    /**
     * @brief Optional. Number of Telegram Stars that were paid for the ability to upgrade the gift
    */
    std::optional<std::int32_t> prepaidUpgradeStarCount { };

    /**
     * @brief Optional. True, if the gift's upgrade was purchased after the gift was sent; for gifts
     * received on behalf of business accounts only
    */
    std::optional<bool> isUpgradeSeparate { };

    /**
     * @brief Optional. Unique number reserved for this gift when upgraded. See the number field in
     * UniqueGift.
    */
    std::optional<std::int32_t> uniqueGiftNumber { };
};

TGBOT_API void from_json(const nlohmann::json& json, OwnedGiftRegular& value);
TGBOT_API void to_json(nlohmann::json& json, const OwnedGiftRegular& value);

} // namespace TgBot
