// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

/**
 * @brief Describes a service message about a change in the price of paid messages within a chat.
 */
struct PaidMessagePriceChanged {
    using Ptr = std::shared_ptr<PaidMessagePriceChanged>;

    /**
     * @brief The new number of Telegram Stars that must be paid by non-administrator users of the
     * supergroup chat for each sent message
    */
    std::int32_t paidMessageStarCount { };
};

TGBOT_API void from_json(const nlohmann::json& json, PaidMessagePriceChanged& value);
TGBOT_API void to_json(nlohmann::json& json, const PaidMessagePriceChanged& value);

} // namespace TgBot
