// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct LivePhoto;

/**
 * @brief The paid media is a live photo.
 */
struct PaidMediaLivePhoto {
    using Ptr = std::shared_ptr<PaidMediaLivePhoto>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the paid media, always “live_photo”
    */
    std::string type { TYPE };

    /**
     * @brief The photo
    */
    std::shared_ptr<LivePhoto> livePhoto { };
};

TGBOT_API void from_json(const nlohmann::json& json, PaidMediaLivePhoto& value);
TGBOT_API void to_json(nlohmann::json& json, const PaidMediaLivePhoto& value);

} // namespace TgBot
