// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>
#include <vector>

namespace TgBot {

struct PhotoSize;

/**
 * @brief The paid media is a photo.
 */
struct PaidMediaPhoto {
    using Ptr = std::shared_ptr<PaidMediaPhoto>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the paid media, always “photo”
    */
    std::string type { TYPE };

    /**
     * @brief The photo
    */
    std::vector<std::shared_ptr<PhotoSize>> photo { };
};

TGBOT_API void from_json(const nlohmann::json& json, PaidMediaPhoto& value);
TGBOT_API void to_json(nlohmann::json& json, const PaidMediaPhoto& value);

} // namespace TgBot
