// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Represents an issue in an unspecified place. The error is considered resolved when new data
 * is added.
 */
struct PassportElementErrorUnspecified {
    using Ptr = std::shared_ptr<PassportElementErrorUnspecified>;

    static TGBOT_API const std::string SOURCE;

    /**
     * @brief Error source, must be unspecified
    */
    std::string source { SOURCE };

    /**
     * @brief Type of element of the user's Telegram Passport which has the issue
    */
    std::string type { };

    /**
     * @brief Base64-encoded element hash
    */
    std::string elementHash { };

    /**
     * @brief Error message
    */
    std::string message { };
};

TGBOT_API void from_json(const nlohmann::json& json, PassportElementErrorUnspecified& value);
TGBOT_API void to_json(nlohmann::json& json, const PassportElementErrorUnspecified& value);

} // namespace TgBot
