// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Represents an issue with the reverse side of a document. The error is considered resolved
 * when the file with reverse side of the document changes.
 */
struct PassportElementErrorReverseSide {
    using Ptr = std::shared_ptr<PassportElementErrorReverseSide>;

    static TGBOT_API const std::string SOURCE;

    /**
     * @brief Error source, must be reverse_side
    */
    std::string source { SOURCE };

    /**
     * @brief The section of the user's Telegram Passport which has the issue, one of
     * “driver_license”, “identity_card”
    */
    std::string type { };

    /**
     * @brief Base64-encoded hash of the file with the reverse side of the document
    */
    std::string fileHash { };

    /**
     * @brief Error message
    */
    std::string message { };
};

TGBOT_API void from_json(const nlohmann::json& json, PassportElementErrorReverseSide& value);
TGBOT_API void to_json(nlohmann::json& json, const PassportElementErrorReverseSide& value);

} // namespace TgBot
