// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents one size of a photo or a file / sticker thumbnail.
 */
struct PhotoSize {
    using Ptr = std::shared_ptr<PhotoSize>;

    /**
     * @brief Identifier for this file, which can be used to download or reuse the file
    */
    std::string fileId { };

    /**
     * @brief Unique identifier for this file, which is supposed to be the same over time and for
     * different bots. Can't be used to download or reuse the file.
    */
    std::string fileUniqueId { };

    /**
     * @brief Photo width
    */
    std::int32_t width { };

    /**
     * @brief Photo height
    */
    std::int32_t height { };

    /**
     * @brief Optional. File size in bytes
    */
    std::optional<std::int32_t> fileSize { };
};

TGBOT_API void from_json(const nlohmann::json& json, PhotoSize& value);
TGBOT_API void to_json(nlohmann::json& json, const PhotoSize& value);

} // namespace TgBot
