// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct Chat;
struct MessageEntity;
struct PollMedia;
struct User;

/**
 * @brief This object contains information about one answer option in a poll.
 */
struct PollOption {
    using Ptr = std::shared_ptr<PollOption>;

    /**
     * @brief Unique identifier of the option, persistent on option addition and deletion
    */
    std::string persistentId { };

    /**
     * @brief Option text, 1-100 characters
    */
    std::string text { };

    /**
     * @brief Optional. Special entities that appear in the option text. Currently, only custom emoji
     * entities are allowed in poll option texts
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> textEntities { };

    /**
     * @brief Optional. Media added to the poll option
    */
    std::shared_ptr<PollMedia> media { };

    /**
     * @brief Number of users who voted for this option; may be 0 if unknown
    */
    std::int32_t voterCount { };

    /**
     * @brief Optional. User who added the option; omitted if the option wasn't added by a user after
     * poll creation
    */
    std::shared_ptr<User> addedByUser { };

    /**
     * @brief Optional. Chat that added the option; omitted if the option wasn't added by a chat after
     * poll creation
    */
    std::shared_ptr<Chat> addedByChat { };

    /**
     * @brief Optional. Point in time (Unix timestamp) when the option was added; omitted if the
     * option existed in the original poll
    */
    std::optional<std::int32_t> additionDate { };
};

TGBOT_API void from_json(const nlohmann::json& json, PollOption& value);
TGBOT_API void to_json(nlohmann::json& json, const PollOption& value);

} // namespace TgBot
