// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct MaybeInaccessibleMessage;
struct MessageEntity;

/**
 * @brief Describes a service message about an option deleted from a poll.
 */
struct PollOptionDeleted {
    using Ptr = std::shared_ptr<PollOptionDeleted>;

    /**
     * @brief Optional. Message containing the poll from which the option was deleted, if known. Note
     * that the Message object in this field will not contain the reply_to_message field even
     * if it itself is a reply.
    */
    std::shared_ptr<MaybeInaccessibleMessage> pollMessage { };

    /**
     * @brief Unique identifier of the deleted option
    */
    std::string optionPersistentId { };

    /**
     * @brief Option text
    */
    std::string optionText { };

    /**
     * @brief Optional. Special entities that appear in the option_text
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> optionTextEntities { };
};

TGBOT_API void from_json(const nlohmann::json& json, PollOptionDeleted& value);
TGBOT_API void to_json(nlohmann::json& json, const PollOptionDeleted& value);

} // namespace TgBot
