// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief The reaction is based on an emoji.
 */
struct ReactionTypeEmoji {
    using Ptr = std::shared_ptr<ReactionTypeEmoji>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the reaction, always “emoji”
    */
    std::string type { TYPE };

    /**
     * @brief Reaction emoji. Currently, it can be one of "", "", "", "", "", "", "", "", "", "", "",
     * "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
     * "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
     * "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "".
    */
    std::string emoji { };
};

TGBOT_API void from_json(const nlohmann::json& json, ReactionTypeEmoji& value);
TGBOT_API void to_json(nlohmann::json& json, const ReactionTypeEmoji& value);

} // namespace TgBot
