// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

struct ReactionType;

/**
 * @brief Represents a reaction added to a message along with the number of times it was added.
 */
struct ReactionCount {
    using Ptr = std::shared_ptr<ReactionCount>;

    /**
     * @brief Type of the reaction
    */
    std::shared_ptr<ReactionType> type { };

    /**
     * @brief Number of times the reaction was added
    */
    std::int32_t totalCount { };
};

TGBOT_API void from_json(const nlohmann::json& json, ReactionCount& value);
TGBOT_API void to_json(nlohmann::json& json, const ReactionCount& value);

} // namespace TgBot
