// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief The reaction is based on a custom emoji.
 */
struct ReactionTypeCustomEmoji {
    using Ptr = std::shared_ptr<ReactionTypeCustomEmoji>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the reaction, always “custom_emoji”
    */
    std::string type { TYPE };

    /**
     * @brief Custom emoji identifier
    */
    std::string customEmojiId { };
};

TGBOT_API void from_json(const nlohmann::json& json, ReactionTypeCustomEmoji& value);
TGBOT_API void to_json(nlohmann::json& json, const ReactionTypeCustomEmoji& value);

} // namespace TgBot
