// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct MessageEntity;

/**
 * @brief Describes reply parameters for the message that is being sent.
 */
struct ReplyParameters {
    using Ptr = std::shared_ptr<ReplyParameters>;

    /**
     * @brief Optional. Identifier of the message that will be replied to in the current chat, or in
     * the chat chat_id if it is specified. Required if ephemeral_message_id isn't specified.
    */
    std::optional<std::int32_t> messageId { };

    /**
     * @brief Optional. If the message to be replied to is from a different chat, unique identifier
     * for the chat or username of the bot, supergroup or channel in the format @username. Not
     * supported for messages sent on behalf of a business account, messages from channel
     * direct messages chats and ephemeral messages.
    */
    std::optional<std::int64_t> chatId { };

    /**
     * @brief Optional. Identifier of the incoming ephemeral message that will be replied to in the
     * current chat. A reply to an ephemeral message must itself be an ephemeral message. An
     * ephemeral message may only be replied to within 15 seconds of being sent. Required if
     * message_id isn't specified.
    */
    std::optional<std::int32_t> ephemeralMessageId { };

    /**
     * @brief Optional. Pass True if the message should be sent even if the specified message to be
     * replied to is not found. Always False for replies in another chat or forum topic, and
     * sent ephemeral messages. Always True for messages sent on behalf of a business account.
    */
    std::optional<bool> allowSendingWithoutReply { };

    /**
     * @brief Optional. Quoted part of the message to be replied to; 0-1024 characters after entities
     * parsing. The quote must be an exact substring of the message to be replied to, including
     * bold, italic, underline, strikethrough, spoiler, custom_emoji, and date_time entities.
     * The message will fail to send if the quote isn't found in the original message. Ignored
     * for ephemeral messages.
    */
    std::optional<std::string> quote { };

    /**
     * @brief Optional. Mode for parsing entities in the quote. See formatting options for more
     * details.
    */
    std::optional<std::string> quoteParseMode { };

    /**
     * @brief Optional. A JSON-serialized list of special entities that appear in the quote. It can be
     * specified instead of quote_parse_mode.
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> quoteEntities { };

    /**
     * @brief Optional. Position of the quote in the original message in UTF-16 code units
    */
    std::optional<std::int32_t> quotePosition { };

    /**
     * @brief Optional. Identifier of the specific checklist task to be replied to
    */
    std::optional<std::int32_t> checklistTaskId { };

    /**
     * @brief Optional. Persistent identifier of the specific poll option to be replied to
    */
    std::optional<std::string> pollOptionId { };
};

TGBOT_API void from_json(const nlohmann::json& json, ReplyParameters& value);
TGBOT_API void to_json(nlohmann::json& json, const ReplyParameters& value);

} // namespace TgBot
