// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>

namespace TgBot {

/**
 * @brief Describes why a request was unsuccessful.
 */
struct ResponseParameters {
    using Ptr = std::shared_ptr<ResponseParameters>;

    /**
     * @brief Optional. The group has been migrated to a supergroup with the specified identifier.
     * This number may have more than 32 significant bits and some programming languages may
     * have difficulty/silent defects in interpreting it. But it has at most 52 significant
     * bits, so a signed 64-bit integer or double-precision float type are safe for storing
     * this identifier.
    */
    std::optional<std::int64_t> migrateToChatId { };

    /**
     * @brief Optional. In case of exceeding flood control, the number of seconds left to wait before
     * the request can be repeated
    */
    std::optional<std::int32_t> retryAfter { };
};

TGBOT_API void from_json(const nlohmann::json& json, ResponseParameters& value);
TGBOT_API void to_json(nlohmann::json& json, const ResponseParameters& value);

} // namespace TgBot
