// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief The withdrawal is in progress.
 */
struct RevenueWithdrawalStatePending {
    using Ptr = std::shared_ptr<RevenueWithdrawalStatePending>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the state, always “pending”
    */
    std::string type { TYPE };
};

TGBOT_API void from_json(const nlohmann::json& json, RevenueWithdrawalStatePending& value);
TGBOT_API void to_json(nlohmann::json& json, const RevenueWithdrawalStatePending& value);

} // namespace TgBot
