// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct RevenueWithdrawalStateFailed;
struct RevenueWithdrawalStatePending;
struct RevenueWithdrawalStateSucceeded;

/**
 * @brief This object describes the state of a revenue withdrawal operation. Currently, it can be one
 * of RevenueWithdrawalStatePending RevenueWithdrawalStateSucceeded
 * RevenueWithdrawalStateFailed
 */
struct RevenueWithdrawalState {
    using Ptr = std::shared_ptr<RevenueWithdrawalState>;

    std::variant<std::shared_ptr<RevenueWithdrawalStatePending>, std::shared_ptr<RevenueWithdrawalStateSucceeded>,
                 std::shared_ptr<RevenueWithdrawalStateFailed>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, RevenueWithdrawalState& value);
TGBOT_API void to_json(nlohmann::json& json, const RevenueWithdrawalState& value);

} // namespace TgBot
