// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct RichTextAnchor;
struct RichTextAnchorLink;
struct RichTextBankCardNumber;
struct RichTextBold;
struct RichTextBotCommand;
struct RichTextCashtag;
struct RichTextCode;
struct RichTextCustomEmoji;
struct RichTextDateTime;
struct RichTextEmailAddress;
struct RichTextHashtag;
struct RichTextItalic;
struct RichTextMarked;
struct RichTextMathematicalExpression;
struct RichTextMention;
struct RichTextPhoneNumber;
struct RichTextReference;
struct RichTextReferenceLink;
struct RichTextSpoiler;
struct RichTextStrikethrough;
struct RichTextSubscript;
struct RichTextSuperscript;
struct RichTextTextMention;
struct RichTextUnderline;
struct RichTextUrl;

/**
 * @brief This object represents a rich formatted text. Currently, it can be either a String for plain
 * text, an Array of RichText, or any of the following types: RichTextBold RichTextItalic
 * RichTextUnderline RichTextStrikethrough RichTextSpoiler RichTextDateTime RichTextTextMention
 * RichTextSubscript RichTextSuperscript RichTextMarked RichTextCode RichTextCustomEmoji
 * RichTextMathematicalExpression RichTextUrl RichTextEmailAddress RichTextPhoneNumber
 * RichTextBankCardNumber RichTextMention RichTextHashtag RichTextCashtag RichTextBotCommand
 * RichTextAnchor RichTextAnchorLink RichTextReference RichTextReferenceLink
 */
struct RichText {
    using Ptr = std::shared_ptr<RichText>;

    std::variant<
        std::shared_ptr<RichTextBold>, std::shared_ptr<RichTextItalic>, std::shared_ptr<RichTextUnderline>,
        std::shared_ptr<RichTextStrikethrough>, std::shared_ptr<RichTextSpoiler>, std::shared_ptr<RichTextDateTime>,
        std::shared_ptr<RichTextTextMention>, std::shared_ptr<RichTextSubscript>, std::shared_ptr<RichTextSuperscript>,
        std::shared_ptr<RichTextMarked>, std::shared_ptr<RichTextCode>, std::shared_ptr<RichTextCustomEmoji>,
        std::shared_ptr<RichTextMathematicalExpression>, std::shared_ptr<RichTextUrl>,
        std::shared_ptr<RichTextEmailAddress>, std::shared_ptr<RichTextPhoneNumber>,
        std::shared_ptr<RichTextBankCardNumber>, std::shared_ptr<RichTextMention>, std::shared_ptr<RichTextHashtag>,
        std::shared_ptr<RichTextCashtag>, std::shared_ptr<RichTextBotCommand>, std::shared_ptr<RichTextAnchor>,
        std::shared_ptr<RichTextAnchorLink>, std::shared_ptr<RichTextReference>, std::shared_ptr<RichTextReferenceLink>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, RichText& value);
TGBOT_API void to_json(nlohmann::json& json, const RichText& value);

} // namespace TgBot
