// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A text with a phone number.
 */
struct RichTextPhoneNumber {
    using Ptr = std::shared_ptr<RichTextPhoneNumber>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “phone_number”
    */
    std::string type { TYPE };

    /**
     * @brief The text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The phone number
    */
    std::string phoneNumber { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextPhoneNumber& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextPhoneNumber& value);

} // namespace TgBot
