// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A bold text.
 */
struct RichTextBold {
    using Ptr = std::shared_ptr<RichTextBold>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “bold”
    */
    std::string type { TYPE };

    /**
     * @brief The text
    */
    std::shared_ptr<RichText> text { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextBold& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextBold& value);

} // namespace TgBot
