// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct RichBlockTableCell;
struct RichText;

/**
 * @brief A table, corresponding to the HTML tag <table>.
 */
struct RichBlockTable {
    using Ptr = std::shared_ptr<RichBlockTable>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “table”
    */
    std::string type { TYPE };

    /**
     * @brief Cells of the table
    */
    std::vector<std::vector<std::shared_ptr<RichBlockTableCell>>> cells { };

    /**
     * @brief Optional. True, if the table has borders
    */
    std::optional<bool> isBordered { };

    /**
     * @brief Optional. True, if the table is striped
    */
    std::optional<bool> isStriped { };

    /**
     * @brief Optional. Caption of the table
    */
    std::shared_ptr<RichText> caption { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichBlockTable& value);
TGBOT_API void to_json(nlohmann::json& json, const RichBlockTable& value);

} // namespace TgBot
