// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief A block with a mathematical expression in LaTeX format, corresponding to the custom HTML tag
 * <tg-math-block>.
 */
struct RichBlockMathematicalExpression {
    using Ptr = std::shared_ptr<RichBlockMathematicalExpression>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “mathematical_expression”
    */
    std::string type { TYPE };

    /**
     * @brief The mathematical expression in LaTeX format
    */
    std::string expression { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichBlockMathematicalExpression& value);
TGBOT_API void to_json(nlohmann::json& json, const RichBlockMathematicalExpression& value);

} // namespace TgBot
