// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A link to an anchor.
 */
struct RichTextAnchorLink {
    using Ptr = std::shared_ptr<RichTextAnchorLink>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “anchor_link”
    */
    std::string type { TYPE };

    /**
     * @brief The link text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The name of the anchor. If the name is empty, then the link brings back to the top of
     * the message.
    */
    std::string anchorName { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextAnchorLink& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextAnchorLink& value);

} // namespace TgBot
