// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>
#include <vector>

namespace TgBot {

struct RichBlock;
struct RichBlockCaption;

/**
 * @brief A slideshow, corresponding to the custom HTML tag <tg-slideshow>.
 */
struct RichBlockSlideshow {
    using Ptr = std::shared_ptr<RichBlockSlideshow>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “slideshow”
    */
    std::string type { TYPE };

    /**
     * @brief Elements of the slideshow
    */
    std::vector<std::shared_ptr<RichBlock>> blocks { };

    /**
     * @brief Optional. Caption of the block
    */
    std::shared_ptr<RichBlockCaption> caption { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichBlockSlideshow& value);
TGBOT_API void to_json(nlohmann::json& json, const RichBlockSlideshow& value);

} // namespace TgBot
