// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A cashtag.
 */
struct RichTextCashtag {
    using Ptr = std::shared_ptr<RichTextCashtag>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “cashtag”
    */
    std::string type { TYPE };

    /**
     * @brief The text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The cashtag
    */
    std::string cashtag { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextCashtag& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextCashtag& value);

} // namespace TgBot
