// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A link to a reference.
 */
struct RichTextReferenceLink {
    using Ptr = std::shared_ptr<RichTextReferenceLink>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “reference_link”
    */
    std::string type { TYPE };

    /**
     * @brief The link text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The name of the reference
    */
    std::string referenceName { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextReferenceLink& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextReferenceLink& value);

} // namespace TgBot
