// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct RichBlockCaption;
struct Video;

/**
 * @brief A block with a video, corresponding to the HTML tag <video>.
 */
struct RichBlockVideo {
    using Ptr = std::shared_ptr<RichBlockVideo>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the block, always “video”
    */
    std::string type { TYPE };

    /**
     * @brief The video
    */
    std::shared_ptr<Video> video { };

    /**
     * @brief Optional. True, if the media preview is covered by a spoiler animation
    */
    std::optional<bool> hasSpoiler { };

    /**
     * @brief Optional. Caption of the block
    */
    std::shared_ptr<RichBlockCaption> caption { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichBlockVideo& value);
TGBOT_API void to_json(nlohmann::json& json, const RichBlockVideo& value);

} // namespace TgBot
