// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;
struct User;

/**
 * @brief A mention of a Telegram user by their identifier.
 */
struct RichTextTextMention {
    using Ptr = std::shared_ptr<RichTextTextMention>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “text_mention”
    */
    std::string type { TYPE };

    /**
     * @brief The text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The mentioned user
    */
    std::shared_ptr<User> user { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextTextMention& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextTextMention& value);

} // namespace TgBot
