// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A reference.
 */
struct RichTextReference {
    using Ptr = std::shared_ptr<RichTextReference>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “reference”
    */
    std::string type { TYPE };

    /**
     * @brief Text of the reference
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The name of the reference
    */
    std::string name { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextReference& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextReference& value);

} // namespace TgBot
