// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A text with a bank card number.
 */
struct RichTextBankCardNumber {
    using Ptr = std::shared_ptr<RichTextBankCardNumber>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “bank_card_number”
    */
    std::string type { TYPE };

    /**
     * @brief The text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The bank card number
    */
    std::string bankCardNumber { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextBankCardNumber& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextBankCardNumber& value);

} // namespace TgBot
