// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct RichText;

/**
 * @brief A hashtag.
 */
struct RichTextHashtag {
    using Ptr = std::shared_ptr<RichTextHashtag>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the rich text, always “hashtag”
    */
    std::string type { TYPE };

    /**
     * @brief The text
    */
    std::shared_ptr<RichText> text { };

    /**
     * @brief The hashtag
    */
    std::string hashtag { };
};

TGBOT_API void from_json(const nlohmann::json& json, RichTextHashtag& value);
TGBOT_API void to_json(nlohmann::json& json, const RichTextHashtag& value);

} // namespace TgBot
