// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>

namespace TgBot {

/**
 * @brief Describes an amount of Telegram Stars.
 */
struct StarAmount {
    using Ptr = std::shared_ptr<StarAmount>;

    /**
     * @brief Integer amount of Telegram Stars, rounded to 0; can be negative
    */
    std::int32_t amount { };

    /**
     * @brief Optional. The number of 1/1000000000 shares of Telegram Stars; from -999999999 to
     * 999999999; can be negative if and only if amount is non-positive
    */
    std::optional<std::int32_t> nanostarAmount { };
};

TGBOT_API void from_json(const nlohmann::json& json, StarAmount& value);
TGBOT_API void to_json(nlohmann::json& json, const StarAmount& value);

} // namespace TgBot
