// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct TransactionPartner;

/**
 * @brief Describes a Telegram Star transaction. Note that if the buyer initiates a chargeback with
 * the payment provider from whom they acquired Stars (e.g., Apple, Google) following this
 * transaction, the refunded Stars will be deducted from the bot's balance. This is outside of
 * Telegram's control.
 */
struct StarTransaction {
    using Ptr = std::shared_ptr<StarTransaction>;

    /**
     * @brief Unique identifier of the transaction. Coincides with the identifier of the original
     * transaction for refund transactions. Coincides with
     * SuccessfulPayment.telegram_payment_charge_id for successful incoming payments from
     * users.
    */
    std::string id { };

    /**
     * @brief Integer amount of Telegram Stars transferred by the transaction
    */
    std::int32_t amount { };

    /**
     * @brief Optional. The number of 1/1000000000 shares of Telegram Stars transferred by the
     * transaction; from 0 to 999999999
    */
    std::optional<std::int32_t> nanostarAmount { };

    /**
     * @brief Date the transaction was created in Unix time
    */
    std::int32_t date { };

    /**
     * @brief Optional. Source of an incoming transaction (e.g., a user purchasing goods or services,
     * Fragment refunding a failed withdrawal). Only for incoming transactions.
    */
    std::shared_ptr<TransactionPartner> source { };

    /**
     * @brief Optional. Receiver of an outgoing transaction (e.g., a user for a purchase refund,
     * Fragment for a withdrawal). Only for outgoing transactions.
    */
    std::shared_ptr<TransactionPartner> receiver { };
};

TGBOT_API void from_json(const nlohmann::json& json, StarTransaction& value);
TGBOT_API void to_json(nlohmann::json& json, const StarTransaction& value);

} // namespace TgBot
