// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>
#include <vector>

namespace TgBot {

struct PhotoSize;
struct Sticker;

/**
 * @brief This object represents a sticker set.
 */
struct StickerSet {
    using Ptr = std::shared_ptr<StickerSet>;

    enum class Type { Regular, Mask, CustomEmoji };

    /**
     * @brief Sticker set name
    */
    std::string name { };

    /**
     * @brief Sticker set title
    */
    std::string title { };

    /**
     * @brief Type of stickers in the set, currently one of “regular”, “mask”, “custom_emoji”
    */
    Type stickerType { };

    /**
     * @brief List of all set stickers
    */
    std::vector<std::shared_ptr<Sticker>> stickers { };

    /**
     * @brief Optional. Sticker set thumbnail in the .WEBP, .TGS, or .WEBM format
    */
    std::shared_ptr<PhotoSize> thumbnail { };
};

TGBOT_API void from_json(const nlohmann::json& json, StickerSet::Type& value);
TGBOT_API void to_json(nlohmann::json& json, const StickerSet::Type& value);

TGBOT_API void from_json(const nlohmann::json& json, StickerSet& value);
TGBOT_API void to_json(nlohmann::json& json, const StickerSet& value);

} // namespace TgBot
