// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct ReactionType;

/**
 * @brief Describes a story area pointing to a suggested reaction. Currently, a story can have up to 5
 * suggested reaction areas.
 */
struct StoryAreaTypeSuggestedReaction {
    using Ptr = std::shared_ptr<StoryAreaTypeSuggestedReaction>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the area, always “suggested_reaction”
    */
    std::string type { TYPE };

    /**
     * @brief Type of the reaction
    */
    std::shared_ptr<ReactionType> reactionType { };

    /**
     * @brief Optional. Pass True if the reaction area has a dark background
    */
    std::optional<bool> isDark { };

    /**
     * @brief Optional. Pass True if reaction area corner is flipped
    */
    std::optional<bool> isFlipped { };
};

TGBOT_API void from_json(const nlohmann::json& json, StoryAreaTypeSuggestedReaction& value);
TGBOT_API void to_json(nlohmann::json& json, const StoryAreaTypeSuggestedReaction& value);

} // namespace TgBot
