// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Describes a story area containing weather information. Currently, a story can have up to 3
 * weather areas.
 */
struct StoryAreaTypeWeather {
    using Ptr = std::shared_ptr<StoryAreaTypeWeather>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the area, always “weather”
    */
    std::string type { TYPE };

    /**
     * @brief Temperature, in degree Celsius
    */
    double temperature { };

    /**
     * @brief Emoji representing the weather
    */
    std::string emoji { };

    /**
     * @brief A color of the area background in the ARGB format
    */
    std::int32_t backgroundColor { };
};

TGBOT_API void from_json(const nlohmann::json& json, StoryAreaTypeWeather& value);
TGBOT_API void to_json(nlohmann::json& json, const StoryAreaTypeWeather& value);

} // namespace TgBot
