// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Describes a story area pointing to a unique gift. Currently, a story can have at most 1
 * unique gift area.
 */
struct StoryAreaTypeUniqueGift {
    using Ptr = std::shared_ptr<StoryAreaTypeUniqueGift>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the area, always “unique_gift”
    */
    std::string type { TYPE };

    /**
     * @brief Unique name of the gift
    */
    std::string name { };
};

TGBOT_API void from_json(const nlohmann::json& json, StoryAreaTypeUniqueGift& value);
TGBOT_API void to_json(nlohmann::json& json, const StoryAreaTypeUniqueGift& value);

} // namespace TgBot
