// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

struct Chat;

/**
 * @brief This object represents a story.
 */
struct Story {
    using Ptr = std::shared_ptr<Story>;

    /**
     * @brief Chat that posted the story
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Unique identifier for the story in the chat
    */
    std::int32_t id { };
};

TGBOT_API void from_json(const nlohmann::json& json, Story& value);
TGBOT_API void to_json(nlohmann::json& json, const Story& value);

} // namespace TgBot
