// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <variant>

namespace TgBot {

struct StoryAreaTypeLink;
struct StoryAreaTypeLocation;
struct StoryAreaTypeSuggestedReaction;
struct StoryAreaTypeUniqueGift;
struct StoryAreaTypeWeather;

/**
 * @brief Describes the type of a clickable area on a story. Currently, it can be one of
 * StoryAreaTypeLocation StoryAreaTypeSuggestedReaction StoryAreaTypeLink StoryAreaTypeWeather
 * StoryAreaTypeUniqueGift
 */
struct StoryAreaType {
    using Ptr = std::shared_ptr<StoryAreaType>;

    std::variant<std::shared_ptr<StoryAreaTypeLocation>, std::shared_ptr<StoryAreaTypeSuggestedReaction>,
                 std::shared_ptr<StoryAreaTypeLink>, std::shared_ptr<StoryAreaTypeWeather>,
                 std::shared_ptr<StoryAreaTypeUniqueGift>>
        value;
};

TGBOT_API void from_json(const nlohmann::json& json, StoryAreaType& value);
TGBOT_API void to_json(nlohmann::json& json, const StoryAreaType& value);

} // namespace TgBot
