// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct OrderInfo;

/**
 * @brief This object contains basic information about a successful payment. Note that if the buyer
 * initiates a chargeback with the relevant payment provider following this transaction, the
 * funds may be debited from your balance. This is outside of Telegram's control.
 */
struct SuccessfulPayment {
    using Ptr = std::shared_ptr<SuccessfulPayment>;

    /**
     * @brief Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars
    */
    std::string currency { };

    /**
     * @brief Total price in the smallest units of the currency (integer, not float/double). For
     * example, for a price of US$ 1.45 pass amount = 145. See the exp parameter in
     * currencies.json, it shows the number of digits past the decimal point for each currency
     * (2 for the majority of currencies).
    */
    std::int32_t totalAmount { };

    /**
     * @brief Bot-specified invoice payload
    */
    std::string invoicePayload { };

    /**
     * @brief Optional. Expiration date of the subscription, in Unix time; for recurring payments only
    */
    std::optional<std::int32_t> subscriptionExpirationDate { };

    /**
     * @brief Optional. True, if the payment is a recurring payment for a subscription
    */
    std::optional<bool> isRecurring { };

    /**
     * @brief Optional. True, if the payment is the first payment for a subscription
    */
    std::optional<bool> isFirstRecurring { };

    /**
     * @brief Optional. Identifier of the shipping option chosen by the user
    */
    std::optional<std::string> shippingOptionId { };

    /**
     * @brief Optional. Order information provided by the user
    */
    std::shared_ptr<OrderInfo> orderInfo { };

    /**
     * @brief Telegram payment identifier
    */
    std::string telegramPaymentChargeId { };

    /**
     * @brief Provider payment identifier
    */
    std::string providerPaymentChargeId { };
};

TGBOT_API void from_json(const nlohmann::json& json, SuccessfulPayment& value);
TGBOT_API void to_json(nlohmann::json& json, const SuccessfulPayment& value);

} // namespace TgBot
