// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Describes the price of a suggested post.
 */
struct SuggestedPostPrice {
    using Ptr = std::shared_ptr<SuggestedPostPrice>;

    /**
     * @brief Currency in which the post will be paid. Currently, must be one of “XTR” for Telegram
     * Stars or “TON” for TON grams.
    */
    std::string currency { };

    /**
     * @brief The amount of the currency that will be paid for the post in the smallest units of the
     * currency, i.e. Telegram Stars or nanograms. Currently, price in Telegram Stars must be
     * between 5 and 100000, and price in nanograms must be between 10000000 and
     * 10000000000000.
    */
    std::int32_t amount { };
};

TGBOT_API void from_json(const nlohmann::json& json, SuggestedPostPrice& value);
TGBOT_API void to_json(nlohmann::json& json, const SuggestedPostPrice& value);

} // namespace TgBot
