// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct SuggestedPostPrice;

/**
 * @brief Contains information about a suggested post.
 */
struct SuggestedPostInfo {
    using Ptr = std::shared_ptr<SuggestedPostInfo>;

    /**
     * @brief State of the suggested post. Currently, it can be one of “pending”, “approved”,
     * “declined”.
    */
    std::string state { };

    /**
     * @brief Optional. Proposed price of the post. If the field is omitted, then the post is unpaid.
    */
    std::shared_ptr<SuggestedPostPrice> price { };

    /**
     * @brief Optional. Proposed send date of the post. If the field is omitted, then the post can be
     * published at any time within 30 days at the sole discretion of the user or administrator
     * who approves it.
    */
    std::optional<std::int32_t> sendDate { };
};

TGBOT_API void from_json(const nlohmann::json& json, SuggestedPostInfo& value);
TGBOT_API void to_json(nlohmann::json& json, const SuggestedPostInfo& value);

} // namespace TgBot
