// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct MessageEntity;

/**
 * @brief This object contains information about the quoted part of a message that is replied to by
 * the given message.
 */
struct TextQuote {
    using Ptr = std::shared_ptr<TextQuote>;

    /**
     * @brief Text of the quoted part of a message that is replied to by the given message
    */
    std::string text { };

    /**
     * @brief Optional. Special entities that appear in the quote. Currently, only bold, italic,
     * underline, strikethrough, spoiler, custom_emoji, and date_time entities are kept in
     * quotes.
    */
    std::optional<std::vector<std::shared_ptr<MessageEntity>>> entities { };

    /**
     * @brief Approximate quote position in the original message in UTF-16 code units as specified by
     * the sender
    */
    std::int32_t position { };

    /**
     * @brief Optional. True, if the quote was chosen manually by the message sender. Otherwise, the
     * quote was added automatically by the server.
    */
    std::optional<bool> isManual { };
};

TGBOT_API void from_json(const nlohmann::json& json, TextQuote& value);
TGBOT_API void to_json(nlohmann::json& json, const TextQuote& value);

} // namespace TgBot
