// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Describes a transaction with an unknown source or recipient.
 */
struct TransactionPartnerOther {
    using Ptr = std::shared_ptr<TransactionPartnerOther>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the transaction partner, always “other”
    */
    std::string type { TYPE };
};

TGBOT_API void from_json(const nlohmann::json& json, TransactionPartnerOther& value);
TGBOT_API void to_json(nlohmann::json& json, const TransactionPartnerOther& value);

} // namespace TgBot
