// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

struct Chat;
struct Gift;

/**
 * @brief Describes a transaction with a chat.
 */
struct TransactionPartnerChat {
    using Ptr = std::shared_ptr<TransactionPartnerChat>;

    static TGBOT_API const std::string TYPE;

    /**
     * @brief Type of the transaction partner, always “chat”
    */
    std::string type { TYPE };

    /**
     * @brief Information about the chat
    */
    std::shared_ptr<Chat> chat { };

    /**
     * @brief Optional. The gift sent to the chat by the bot
    */
    std::shared_ptr<Gift> gift { };
};

TGBOT_API void from_json(const nlohmann::json& json, TransactionPartnerChat& value);
TGBOT_API void to_json(nlohmann::json& json, const TransactionPartnerChat& value);

} // namespace TgBot
