// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

struct Sticker;

/**
 * @brief This object describes the model of a unique gift.
 */
struct UniqueGiftModel {
    using Ptr = std::shared_ptr<UniqueGiftModel>;

    /**
     * @brief Name of the model
    */
    std::string name { };

    /**
     * @brief The sticker that represents the unique gift
    */
    std::shared_ptr<Sticker> sticker { };

    /**
     * @brief The number of unique gifts that receive this model for every 1000 gift upgrades. Always
     * 0 for crafted gifts.
    */
    std::int32_t rarityPerMille { };

    /**
     * @brief Optional. Rarity of the model if it is a crafted model. Currently, can be “uncommon”,
     * “rare”, “epic”, or “legendary”.
    */
    std::optional<std::string> rarity { };
};

TGBOT_API void from_json(const nlohmann::json& json, UniqueGiftModel& value);
TGBOT_API void to_json(nlohmann::json& json, const UniqueGiftModel& value);

} // namespace TgBot
