// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

struct BotSubscriptionUpdated;
struct BusinessConnection;
struct BusinessMessagesDeleted;
struct CallbackQuery;
struct ChatBoostRemoved;
struct ChatBoostUpdated;
struct ChatJoinRequest;
struct ChatMemberUpdated;
struct ChosenInlineResult;
struct InlineQuery;
struct ManagedBotUpdated;
struct Message;
struct MessageReactionCountUpdated;
struct MessageReactionUpdated;
struct PaidMediaPurchased;
struct Poll;
struct PollAnswer;
struct PreCheckoutQuery;
struct ShippingQuery;

/**
 * @brief This object represents an incoming update.At most one of the optional fields can be present
 * in any given update.
 */
struct Update {
    using Ptr = std::shared_ptr<Update>;

    /**
     * @brief The update's unique identifier. Update identifiers start from a certain positive number
     * and increase sequentially. This identifier becomes especially handy if you're using
     * webhooks, since it allows you to ignore repeated updates or to restore the correct
     * update sequence, should they get out of order. If there are no new updates for at least
     * a week, then identifier of the next update will be chosen randomly instead of
     * sequentially.
    */
    std::int32_t updateId { };

    /**
     * @brief Optional. New incoming message of any kind - text, photo, sticker, etc.
    */
    std::shared_ptr<Message> message { };

    /**
     * @brief Optional. New version of a message that is known to the bot and was edited. This update
     * may at times be triggered by changes to message fields that are either unavailable or
     * not actively used by your bot.
    */
    std::shared_ptr<Message> editedMessage { };

    /**
     * @brief Optional. New incoming channel post of any kind - text, photo, sticker, etc.
    */
    std::shared_ptr<Message> channelPost { };

    /**
     * @brief Optional. New version of a channel post that is known to the bot and was edited. This
     * update may at times be triggered by changes to message fields that are either
     * unavailable or not actively used by your bot.
    */
    std::shared_ptr<Message> editedChannelPost { };

    /**
     * @brief Optional. The bot was connected to or disconnected from a business account, or a user
     * edited an existing connection with the bot
    */
    std::shared_ptr<BusinessConnection> businessConnection { };

    /**
     * @brief Optional. New message from a connected business account
    */
    std::shared_ptr<Message> businessMessage { };

    /**
     * @brief Optional. New version of a message from a connected business account
    */
    std::shared_ptr<Message> editedBusinessMessage { };

    /**
     * @brief Optional. Messages were deleted from a connected business account
    */
    std::shared_ptr<BusinessMessagesDeleted> deletedBusinessMessages { };

    /**
     * @brief Optional. New guest message. The bot can use the field Message.guest_query_id and the
     * method answerGuestQuery to send a message in response.
    */
    std::shared_ptr<Message> guestMessage { };

    /**
     * @brief Optional. A reaction to a message was changed by a user. The bot must be an
     * administrator in the chat and must explicitly specify "message_reaction" in the list of
     * allowed_updates to receive these updates. The update isn't received for reactions set by
     * bots.
    */
    std::shared_ptr<MessageReactionUpdated> messageReaction { };

    /**
     * @brief Optional. Reactions to a message with anonymous reactions were changed. The bot must be
     * an administrator in the chat and must explicitly specify "message_reaction_count" in the
     * list of allowed_updates to receive these updates. The updates are grouped and can be
     * sent with delay up to a few minutes.
    */
    std::shared_ptr<MessageReactionCountUpdated> messageReactionCount { };

    /**
     * @brief Optional. New incoming inline query
    */
    std::shared_ptr<InlineQuery> inlineQuery { };

    /**
     * @brief Optional. The result of an inline query that was chosen by a user and sent to their chat
     * partner. Please see our documentation on the feedback collecting for details on how to
     * enable these updates for your bot.
    */
    std::shared_ptr<ChosenInlineResult> chosenInlineResult { };

    /**
     * @brief Optional. New incoming callback query
    */
    std::shared_ptr<CallbackQuery> callbackQuery { };

    /**
     * @brief Optional. New incoming shipping query. Only for invoices with flexible price.
    */
    std::shared_ptr<ShippingQuery> shippingQuery { };

    /**
     * @brief Optional. New incoming pre-checkout query. Contains full information about checkout.
    */
    std::shared_ptr<PreCheckoutQuery> preCheckoutQuery { };

    /**
     * @brief Optional. A user purchased paid media with a non-empty payload sent by the bot in a non-
     * channel chat
    */
    std::shared_ptr<PaidMediaPurchased> purchasedPaidMedia { };

    /**
     * @brief Optional. New poll state. Bots receive only updates about manually stopped polls and
     * polls, which are sent by the bot.
    */
    std::shared_ptr<Poll> poll { };

    /**
     * @brief Optional. A user changed their answer in a non-anonymous poll. Bots receive new votes
     * only in polls that were sent by the bot itself.
    */
    std::shared_ptr<PollAnswer> pollAnswer { };

    /**
     * @brief Optional. The bot's chat member status was updated in a chat. For private chats, this
     * update is received only when the bot is blocked or unblocked by the user.
    */
    std::shared_ptr<ChatMemberUpdated> myChatMember { };

    /**
     * @brief Optional. A chat member's status was updated in a chat. The bot must be an administrator
     * in the chat and must explicitly specify "chat_member" in the list of allowed_updates to
     * receive these updates.
    */
    std::shared_ptr<ChatMemberUpdated> chatMember { };

    /**
     * @brief Optional. A request to join the chat has been sent. The bot must have the
     * can_invite_users administrator right in the chat to receive these updates.
    */
    std::shared_ptr<ChatJoinRequest> chatJoinRequest { };

    /**
     * @brief Optional. A chat boost was added or changed. The bot must be an administrator in the
     * chat to receive these updates.
    */
    std::shared_ptr<ChatBoostUpdated> chatBoost { };

    /**
     * @brief Optional. A boost was removed from a chat. The bot must be an administrator in the chat
     * to receive these updates.
    */
    std::shared_ptr<ChatBoostRemoved> removedChatBoost { };

    /**
     * @brief Optional. A new bot was created to be managed by the bot, or token or owner of a managed
     * bot was changed
    */
    std::shared_ptr<ManagedBotUpdated> managedBot { };

    /**
     * @brief Optional. User payment subscription has changed
    */
    std::shared_ptr<BotSubscriptionUpdated> subscription { };
};

TGBOT_API void from_json(const nlohmann::json& json, Update& value);
TGBOT_API void to_json(nlohmann::json& json, const Update& value);

} // namespace TgBot
