// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <vector>

namespace TgBot {

struct ChatBoost;

/**
 * @brief This object represents a list of boosts added to a chat by a user.
 */
struct UserChatBoosts {
    using Ptr = std::shared_ptr<UserChatBoosts>;

    /**
     * @brief The list of boosts added to the chat by the user
    */
    std::vector<std::shared_ptr<ChatBoost>> boosts { };
};

TGBOT_API void from_json(const nlohmann::json& json, UserChatBoosts& value);
TGBOT_API void to_json(nlohmann::json& json, const UserChatBoosts& value);

} // namespace TgBot
