// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <vector>

namespace TgBot {

struct PhotoSize;

/**
 * @brief This object represent a user's profile pictures.
 */
struct UserProfilePhotos {
    using Ptr = std::shared_ptr<UserProfilePhotos>;

    /**
     * @brief Total number of profile pictures the target user has
    */
    std::int32_t totalCount { };

    /**
     * @brief Requested profile pictures (in up to 4 sizes each)
    */
    std::vector<std::vector<std::shared_ptr<PhotoSize>>> photos { };
};

TGBOT_API void from_json(const nlohmann::json& json, UserProfilePhotos& value);
TGBOT_API void to_json(nlohmann::json& json, const UserProfilePhotos& value);

} // namespace TgBot
