// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <vector>

namespace TgBot {

struct Audio;

/**
 * @brief This object represents the audios displayed on a user's profile.
 */
struct UserProfileAudios {
    using Ptr = std::shared_ptr<UserProfileAudios>;

    /**
     * @brief Total number of profile audios for the target user
    */
    std::int32_t totalCount { };

    /**
     * @brief Requested profile audios
    */
    std::vector<std::shared_ptr<Audio>> audios { };
};

TGBOT_API void from_json(const nlohmann::json& json, UserProfileAudios& value);
TGBOT_API void to_json(nlohmann::json& json, const UserProfileAudios& value);

} // namespace TgBot
