// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents a Telegram user or bot.
 */
struct User {
    using Ptr = std::shared_ptr<User>;

    /**
     * @brief Unique identifier for this user or bot. This number may have more than 32 significant
     * bits and some programming languages may have difficulty/silent defects in interpreting
     * it. But it has at most 52 significant bits, so a 64-bit integer or double-precision
     * float type are safe for storing this identifier.
    */
    std::int64_t id { };

    /**
     * @brief True, if this user is a bot
    */
    bool isBot { };

    /**
     * @brief User's or bot's first name
    */
    std::string firstName { };

    /**
     * @brief Optional. User's or bot's last name
    */
    std::optional<std::string> lastName { };

    /**
     * @brief Optional. User's or bot's username
    */
    std::optional<std::string> username { };

    /**
     * @brief Optional. IETF language tag of the user's language
    */
    std::optional<std::string> languageCode { };

    /**
     * @brief Optional. True, if this user is a Telegram Premium user
    */
    std::optional<bool> isPremium { };

    /**
     * @brief Optional. True, if this user added the bot to the attachment menu
    */
    std::optional<bool> addedToAttachmentMenu { };

    /**
     * @brief Optional. True, if the bot can be invited to groups. Returned only in getMe.
    */
    std::optional<bool> canJoinGroups { };

    /**
     * @brief Optional. True, if privacy mode is disabled for the bot. Returned only in getMe.
    */
    std::optional<bool> canReadAllGroupMessages { };

    /**
     * @brief Optional. True, if the bot supports guest queries from chats it is not a member of.
     * Returned only in getMe.
    */
    std::optional<bool> supportsGuestQueries { };

    /**
     * @brief Optional. True, if the bot supports inline queries. Returned only in getMe.
    */
    std::optional<bool> supportsInlineQueries { };

    /**
     * @brief Optional. True, if the bot can be connected to a user account to manage it. Returned
     * only in getMe.
    */
    std::optional<bool> canConnectToBusiness { };

    /**
     * @brief Optional. True, if the bot has a main Web App. Returned only in getMe.
    */
    std::optional<bool> hasMainWebApp { };

    /**
     * @brief Optional. True, if the bot has forum topic mode enabled in private chats. Returned only
     * in getMe.
    */
    std::optional<bool> hasTopicsEnabled { };

    /**
     * @brief Optional. True, if the bot allows users to create and delete topics in private chats.
     * Returned only in getMe.
    */
    std::optional<bool> allowsUsersToCreateTopics { };

    /**
     * @brief Optional. True, if other bots can be created to be controlled by the bot. Returned only
     * in getMe.
    */
    std::optional<bool> canManageBots { };

    /**
     * @brief Optional. True, if the bot supports join request queries and can be assigned to process
     * them. Returned only in getMe.
    */
    std::optional<bool> supportsJoinRequestQueries { };
};

TGBOT_API void from_json(const nlohmann::json& json, User& value);
TGBOT_API void to_json(nlohmann::json& json, const User& value);

} // namespace TgBot
