// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

struct PhotoSize;
struct VideoQuality;

/**
 * @brief This object represents a video file.
 */
struct Video {
    using Ptr = std::shared_ptr<Video>;

    /**
     * @brief Identifier for this file, which can be used to download or reuse the file
    */
    std::string fileId { };

    /**
     * @brief Unique identifier for this file, which is supposed to be the same over time and for
     * different bots. Can't be used to download or reuse the file.
    */
    std::string fileUniqueId { };

    /**
     * @brief Video width as defined by the sender
    */
    std::int32_t width { };

    /**
     * @brief Video height as defined by the sender
    */
    std::int32_t height { };

    /**
     * @brief Duration of the video in seconds as defined by the sender
    */
    std::int32_t duration { };

    /**
     * @brief Optional. Video thumbnail
    */
    std::shared_ptr<PhotoSize> thumbnail { };

    /**
     * @brief Optional. Available sizes of the cover of the video in the message
    */
    std::optional<std::vector<std::shared_ptr<PhotoSize>>> cover { };

    /**
     * @brief Optional. Timestamp in seconds from which the video will play in the message
    */
    std::optional<std::int32_t> startTimestamp { };

    /**
     * @brief Optional. List of available qualities of the video
    */
    std::optional<std::vector<std::shared_ptr<VideoQuality>>> qualities { };

    /**
     * @brief Optional. Original filename as defined by the sender
    */
    std::optional<std::string> fileName { };

    /**
     * @brief Optional. MIME type of the file as defined by the sender
    */
    std::optional<std::string> mimeType { };

    /**
     * @brief Optional. File size in bytes. It can be bigger than 2^31 and some programming languages
     * may have difficulty/silent defects in interpreting it. But it has at most 52 significant
     * bits, so a signed 64-bit integer or double-precision float type are safe for storing
     * this value.
    */
    std::optional<std::int64_t> fileSize { };
};

TGBOT_API void from_json(const nlohmann::json& json, Video& value);
TGBOT_API void to_json(nlohmann::json& json, const Video& value);

} // namespace TgBot
