// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>

namespace TgBot {

/**
 * @brief This object represents a service message about a video chat scheduled in the chat.
 */
struct VideoChatScheduled {
    using Ptr = std::shared_ptr<VideoChatScheduled>;

    /**
     * @brief Point in time (Unix timestamp) when the video chat is supposed to be started by a chat
     * administrator
    */
    std::int32_t startDate { };
};

TGBOT_API void from_json(const nlohmann::json& json, VideoChatScheduled& value);
TGBOT_API void to_json(nlohmann::json& json, const VideoChatScheduled& value);

} // namespace TgBot
