// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>

namespace TgBot {

/**
 * @brief This object represents a voice note.
 */
struct Voice {
    using Ptr = std::shared_ptr<Voice>;

    /**
     * @brief Identifier for this file, which can be used to download or reuse the file
    */
    std::string fileId { };

    /**
     * @brief Unique identifier for this file, which is supposed to be the same over time and for
     * different bots. Can't be used to download or reuse the file.
    */
    std::string fileUniqueId { };

    /**
     * @brief Duration of the audio in seconds as defined by the sender
    */
    std::int32_t duration { };

    /**
     * @brief Optional. MIME type of the file as defined by the sender
    */
    std::optional<std::string> mimeType { };

    /**
     * @brief Optional. File size in bytes. It can be bigger than 2^31 and some programming languages
     * may have difficulty/silent defects in interpreting it. But it has at most 52 significant
     * bits, so a signed 64-bit integer or double-precision float type are safe for storing
     * this value.
    */
    std::optional<std::int64_t> fileSize { };
};

TGBOT_API void from_json(const nlohmann::json& json, Voice& value);
TGBOT_API void to_json(nlohmann::json& json, const Voice& value);

} // namespace TgBot
