// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <string>

namespace TgBot {

/**
 * @brief Describes data sent from a Web App to the bot.
 */
struct WebAppData {
    using Ptr = std::shared_ptr<WebAppData>;

    /**
     * @brief The data. Be aware that a bad client can send arbitrary data in this field.
    */
    std::string data { };

    /**
     * @brief Text of the web_app keyboard button from which the Web App was opened. Be aware that a
     * bad client can send arbitrary data in this field.
    */
    std::string buttonText { };
};

TGBOT_API void from_json(const nlohmann::json& json, WebAppData& value);
TGBOT_API void to_json(nlohmann::json& json, const WebAppData& value);

} // namespace TgBot
