// Generated by `make api-generate`. Do not edit.

#pragma once

#include "tgbot/export.h"

#include <cstdint>
#include <memory>
#include <nlohmann/json_fwd.hpp>
#include <optional>
#include <string>
#include <vector>

namespace TgBot {

/**
 * @brief Describes the current status of a webhook.
 */
struct WebhookInfo {
    using Ptr = std::shared_ptr<WebhookInfo>;

    /**
     * @brief Webhook URL, may be empty if webhook is not set up
    */
    std::string url { };

    /**
     * @brief True, if a custom certificate was provided for webhook certificate checks
    */
    bool hasCustomCertificate { };

    /**
     * @brief Number of updates awaiting delivery
    */
    std::int32_t pendingUpdateCount { };

    /**
     * @brief Optional. Currently used webhook IP address
    */
    std::optional<std::string> ipAddress { };

    /**
     * @brief Optional. Unix time for the most recent error that happened when trying to deliver an
     * update via webhook
    */
    std::optional<std::int32_t> lastErrorDate { };

    /**
     * @brief Optional. Error message in human-readable format for the most recent error that happened
     * when trying to deliver an update via webhook
    */
    std::optional<std::string> lastErrorMessage { };

    /**
     * @brief Optional. Unix time of the most recent error that happened when trying to synchronize
     * available updates with Telegram datacenters
    */
    std::optional<std::int32_t> lastSynchronizationErrorDate { };

    /**
     * @brief Optional. The maximum allowed number of simultaneous HTTPS connections to the webhook
     * for update delivery
    */
    std::optional<std::int32_t> maxConnections { };

    /**
     * @brief Optional. A list of update types the bot is subscribed to. Defaults to all update types
     * except chat_member, message_reaction, and message_reaction_count.
    */
    std::optional<std::vector<std::string>> allowedUpdates { };
};

TGBOT_API void from_json(const nlohmann::json& json, WebhookInfo& value);
TGBOT_API void to_json(nlohmann::json& json, const WebhookInfo& value);

} // namespace TgBot
